//
// Copyright (c) 2017, 2023 Contributors to the Eclipse Foundation
//

[appendix]
== Revision History

This appendix lists the significant changes
that have been made during the development of the Java Persistence 2.2
specification.

=== Maintenance Release Draft

Created document from Java Persistence 2.1
Final Release specification.

The following annotations have been marked _@Repeatable_:

* AssociationOverride
* AttributeOverride
* Convert
* JoinColumn
* MapKeyJoinColumn
* NamedEntityGraph
* NamedNativeQuery
* NamedQuery
* NamedStoredProcedureQuery
* PersistenceContext
* PersistenceUnit
* PrimaryKeyJoinColumn
* SecondaryTable
* SqlResultSetMapping
* SequenceGenerator
* TableGenerator

Added SequenceGenerators and TableGenerators annotations.

Added support for CDI injection into
AttributeConverter classes.

Added support for the mapping of the following java.time types:

* java.time.LocalDate
* java.time.LocalTime
* java.time.LocalDateTime
* java.time.OffsetTime
* java.time.OffsetDateTime

Added default Stream getResultStream() method
to Query interface.

Added default Stream<X> getResultStream()
method to TypedQuery interface.

Replaced reference to JAR file specification
in persistence provider bootstrapping section with more general
reference to Java SE service provider requirements.

Updated persistence.xml and orm.xml schemas to 2.2 versions.

Updated Related Documents.

=== Jakarta Persistence 3.0

Created document from Java Persistence 2.2 Final Release specification.

The document was converted to _Asciidoc_ format.

Packages of all API classes were changed to _jakarta.persistence_. These changes are reflected in the specification document.

Schema namespaces were changed from http://xmlns.jcp.org/xml/ns/persistence and http://xmlns.jcp.org/xml/ns/persistence/orm
to https://jakarta.ee/xml/ns/persistence and https://jakarta.ee/xml/ns/persistence/orm

References to schema versions lower than 2.2 were removed.

=== Jakarta Persistence 3.1

`EntityManagerFactory` and `EntityManager` interfaces extend `java.lang.AutoCloseable` interface

Fixed `ClassTransformer.transform` to throw Persistence API specific exception

Added support for `java.util.UUID` and `GenerationType.UUID`

Added _CEILING_, _EXP_, _FLOOR_, _LN_, _POWER_, _ROUND_, and _SIGN_
numeric functions to Jakarta Persistence QL and _ceiling()_, _exp()_,
_floor(), _ln()_, _power()_,  _round()_, and _sign()_ to Criteria API

Added _LOCAL DATE_, _LOCAL DATETIME_, and _LOCAL TIME_ functions to Jakarta Persistence QL and
corresponding _localDate()_, _localDateTime()_, and _localTime()_ to Criteria API

Added _EXTRACT_ function to Jakarta Persistence QL

Added support for __Expression__s as conditions in _Criteria_ `CASE` expressions

Clarified mixing types of query input parameters

Added missing definition of _single_valued_embeddable_object_field_ in Jakarta Persistence QL BNF

Clarified definition of the _Basic_ type

Clarified the order of parameters in the _LOCATE_ function

Clarified `SqlResultSetMapping` with multiple ``EntityResult``s and conflicting aliases

=== Jakarta Persistence 3.2

Added support for Java record types as embeddable classes

Added support for _java.time.Instant_ and _java.time.Year_ and clarified JDBC mappings for basic types

Added `union`, `intersect`, `except`, `cast`, `left`, `right`, and `replace` for JPQL and criteria queries

Added `||` string concatenation operator to JPQL

Added _extract()_ to _CriteriaBuilder_

Added _subquery(EntityType)_ to _CommonAbstractCriteria_

Added support for specifying null precedence when ordering JPQL and criteria queries

Added _getSingleResultOrNull()_ to _Query_, _TypedQuery_, _StoredProcedureQuery_

Added _entities()_, _classes()_ and _columns()_ to _NamedNativeQuery_

Added _lockMode()_ to _EntityResult_ with the default being `OPTIMISTIC`

Added _getVersion()_, _isLoaded()_, _load()_, _isInstance()_ and _getClass()_ methods to _PersistenceUnitUtil_

Added overload of _entity()_ accepting an entity name to _Metamodel_

Added joins on __EntityType__s

Added constants for managed types, named queries, named graphs and named result set mappings to generated _StaticMetamodel_

Added _LocalDateTime_ and _Instant_ to supported _Version_ types

Added _where()_, _having()_, _and()_, and _or()_ overloads accepting _List<Predicate>_ to _CriteriaQuery_ and _CriteriaBuilder_

Added _equalTo()_ and _notEqualTo()_ to _Expression_

Added _concat()_ overload accepting list of expressions to _CriteriaBuilder_

Added _Graph_ interface as parent of _EntityGraph_ and _Subgraph_ and moved common operations there

Added _addAttributeNode()_, _removeAttributeNode()_, _addTreatedSubgraph()_, _addElementSubgraph()_, _addTreatedElementSubgraph()_,
_addMapKeySubgraph()_, and _addTreatedMapKeySubgraph()_ methods to _Graph_

Added _find()_, _refresh()_, _lock()_ overloads to _EntityManager_ taking newly introduced __FindOption__s, __RefreshOption__s,
and __LockOption__s respectively

Added _setCacheStoreMode()_, and _setCacheRetreiveMode()_ methods to _EntityManager_ and _Query_

Added _getReference_ overload to _EntityManager_

Added _runWithConnection()_ and _callWithConnection()_ to _EntityManager_

Added _runInTransaction()_ and _callInTransaction()_ to _EntityManagerFactory_

Added programmatic API to obtain _EntityManagerFactory_ using _PersistenceConfiguration_

Added constants for properties defined by the specification to the _PersistenceConfiguration_

Added _SchemaManager_ API

Added options member to elements which result in DDL generation

Added _EnumeratedValue_ allowing custom mapping of fields of Java enums

Added _comment_ and _check_ members to table and column annotations, along with _CheckConstraint_

Made the _name_ member of _TableGenerator_ and _SequenceGenerator_ optional

Clarified the primary key types supported for each _GenerationType_

Clarified availability of _SEQUENCE_, _TABLE_ and _UUID_ generated IDs on _PrePersist_

Clarified semantics of numeric literals and added support for `bi` and `bd` suffixes

Clarified rules around distinction of entity names and identification variables and case-sensitivity in JPQL queries

Clarified the semantics of __Bindable.ENTITY_TYPE__ in javadoc

Entity and embeddable classes may now be static inner classes

Primary key classes are no longer required to be public and serializable

Pulled _getParameters()_ up from _CriteriaQuery_ to _CommonAbstractCriteria_

Fixed wildcard types in _addSubgraph_ and _addAttributeNode_ in _Graph_

Fixed lower type bounds to the _Path.get_ entity argument _X_

Fixed example code in the javadoc of _AttributeOverrides_

Partially fixed raw types warnings through the API

Improved AsciiDoc formatting and fixed typos through the specification document

==== Deprecations

Deprecated usage of _Calendar_, _Date_, _Time_, _Timestamp_, _Temporal_, _MapKeyTemporal_ and _TemporalType_
in new applications in favour of _java.time_ API

==== Deprecations for removal

Deprecated _addSubclassSubgraph()_ in _EntityGraph_ for removal; _addTreatedSubgraph()_ method should be used as direct replacement

Deprecated _addSubgraph(Attribute, Class)_ and _addKeySubgraph()_ in _Graph_/_EntityGraph_/_SubGraph_ for removal; _addTreatedSubgraph(Attribute, Class)_
and _addMapKeySubgraph()_ methods should be used as direct replacements

Deprecated _jakarta.persistence.spi.PersistenceUnitTransactionType_ for removal; _jakarta.persistence.PersistenceUnitTransactionType_
methods should be used as direct replacement
