//
// Copyright (c) 2017, 2023 Contributors to the Eclipse Foundation
//

== Query Language [[a4665]]

The Jakarta Persistence Query Language is defined by the Jakarta Query
specification<<a19503>>.

[NOTE]
Jakarta Query is intended to be backward compatible with the query
language specified by previous versions of this specification, and
therefore older versions of this specification still provide useful
context for the interpretation and use of Jakarta Query in the
context of Jakarta Persistence.

In this chapter we specify how concepts introduced by the Jakarta
Query specification map to concepts defined by Jakarta Persistence.

=== Jakarta Persistence Query Language

Jakarta Query defines two levels of compliance: the _persistence
language_, and the _common language_. The common language is a
strict subset of the persistence language.

This specification requires support for the persistence language.

=== Dictionary of Basic Concepts

Jakarta Query defines a structural type system in terms of:

1. _atomic values_,
2. _collections_, and
3. _structures_ and _records_.

A structure type might be assigned a name, in which case it is
considered:

- an _embedded type_, unless it is a record, or
- an _entity type_, if it is a record.

Please refer to the Jakarta Query specification for the abstract
definitions of these concepts. Here we specify how these concepts
must be interpreted by an implementation of Jakarta Persistence:

- every entity class, as defined by <<a18>>, is treated as a
  Jakarta Query entity type,
- every embeddable class, as defined by <<a487>>, is treated as
  a Jakarta Query embedded type,
- every basic type, as defined in <<a486>>, is treated as an
  atomic type, and
- every collection mapped via `@OneToMany`, `@ManyToMany`, or
  `@ElementCollection` is treated as Jakarta Query collection.

According to Jakarta Query, a record is simply a structure with a
unique identifier. In Jakarta Persistence, this unique identifier
is understood to mean the primary key of the entity, as defined
in <<a132>>. Similarly, the notion of a _version_ is understood
to mean the entity version, as defined in <<a2060>>.

=== Inheritance and Polymorphism

Jakarta Query defines inheritance as a structural relationship
between entity types. In the context of Jakarta Persistence,
an inheritance relationship can only exist between entity types
belong to the same entity class hierarchy, as defined in
<<a966>>.

[WARNING]
That is, the implicit relationship between structural types defined
by Jakarta Query is reinterpreted here as a declared relationship
between nominal types.

Thus, polymorphic querying is limited to polymorphism over types
belonging to the same entity class hierarchy.

=== Databases and Records

Jakarta Query defines the word _database_ to mean a finite set of
records. Here we understand a database to encompass the relational
database tables holding state mapped to the entities belonging to a
given persistence unit. The records are the rows of these tables.

=== Naming [[naming]]

Every Jakarta Query entity type or embedded type has a name.

- This specification does not define the names of embeddable types.
  footnote:[In principle, the embeddable class name would work.]
- The name of an entity type is its _entity name_.

An entity name is specified by the `name` element of the `@Entity`
annotation, as defined later in <<entity-annotation>>, or by the
`<entity-name>` element of the XML descriptor, and--when not
explicitly specified--defaults to the unqualified name of the entity
class.footnote:[The unqualified name of a nested entity class
`org.example.Outer.Inner` is just `Inner`.]

Entity names are scoped to a persistence unit and must be unique
within the persistence unit. It is the responsibility of the
application programmer to ensure that entities belonging to the
same persistence unit have distinct entity names.

=== Fetch Joins

The Jakarta Query specification introduces the notion of a _fetch
join_, but assigns no semantics to it. An implementation of Jakarta
Persistence must treat the fetch join syntax as an instruction to
fetch specified associated data from the database eagerly, when the
query is executed, so that it is immediately _available_ to the
client, in the sense defined above in <<detached-lazy-state>>.

As implied by the syntax `join fetch`, implementations are strongly
encouraged to implement a fetch join as a join between relational
tables. However, this implementation strategy is not strictly
required by this specification.

=== Null

Jakarta Query leaves open the semantics of equality for null values.
This specification requires that the expressions `null = null` and
`null <> null` both evaluate to `null`. Furthermore, if `x` evaluates
to a non-null value, then both `x = null` and `x <> null` evaluate
to `null`.

=== Ternary Logic

This specification requires that conditional expressions evaluate
according to the rules of _ternary logic_. That is, with the special
exceptions of the `is null` and `is not null` operators, and of the
`coalasce()` function, when an expression involves a null value,
the expression evaluates to `null`.

Thus, in particular, a conditional or logical expression may take
one of three distinct values: `true`, `false`, and `null`. Jakarta
Query does not assign a value to a conditional or logical expression,
saying only that a conditional expression might be _satisfied_ or
_unsatisfied_. This specification requires that implementations
assign:

- the value `true` to a satisfied expression, and
- one of the values `null` or `false` to an unsatisfied expression,
  according to the rules given in the previous paragraph.

[CAUTION]
Note that according to these rules, the logical operator expression
`not null` evaluates to `null`, and so the `not` operator is not
always satisfied when its argument is unsatisfied.

=== Path Expressions

This specification requires support for compound path expressions
which involve attributes of multiple embeddable and entity types.

[IMPORTANT]
Jakarta Query treats path expressions as a sort of left outer join.
But for backward compatibility with older releases of the Jakarta
Persistence Query Language, an implementation is permitted to treat
a path expression as if it were a sort of inner join.

=== Query Parameters [[query-parameters]]

Jakarta Query defines a syntax for query parameters:

- A _named parameter_ is a legal Java identifier prefixed with the
  `:` character.
- An _ordinal parameter_ is a decimal integer prefixed with the `?`
  character.

Parameter names are considered case-sensitive.

Ordinal parameters are numbered sequentially, starting with  `?1`.

[NOTE]
Terminology Note: Elsewhere In this specification, ordinal parameters
are called _positional parameters_.

Arguments are assigned to query parameters via the `setParameter()`
methods of the `Query` interface, as specified in <<a4397>>.

=== Type Casts

Jakarta Query defines a `cast()` function which converts an expression
of one type to an expression of a different type.

The persistence provider is required to accept type casts of the
following forms:

- any scalar expression to `STRING`;
- any string expression to `INTEGER`, `LONG`, `FLOAT`, or `DOUBLE`.

Typecast expressions are evaluated by the database, with semantics
that vary somewhat between different databases. Portable applications
should avoid depending on the specific format of a cast to `STRING`.

When a type cast occurs as a select expression, the result type of
the select expression is:

- `java.lang.String` for a cast to `STRING`;
- `java.lang.Integer`, `java.lang.Long`, `java.lang.Float`, or
  `java.lang.Double` for a cast to `INTEGER`, `LONG`, `FLOAT`,
  or `DOUBLE`, respectively.

=== Datetime Special Values and Functions [[a5304]]

For backward compatibility, this specification requires support for the
special values `current_date`, `current_time`, and `current_timestamp`,
which are not defined by Jakarta Query, evaluating to the current date,
time, or timestamp on the database server, respectively. Their types are
`java.sql.Date`, `java.sql.Time`, and `java.sql.Timestamp` respectively.

This specification requires that the implementation of the `extract()`
function accept a datetime argument and one of the following field type
identifiers: `YEAR`, `QUARTER`, `MONTH`, `WEEK`, `DAY`, `HOUR`, `MINUTE`,
`SECOND`, `DATE`, `TIME`.

`extract()` returns the value of the corresponding field or part of the
datetime. It is illegal to pass a datetime argument which does not have
the given field type to `EXTRACT`.

For the following field type identifiers, `extract()` returns an integer
value:

- `YEAR` means the calendar year.
- `QUARTER` means the calendar quarter, numbered from 1 to 4.
- `MONTH` means the calendar month of the year, numbered from 1.
- `WEEK` means the ISO-8601 week number.
- `DAY` means the calendar day of the month, numbered from 1.
- `HOUR` means the hour of the day in 24-hour time, numbered from 0 to 23.
- `MINUTE` means the minute of the hour, numbered from 0 to 59.

For the `SECOND` field type identifier, `EXTRACT` returns a floating point
value:

- `SECOND` means the second of the minute, numbered from 0 to 59, including
  a fractional part representing fractions of a second.

For the following field type identifiers, `EXTRACT` returns a part of the
datetime value:

- `DATE` means the date part of a datetime.
- `TIME` means the time part of a datetime.

It is illegal to pass a datetime argument which does not have the given
part to `EXTRACT`.

[source,sql]
----
FROM Course c WHERE c.year = EXTRACT(YEAR FROM LOCAL DATE)
----

=== Database Functions

For backward compatibility, this specification requires support for
the `function()` function, allowing invocation of arbitrary database
functions, including built-in functions and user-defined functions.

However, implementations are now strongly encouraged to simply allow
direct invocation of database functions without requiring the extra
ceremony of `function()`.

=== Constructor Application

This specification requires support for explicit constructor application
in the `SELECT` clause.