//
// Copyright (c) 2017, 2020 Contributors to the Eclipse Foundation
//

== Metamodel API [[a6072]]

This specification provides a set of interfaces for dynamically accessing
a metamodel representing the managed classes of a persistence unit.
Instances of metamodel types may be obtained either:

- via programmatic lookup using an instance of the interface
  `jakarta.persistence.metamodel.Metamodel` obtained from the
  `EntityManagerFactory` or `EntityManager` by calling
  `getMetamodel()`, or
- in a typesafe way, using _static metamodel classes_.

A static metamodel class is a class with static members providing direct
typesafe access to metamodel objects representing the persistent members
of a given managed class.

=== Static Metamodel Classes [[a6933]]

A set of static metamodel classes corresponding to the managed classes of
a persistence unit can be generated using an annotation processor or may
be created by the application developer.

In the typical case, an annotation processor is used to generate static
metamodel classes corresponding to the entities, mapped superclasses,
and embeddable classes in the persistence unit. A static metamodel class
models the persistent state and relationships of the corresponding managed
class. For portability, an annotation processor should generate a _canonical
metamodel_ as specified in the next section.

==== Canonical Metamodel

This specification defines as follows a
canonical metamodel and the structure of canonical metamodel classes.

For every managed class in the persistence
unit, a corresponding metamodel class is produced as follows:

* For each managed class `X` in package `p`, a metamodel class
`X_` in package `p` is created.footnote:[We expect that the
option of different packages will be provided in a future release of
this specification.]

* The name of the metamodel class is derived from the name of the
managed class by appending "`_`" to the name of the managed class.

* The metamodel class `X_` must be annotated with the
`jakarta.persistence.StaticMetamodel` annotationfootnote:[If the class
was generated, the `javax.annotation.processing.Generated` or `jakarta.annotation.Generated`
annotation should be used to annotate the class. The use of any other annotations on static
metamodel classes is undefined.].

* If the managed class `X` extends another class `S`, where `S` is the
most derived managed class (i.e., entity or mapped superclass) extended
by `X`, then the metamodel class `X_` must extend the metamodel
class `S_` created for `S`.

* The metamodel class must contain a field declaration as follows:
+
[source,java]
----
public static volatile jakarta.persistence.metamodel.T<X> class_;
----
+
where `T` is `EntityType`, `EmbeddableType`, or `MappedSuperclassType`
depending on whether `X` is an entity, embeddable, or mapped superclass.
* For every persistent attribute `y` declared by class `X`, the
metamodel class must contain a field declaration as follows:
+
[source,java]
----
public static final String Y = "y";
----
+
where the field name `Y` is obtained by transforming each lowercase
character in the attribute name `y` to uppercase, and inserting an
underscore if the character following the transformed character
is uppercase.

* For every persistent non-collection-valued
attribute `y` declared by class `X`, where the type of `y` is `Y`, the
metamodel class must contain a declaration as follows:
+
[source,java]
----
public static volatile SingularAttribute<X, Y> y;
----
+

* For every persistent collection-valued
attribute `z` declared by class `X`, where the element type of `z` is
`Z`, the metamodel class must contain a declaration as follows:
** if the collection type of `z` is `java.util.Collection`, then
+
[source,java]
----
public static volatile CollectionAttribute<X, Z> z;
----
+
** if the collection type of `z` is `java.util.Set`, then
+
[source,java]
----
public static volatile SetAttribute<X, Z> z;
----
+
** if the collection type of `z` is `java.util.List`, then
+
[source,java]
----
public static volatile ListAttribute<X, Z> z;
----
+
** if the collection type of `z` is `java.util.Map`, then
+
[source,java]
----
public static volatile MapAttribute<X, K, Z> z;
----
+
where `K` is the type of the key of the map in class `X`

* For every named query, named entity graph, or SQL result set
mapping with name `"n"` declared by annotations of the class `X`,
the metamodel class must contain a declaration as follows:
+
[source,java]
----
public static final String T_N = "n";
----
+
where The prefix `T` is the string `QUERY`, `GRAPH`, or `MAPPING`,
as appropriate, depending on the annotation type, and the suffix
`N` is obtained by transforming each lowercase character in the
name `n` to uppercase, inserting an underscore if the character
following the transformed character is uppercase, and then
replacing each character which is not a legal Java identifier
character with an underscore.

* For every named query with name `"n"` and query result class
`R` declared by annotations of the class `X`, the metamodel class
must contain a declaration as follows:
+
[source,java]
----
public static volatile TypedQueryReference<R> _n_;
----
+

* For every named entity graph with name `"n"` declared by
annotations of the class `X`, the metamodel class must contain
a declaration as follows:
+
[source,java]
----
public static volatile EntityGraph<X> _n;
----
+

Import statements must be included for the
needed `jakarta.persistence.metamodel` types as appropriate (e.g.,
`jakarta.persistence.metamodel.SingularAttribute`,
`jakarta.persistence.metamodel.CollectionAttribute`,
`jakarta.persistence.metamodel.SetAttribute`,
`jakarta.persistence.metamodel.ListAttribute`,
`jakarta.persistence.metamodel.MapAttribute`) and all classes `X`, `Y`,
`Z`, `R`, and `K`.

[NOTE]
====
Implementations of this specification are
not required to support the use of non-canonical metamodel classes.
Applications that use non-canonical metamodel classes will not be
portable.
====

===== Example Canonical Metamodel [[a6961]]

Assume the `Order` entity below.

[source,java]
----
package com.example;

import java.util.Set;
import java.math.BigDecimal;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;


@Entity
public class Order {
    @Id
    Integer orderId;

    @ManyToOne
    Customer customer;

    @OneToMany
    Set<Item> lineItems;

    Address shippingAddress;

    BigDecimal totalCost;

    // ...
}
----

The corresponding canonical metamodel class, `Order_`, is as follows:

[source,java]
----
package com.example;

import java.math.BigDecimal;
import jakarta.persistence.metamodel.SingularAttribute;
import jakarta.persistence.metamodel.SetAttribute;
import jakarta.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Order.class)
public class Order_ {
	public static volatile EntityType<Order> class_;

    public static volatile SingularAttribute<Order, Integer> orderId;
    public static volatile SingularAttribute<Order, Customer> customer;
    public static volatile SetAttribute<Order, Item> lineItems;
    public static volatile SingularAttribute<Order, Address> shippingAddress;
    public static volatile SingularAttribute<Order, BigDecimal> totalCost;

	public static final String LINE_ITEMS = "lineItems";
	public static final String ORDER_ID = "orderId";
	public static final String SHIPPING_ADDRESS = "shippingAddress";
	public static final String TOTAL_COST = "totalCost";
	public static final String CUSTOMER = "customer";
}
----

==== Bootstrapping the Static Metamodel

When the entity manager factory for a persistence unit is created, it is
the responsibility of the persistence provider to initialize the state of
the static metamodel classes representing managed classes belonging to the
persistence unit. Any generated metamodel classes must be accessible on the
classpath.

Persistence providers must support the use of canonical metamodel classes.
Persistence providers may, but are not required to, support the use of
non-canonical metamodel classes.


=== Metamodel API Interfaces

The `jakarta.persistence.metamodel` interfaces
provide for dynamically accessing the metamodel of the persistent
state and relationships of the managed classes of a persistence unit.

The metamodel can be accessed through the
`EntityManagerFactory` or `EntityManager.getMetamodel` methods.

The metamodel API may be extended to cover
object/relational mapping information in a future release of this
specification.


==== Metamodel Interface

[source,java]
----
package jakarta.persistence.metamodel;

import java.util.Set;

/**
 * Provides access to the metamodel of persistent
 * entities in the persistence unit.
 *
 * @since 2.0
 */
public interface Metamodel {

    /**
     *  Return the metamodel entity type representing the entity.
     *  @param entityName  the name of the represented entity
     *  @return the metamodel entity type
     *  @throws IllegalArgumentException if not an entity
     *  @see jakarta.persistence.Entity#name
     *  @since 3.2
     */
    EntityType<?> entity(String entityName);

    /**
     *  Return the metamodel entity type representing the entity.
     *  @param cls  the type of the represented entity
     *  @return the metamodel entity type
     *  @throws IllegalArgumentException if not an entity
     */
    <X> EntityType<X> entity(Class<X> cls);

    /**
     *  Return the metamodel managed type representing the
     *  entity, mapped superclass, or embeddable class.
     *  @param cls  the type of the represented managed class
     *  @return the metamodel managed type
     *  @throws IllegalArgumentException if not a managed class
     */
    <X> ManagedType<X> managedType(Class<X> cls);

    /**
     *  Return the metamodel embeddable type representing the
     *  embeddable class.
     *  @param cls  the type of the represented embeddable class
     *  @return the metamodel embeddable type
     *  @throws IllegalArgumentException if not an embeddable class
     */
    <X> EmbeddableType<X> embeddable(Class<X> cls);

    /**
     *  Return the metamodel managed types.
     *  @return the metamodel managed types
     */
    Set<ManagedType<?>> getManagedTypes();

    /**
     * Return the metamodel entity types.
     * @return the metamodel entity types
     */
    Set<EntityType<?>> getEntities();

    /**
     * Return the metamodel embeddable types.  Returns empty set
     * if there are no embeddable types.
     * @return the metamodel embeddable types
     */
    Set<EmbeddableType<?>> getEmbeddables();
}
----

==== Type Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Instances of the type <code>Type</code> represent persistent object
 * or attribute types.
 *
 * @param <X>  The type of the represented object or attribute
 *
 * @since 2.0
 */
public interface Type<X> {

       public static enum PersistenceType {

       /** Entity */
           ENTITY,

       /** Embeddable class */
       EMBEDDABLE,

       /** Mapped superclass */
       MAPPED_SUPERCLASS,

       /** Basic type */
       BASIC
       }

    /**
     *  Return the persistence type.
     *  @return persistence type
     */
    PersistenceType getPersistenceType();

    /**
     *  Return the represented Java type.
     *  @return Java type
     */
    Class<X> getJavaType();
}
----

==== ManagedType Interface

[source,java]
----
package jakarta.persistence.metamodel;

import java.util.Set;

/**
 *  Instances of the type <code>ManagedType</code> represent entity, mapped
 *  superclass, and embeddable types.
 *
 *  @param <X> The represented type.
 *
 *  @since 2.0
 *
 */
public interface ManagedType<X> extends Type<X> {

    /**
     *  Return the attributes of the managed type.
     *  @return attributes of the managed type
     */
     Set<Attribute<? super X, ?>> getAttributes();

    /**
     *  Return the attributes declared by the managed type.
     *  Returns empty set if the managed type has no declared
     *  attributes.
     *  @return declared attributes of the managed type
     */
     Set<Attribute<X, ?>> getDeclaredAttributes();

    /**
     *  Return the single-valued attribute of the managed
     *  type that corresponds to the specified name and Java type.
     *  @param name  the name of the represented attribute
     *  @param type  the type of the represented attribute
     *  @return single-valued attribute with given name and type
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not present in the managed type
     */
    <Y> SingularAttribute<? super X, Y> getSingularAttribute(String name, Class<Y> type);

    /**
     *  Return the single-valued attribute declared by the
     *  managed type that corresponds to the specified name and
     *  Java type.
     *  @param name  the name of the represented attribute
     *  @param type  the type of the represented attribute
     *  @return declared single-valued attribute of the given
     *          name and type
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not declared in the managed type
     */
    <Y> SingularAttribute<X, Y> getDeclaredSingularAttribute(String name, Class<Y> type);

    /**
     *  Return the single-valued attributes of the managed type.
     *  Returns empty set if the managed type has no single-valued
     *  attributes.
     *  @return single-valued attributes
     */
    Set<SingularAttribute<? super X, ?>> getSingularAttributes();

    /**
     *  Return the single-valued attributes declared by the managed
     *  type.
     *  Returns empty set if the managed type has no declared
     *  single-valued attributes.
     *  @return declared single-valued attributes
     */
    Set<SingularAttribute<X, ?>> getDeclaredSingularAttributes();

    /**
     *  Return the Collection-valued attribute of the managed type
     *  that corresponds to the specified name and Java element type.
     *  @param name  the name of the represented attribute
     *  @param elementType  the element type of the represented
     *                      attribute
     *  @return CollectionAttribute of the given name and element
     *          type
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not present in the managed type
     */
    <E> CollectionAttribute<? super X, E> getCollection(String name, Class<E> elementType);

    /**
     *  Return the Collection-valued attribute declared by the
     *  managed type that corresponds to the specified name and Java
     *  element type.
     *  @param name  the name of the represented attribute
     *  @param elementType  the element type of the represented
     *                      attribute
     *  @return declared <code>CollectionAttribute</code> of the given name and
     *          element type
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not declared in the managed type
     */
    <E> CollectionAttribute<X, E> getDeclaredCollection(String name, Class<E> elementType);

    /**
     *  Return the Set-valued attribute of the managed type that
     *  corresponds to the specified name and Java element type.
     *  @param name  the name of the represented attribute
     *  @param elementType  the element type of the represented
     *                      attribute
     *  @return SetAttribute of the given name and element type
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not present in the managed type
     */
    <E> SetAttribute<? super X, E> getSet(String name, Class<E> elementType);

    /**
     *  Return the Set-valued attribute declared by the managed type
     *  that corresponds to the specified name and Java element type.
     *  @param name  the name of the represented attribute
     *  @param elementType  the element type of the represented
     *                      attribute
     *  @return declared SetAttribute of the given name and
     *          element type
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not declared in the managed type
     */
    <E> SetAttribute<X, E> getDeclaredSet(String name, Class<E> elementType);

    /**
     *  Return the List-valued attribute of the managed type that
     *  corresponds to the specified name and Java element type.
     *  @param name  the name of the represented attribute
     *  @param elementType  the element type of the represented
     *                      attribute
     *  @return ListAttribute of the given name and element type
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not present in the managed type
     */
    <E> ListAttribute<? super X, E> getList(String name, Class<E> elementType);

    /**
     *  Return the List-valued attribute declared by the managed
     *  type that corresponds to the specified name and Java
     *  element type.
     *  @param name  the name of the represented attribute
     *  @param elementType  the element type of the represented
     *                      attribute
     *  @return declared ListAttribute of the given name and
     *          element type
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not declared in the managed type
     */
    <E> ListAttribute<X, E> getDeclaredList(String name, Class<E> elementType);

    /**
     *  Return the Map-valued attribute of the managed type that
     *  corresponds to the specified name and Java key and value
     *  types.
     *  @param name  the name of the represented attribute
     *  @param keyType  the key type of the represented attribute
     *  @param valueType  the value type of the represented attribute
     *  @return MapAttribute of the given name and key and value
     *  types
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not present in the managed type
     */
    <K, V> MapAttribute<? super X, K, V> getMap(String name,
                                                Class<K> keyType,
                                                Class<V> valueType);

    /**
     *  Return the Map-valued attribute declared by the managed
     *  type that corresponds to the specified name and Java key
     *  and value types.
     *  @param name  the name of the represented attribute
     *  @param keyType  the key type of the represented attribute
     *  @param valueType  the value type of the represented attribute
     *  @return declared MapAttribute of the given name and key
     *          and value types
     *  @throws IllegalArgumentException if attribute of the given
     *          name and type is not declared in the managed type
     */
    <K, V> MapAttribute<X, K, V> getDeclaredMap(String name,
                                                Class<K> keyType,
                                                Class<V> valueType);

    /**
     *  Return all multi-valued attributes (Collection-, Set-,
     *  List-, and Map-valued attributes) of the managed type.
     *  Returns empty set if the managed type has no multi-valued
     *  attributes.
     *  @return Collection-, Set-, List-, and Map-valued attributes
     */
    Set<PluralAttribute<? super X, ?, ?>> getPluralAttributes();

    /**
     *  Return all multi-valued attributes (Collection-, Set-,
     *  List-, and Map-valued attributes) declared by the
     *  managed type.
     *  Returns empty set if the managed type has no declared
     *  multi-valued attributes.
     *  @return declared Collection-, Set-, List-, and Map-valued
     *          attributes
     */
    Set<PluralAttribute<X, ?, ?>> getDeclaredPluralAttributes();


//String-based:

    /**
     *  Return the attribute of the managed
     *  type that corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return attribute with given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not present in the managed type
     */
    Attribute<? super X, ?> getAttribute(String name);

    /**
     *  Return the attribute declared by the managed
     *  type that corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return attribute with given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not declared in the managed type
     */
    Attribute<X, ?> getDeclaredAttribute(String name);

    /**
     *  Return the single-valued attribute of the managed type that
     *  corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return single-valued attribute with the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not present in the managed type
     */
    SingularAttribute<? super X, ?> getSingularAttribute(String name);

    /**
     *  Return the single-valued attribute declared by the managed
     *  type that corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return declared single-valued attribute of the given
     *          name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not declared in the managed type
     */
    SingularAttribute<X, ?> getDeclaredSingularAttribute(String name);

    /**
     *  Return the Collection-valued attribute of the managed type
     *  that corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return CollectionAttribute of the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not present in the managed type
     */
    CollectionAttribute<? super X, ?> getCollection(String name);

    /**
     *  Return the Collection-valued attribute declared by the
     *  managed type that corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return declared CollectionAttribute of the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not declared in the managed type
     */
    CollectionAttribute<X, ?> getDeclaredCollection(String name);

    /**
     *  Return the Set-valued attribute of the managed type that
     *  corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return SetAttribute of the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not present in the managed type
     */
    SetAttribute<? super X, ?> getSet(String name);

    /**
     *  Return the Set-valued attribute declared by the managed type
     *  that corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return declared SetAttribute of the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not declared in the managed type
     */
    SetAttribute<X, ?> getDeclaredSet(String name);

    /**
     *  Return the List-valued attribute of the managed type that
     *  corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return ListAttribute of the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not present in the managed type
     */
    ListAttribute<? super X, ?> getList(String name);

    /**
     *  Return the List-valued attribute declared by the managed
     *  type that corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return declared ListAttribute of the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not declared in the managed type
     */
    ListAttribute<X, ?> getDeclaredList(String name);

    /**
     *  Return the Map-valued attribute of the managed type that
     *  corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return MapAttribute of the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not present in the managed type
     */
    MapAttribute<? super X, ?, ?> getMap(String name);

    /**
     *  Return the Map-valued attribute declared by the managed
     *  type that corresponds to the specified name.
     *  @param name  the name of the represented attribute
     *  @return declared MapAttribute of the given name
     *  @throws IllegalArgumentException if attribute of the given
     *          name is not declared in the managed type
     */
    MapAttribute<X, ?, ?> getDeclaredMap(String name);
}
----

==== IdentifiableType Interface

[source,java]
----
package jakarta.persistence.metamodel;

import java.util.Set;

/**
 *  Instances of the type <code>IdentifiableType</code> represent entity or
 *  mapped superclass types.
 *
 *  @param <X> The represented entity or mapped superclass type.
 *
 *  @since 2.0
 *
 */
public interface IdentifiableType<X> extends ManagedType<X> {

    /**
     *  Return the attribute that corresponds to the id attribute of
     *  the entity or mapped superclass.
     *  @param type  the type of the represented id attribute
     *  @return id attribute
     *  @throws IllegalArgumentException if id attribute of the given
     *          type is not present in the identifiable type or if
     *          the identifiable type has an id class
     */
    <Y> SingularAttribute<? super X, Y> getId(Class<Y> type);

    /**
     *  Return the attribute that corresponds to the id attribute
     *  declared by the entity or mapped superclass.
     *  @param type  the type of the represented declared
     *               id attribute
     *  @return declared id attribute
     *  @throws IllegalArgumentException if id attribute of the given
     *          type is not declared in the identifiable type or if
     *          the identifiable type has an id class
     */
    <Y> SingularAttribute<X, Y> getDeclaredId(Class<Y> type);

    /**
     *  Return the attribute that corresponds to the version
     *  attribute of the entity or mapped superclass.
     *  @param type  the type of the represented version attribute
     *  @return version attribute
     *  @throws IllegalArgumentException if version attribute of the
     *          given type is not present in the identifiable type
     */
    <Y> SingularAttribute<? super X, Y> getVersion(Class<Y> type);

    /**
     *  Return the attribute that corresponds to the version
     *  attribute declared by the entity or mapped superclass.
     *  @param type  the type of the represented declared version
     *               attribute
     *  @return declared version attribute
     *  @throws IllegalArgumentException if version attribute of the
     *          type is not declared in the identifiable type
     */
    <Y> SingularAttribute<X, Y> getDeclaredVersion(Class<Y> type);

    /**
     *  Return the identifiable type that corresponds to the most
     *  specific mapped superclass or entity extended by the entity
     *  or mapped superclass.
     *  @return supertype of identifiable type or null if no
     *          such supertype
     */
    IdentifiableType<? super X> getSupertype();

    /**
     *  Whether the identifiable type has a single id attribute.
     *  Returns true for a simple id or embedded id; returns false
     *  for an idclass.
     *  @return boolean indicating whether the identifiable
     *          type has a single id attribute
     */
    boolean hasSingleIdAttribute();

    /**
     *  Whether the identifiable type has a version attribute.
     *  @return boolean indicating whether the identifiable
     *          type has a version attribute
     */
    boolean hasVersionAttribute();

    /**
     *   Return the attributes corresponding to the id class of the
     *   identifiable type.
     *   @return id attributes
     *   @throws IllegalArgumentException if the identifiable type
     *           does not have an id class
     */
     Set<SingularAttribute<? super X, ?>> getIdClassAttributes();

    /**
     *  Return the type that represents the type of the id.
     *  @return type of id
     */
    Type<?> getIdType();
}
----

==== EntityType Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 *  Instances of the type <code>EntityType</code> represent entity types.
 *
 *  @param <X> The represented entity type.
 *
 * @since 2.0
 *
 */
public interface EntityType<X>
            extends IdentifiableType<X>, Bindable<X>{

    /**
     *  Return the entity name.
     *  @return entity name
     */
    String getName();
}
----

==== EmbeddableType Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 *  Instances of the type <code>EmbeddableType</code> represent embeddable types.
 *
 *  @param <X> The represented type.
 *
 *  @since 2.0
 *
 */
public interface EmbeddableType<X> extends ManagedType<X> {}
----

==== MappedSuperclassType Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 *  Instances of the type <code>MappedSuperclassType</code> represent mapped
 *  superclass types.
 *
 *  @param <X> The represented entity type
 *  @since 2.0
 */
public interface MappedSuperclassType<X> extends IdentifiableType<X> {}
----

==== BasicType Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Instances of the type <code>BasicType</code> represent basic types (including
 * temporal and enumerated types).
 *
 * @param <X> The type of the represented basic type
 *
 * @since 2.0
 */
public interface BasicType<X> extends Type<X> {}
----

==== Bindable Interface

[source,java]
----
package jakarta.persistence.metamodel;

import jakarta.persistence.criteria.Path;

/**
 * Instances of the type <code>Bindable</code> represent object or attribute types
 * that can be bound into a {@link Path Path}.
 *
 * @param <T>  The type of the represented object or attribute
 *
 * @since 2.0
 *
 */
public interface Bindable<T> {

    public static enum BindableType {
        /**
         * Single-valued attribute type.
         *
         * @see SingularAttribute
         */
        SINGULAR_ATTRIBUTE,

        /**
         * Multivalued attribute type, that is, a collection.
         *
         * @see PluralAttribute
         */
        PLURAL_ATTRIBUTE,

        /**
         * Entity type.
         *
         * @see EntityType
         */
        ENTITY_TYPE
    }

    /**
     *  Return the bindable type of the represented object.
     *  @return bindable type
     */
    BindableType getBindableType();

    /**
     * Return the Java type of the represented object.
     * If the bindable type of the object is <code>PLURAL_ATTRIBUTE</code>,
     * the Java element type is returned. If the bindable type is
     * <code>SINGULAR_ATTRIBUTE</code> or <code>ENTITY_TYPE</code>,
     * the Java type of the
     * represented entity or attribute is returned.
     * @return Java type
     */
    Class<T> getBindableJavaType();
}
----

==== Attribute Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Represents an attribute of a Java type.
 *
 * @param <X> The represented type that contains the attribute
 * @param <Y> The type of the represented attribute
 *
 * @since 2.0
 */
public interface Attribute<X, Y> {

    public static enum PersistentAttributeType {

         /** Many-to-one association */
         MANY_TO_ONE,

         /** One-to-one association */
         ONE_TO_ONE,

         /** Basic attribute */
         BASIC,

         /** Embeddable class attribute */
         EMBEDDED,

         /** Many-to-many association */
         MANY_TO_MANY,

         /** One-to-many association */
         ONE_TO_MANY,

         /** Element collection */
         ELEMENT_COLLECTION
    }

    /**
     * Return the name of the attribute.
     * @return name
     */
    String getName();

    /**
     *  Return the persistent attribute type for the attribute.
     *  @return persistent attribute type
     */
    PersistentAttributeType getPersistentAttributeType();

    /**
     *  Return the managed type representing the type in which
     *  the attribute was declared.
     *  @return declaring type
     */
    ManagedType<X> getDeclaringType();

    /**
     *  Return the Java type of the represented attribute.
     *  @return Java type
     */
    Class<Y> getJavaType();

    /**
     *  Return the <code>java.lang.reflect.Member</code> for the represented
     *  attribute.
     *  @return corresponding <code>java.lang.reflect.Member</code>
     */
    java.lang.reflect.Member getJavaMember();

    /**
     *  Is the attribute an association.
     *  @return boolean indicating whether the attribute
     *          corresponds to an association
     */
    boolean isAssociation();

    /**
     *  Is the attribute collection-valued (represents a Collection,
     *  Set, List, or Map).
     *  @return boolean indicating whether the attribute is
     *          collection-valued
     */
    boolean isCollection();
}
----

==== SingularAttribute Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Instances of the type <code>SingularAttribute</code> represents persistent
 * single-valued properties or fields.
 *
 * @param <X> The type containing the represented attribute
 * @param <T> The type of the represented attribute
 *
 * @since 2.0
 */
public interface SingularAttribute<X, T>
        extends Attribute<X, T>, Bindable<T> {

    /**
     *  Is the attribute an id attribute.  This method will return
     *  true if the attribute is an attribute that corresponds to
     *  a simple id, an embedded id, or an attribute of an id class.
     *  @return boolean indicating whether the attribute is an id
     */
    boolean isId();

    /**
     *  Is the attribute a version attribute.
     *  @return boolean indicating whether the attribute is
     *          a version attribute
     */
    boolean isVersion();

    /**
     *  Can the attribute be null.
     *  @return boolean indicating whether the attribute can
     *          be null
     */
    boolean isOptional();

    /**
     * Return the type that represents the type of the attribute.
     * @return type of attribute
     */
    Type<T> getType();
}
----

==== PluralAttribute Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Instances of the type <code>PluralAttribute</code> represent
 * persistent collection-valued attributes.
 *
 * @param <X> The type the represented collection belongs to
 * @param <C> The type of the represented collection
 * @param <E> The element type of the represented collection
 *
 * @since 2.0
 */
public interface PluralAttribute<X, C, E>
        extends Attribute<X, C>, Bindable<E> {

    public static enum CollectionType {

        /** Collection-valued attribute */
        COLLECTION,

        /** Set-valued attribute */
        SET,

        /** List-valued attribute */
        LIST,

        /** Map-valued attribute */
        MAP
    }

    /**
     * Return the collection type.
     * @return collection type
     */
    CollectionType getCollectionType();

    /**
     * Return the type representing the element type of the
     * collection.
     * @return element type
     */
    Type<E> getElementType();
}
----

==== CollectionAttribute Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Instances of the type <code>CollectionAttribute</code> represent persistent
 * <code>java.util.Collection</code>-valued attributes.
 *
 * @param <X> The type the represented Collection belongs to
 * @param <E> The element type of the represented Collection
 *
 * @since 2.0
 *
 */
public interface CollectionAttribute<X, E>
    extends PluralAttribute<X, java.util.Collection<E>, E> {}
----

==== SetAttribute Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Instances of the type <code>SetAttribute</code> represent
 * persistent <code>java.util.Set</code>-valued attributes.
 *
 * @param <X> The type the represented Set belongs to
 * @param <E> The element type of the represented Set
 *
 * @since 2.0
 */
public interface SetAttribute<X, E>
    extends PluralAttribute<X, java.util.Set<E>, E> {}
----

==== ListAttribute Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Instances of the type <code>ListAttribute</code> represent persistent
 * <code>java.util.List</code>-valued attributes.
 *
 * @param <X> The type the represented List belongs to
 * @param <E> The element type of the represented List
 *
 * @since 2.0
 *
 */
public interface ListAttribute<X, E>
        extends PluralAttribute<X, java.util.List<E>, E> {}
----

==== MapAttribute Interface

[source,java]
----
package jakarta.persistence.metamodel;

/**
 * Instances of the type <code>MapAttribute</code> represent
 * persistent <code>java.util.Map</code>-valued attributes.
 *
 * @param <X> The type the represented Map belongs to
 * @param <K> The type of the key of the represented Map
 * @param <V> The type of the value of the represented Map
 *
 * @since 2.0
 *
 */
public interface MapAttribute<X, K, V>
    extends PluralAttribute<X, java.util.Map<K, V>, V> {

    /**
     * Return the Java type of the map key.
     * @return Java key type
     */
    Class<K> getKeyJavaType();

    /**
     * Return the type representing the key type of the map.
     * @return type representing key type
     */
    Type<K> getKeyType();
}
----

==== StaticMetamodel Annotation

[source,java]
----
package jakarta.persistence.metamodel;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The <code>StaticMetamodel</code> annotation specifies that the class
 * is a metamodel class that represents the entity, mapped
 * superclass, or embeddable class designated by the value
 * element.
 *
 * @since 2.0
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface StaticMetamodel {

    /**
     * Class being modelled by the annotated class.
     */
    Class<?> value();
}
----