//
// Copyright (c) 2017, 2024 Contributors to the Eclipse Foundation
//

== Entity Packaging [[a12229]]

This chapter describes the packaging of persistence units.

=== Persistence Unit [[a12235]]

A persistence unit is a logical grouping that includes:

- an entity manager factory and its entity managers, together with
  their configuration information,
- the set of managed classes included in the persistence unit and
  managed by entity managers created by the entity manager factory,
  and
- mapping metadata (in the form of metadata annotations and/or XML
  metadata) specifying the mapping of these classes to the database.

=== Persistence Unit Packaging [[a12236]]

Within Jakarta EE environments, any EJB-JAR, WAR, EAR, or application
client JAR can define a persistence unit. Any number of persistence
units may be defined within these scopes.

A persistence unit may be packaged:

- within one or more jar files contained within a WAR or EAR,
- as a set of classes within an EJB-JAR file or in the WAR `classes`
  directory, or
- as a combination of these, as defined below.

A persistence unit is defined by a `persistence.xml` file. The jar file
or directory whose `META-INF` directory contains the `persistence.xml`
file is termed the `root` of the persistence unit. In Jakarta EE
environments, the root of a persistence unit must be either:

- an EJB-JAR file,
- the `WEB-INF/classes` directory of a WAR filefootnote:[The root of
  the persistence unit is the `WEB-INF/classes` directory;
  the `persistence.xml` file is therefore contained in the
  `WEB-INF/classes/META-INF` directory.],
- a jar file in the `WEB-INF/lib` directory of a WAR file,
- a jar file in the library directory or an EAR, or
- an application client JAR file.

It is not required that an EJB-JAR or WAR file containing a persistence
unit be packaged in an EAR unless the persistence unit contains extra
persistence classes in addition to those contained within the EJB-JAR or
WAR. See <<a12305>>.

[NOTE]
====
Java Persistence 1.0 supported the use of a jar file in the root of the
EAR as the root of a persistence unit. This use is no longer supported.
Portable applications should use the EAR library directory for this case
instead. See <<a19499>>.
====

A persistence unit must have a name. The name of the persistence unit must
be unique within a given EJB-JAR file, within a given WAR file, within a
given application client JAR, or within an EAR. See <<a12459>>.

The `persistence.xml` file may be used to define more than one persistence
unit within the same scope.

All persistence classes defined at the level of the Jakarta EE EAR must be
accessible to other Jakarta EE components in the application—that is, to
all components loaded by the application classloader—such that if the same
entity class is referenced by two different Jakarta EE components (which
may be using different persistence units), the referenced class is the same
identical class.

In Java SE environments, the metadata mapping files, jar files, and classes
described in the following sections can be used. To insure the portability
of a Java SE application, it is necessary to explicitly list the managed
persistence classes included in the persistence unit using the `class`
element of the `persistence.xml` file. See <<a12305>>.

==== persistence.xml file [[a12237]]

A `persistence.xml` file defines a persistence unit. The `persistence.xml`
file is located in the `META-INF` directory of the root of the persistence
unit. It may be used to specify:

- managed persistence classes included in the persistence unit,
- object/relational mapping information for those classes,
- scripts for use in schema generation and bulk loading of data, and
- other configuration information for the persistence unit and for the
  entity managers and entity manager factory of the persistence unit.

This information may be defined by containment or by reference, as described
below.

The object/relational mapping information can take the form of:

- annotations on the managed persistence classes included in the persistence
  unit,
- an `orm.xml` file contained in the `META-INF` directory of the root of the
  persistence unit,
- one or more XML files accessible on the classpath and referenced from the
  `persistence.xml` file, or
- any combination of the previous options.

The managed persistence classes may be:

- contained within the root of the persistence unit,
- specified by reference—that is, by naming the classes, class archives, or
  XML mapping files (which in turn reference classes) that are accessible on
  the application classpath, or
- specified by any combination of these means.

See <<a12305>>.

The root element of the `persistence.xml` file is the `persistence` element.
The `persistence` element consists of one or more `persistence-unit` elements.

The `persistence-unit` element consists of the `name` and `transaction-type`
attributes and the following sub-elements:
`description`, `provider`,
`jta-data-source`, `non-jta-data-source`,
`mapping-file`, `jar-file`, `class`,
`exclude-unlisted-classes`,
`shared-cache-mode`, `validation-mode`,
and `properties`.

The `name` attribute is required; the other attributes and elements are optional.
Their semantics are described in the following subsections.

Examples:

[source,xml]
----
<persistence>
    <persistence-unit name="OrderManagement">
        <description>
            This unit manages orders and customers.
            It does not rely on any vendor-specific features and can
            therefore be deployed to any persistence provider.
        </description>
        <jta-data-source>jdbc/MyOrderDB</jta-data-source>
        <mapping-file>ormap.xml</mapping-file>
        <jar-file>MyOrderApp.jar</jar-file>
        <class>com.widgets.Order</class>
        <class>com.widgets.Customer</class>
    </persistence-unit>
</persistence>
----

[source,xml]
----
<persistence>
    <persistence-unit name="OrderManagement2">
        <description>
            This unit manages inventory for auto parts.
            It depends on features provided by the
            com.acme.persistence implementation.
        </description>
        <provider>com.acme.AcmePersistence</provider>
        <jta-data-source>jdbc/MyPartDB</jta-data-source>
        <mapping-file>ormap2.xml</mapping-file>
        <jar-file>MyPartsApp.jar</jar-file>
        <properties>
            <property name="com.acme.persistence.sql-logging" value="on"/>
        </properties>
    </persistence-unit>
</persistence>
----

===== name

The `name` attribute defines the name of the persistence unit. This name is
used to identify the persistence unit referred to by a `PersistenceContext`
or `PersistenceUnit` annotation and in the programmatic API for creating an
entity manager factory.

===== transaction-type [[a12296]]

The `transaction-type` attribute specifies whether entity managers created by
the entity manager factory for the persistence unit are JTA entity managers or
resource-local entity managers. The value of this element must be `JTA` or
`RESOURCE_LOCAL`:

- `JTA` means that a JTA data source is provided—either as specified by the
  `jta-data-source` element, or by the container.
- In a Jakarta EE environment, `RESOURCE_LOCAL` usually means that a non-JTA
  datasource is provided.

Configuration of datasources is described below in <<a12302>>.

If the `transaction-type` is not explicitly specified, its value is defaulted:

- in a Jakarta EE environment, the default is `JTA`, but
- in a Java SE environment, the default is `RESOURCE_LOCAL`.

===== description

The `description` element provides optional descriptive information about the
persistence unit.

===== provider [[a12300]]

The `provider` element specifies the name of a provider-specific implementation
of `jakarta.persistence.spi.PersistenceProvider`. The `provider` element is
optional, but should be explicitly specified if the application depends on the
use of a particular persistence provider.

===== qualifier [[a12310]]

The `qualifier` element specifies the fully-qualified class name of
an annotation annotated `jakarta.inject.Qualifier`. This qualifier
annotation may be used to disambiguate the persistence unit for the
purposes of dependency injection.

===== scope [[a12311]]

The `scope` element specifies the fully-qualified class name of an
annotation annotated `jakarta.inject.Scope` or
`jakarta.enterprise.context.NormalScope`. This scope annotation may
be used to determine the scope of a persistence context for the
purposes of dependency injection.

===== jta-data-source, non-jta-data-source [[a12302]]

In Jakarta EE environments:

- the `jta-data-source` element specifies the JNDI name of a JTA data source,
  and/or
- the `non-jta-data-source` element specifies the JNDI name of a non-JTA data
  source.

The specified data source is used by the persistence provider to obtain database
connections. If neither element is specified, the deployer must specify a data
source at deployment, or a default data source must be provided by the container.

In Java SE environments, these elements may be used, or the data source
information may be specified by other means, depending upon the requirements
of the provider.

===== mapping-file, jar-file, class, exclude-unlisted-classes [[a12305]]

The following classes must be implicitly or explicitly denoted as managed
persistence classes to be included within a persistence unit:

- entity classes;
- embeddable classes;
- mapped superclasses;
- converter classes.

The set of managed persistence classes managed by a persistence unit is
specified using one or more of the following:footnote:[Note that an
given class may be used in more than one persistence unit.]

- annotated managed persistence classes contained in the root of the
  persistence unit (unless the `exclude-unlisted-classes` element is
  specified);
- one or more object/relational mapping XML files;
- one or more JAR files to be searched for classes;
- an explicit list of classes.

The set of entities managed by the persistence unit is the union of these
sources, with the mapping metadata annotations (or annotation defaults)
for any given class being overridden by the XML mapping information file
if there are both annotations and XML mappings for that class. The minimum
portable level of overriding is at the level of the persistent field or
property.

The classes and/or jars that named as part of a persistence unit must be
on the classpath; referencing them from the `persistence.xml` file does
not cause them to be placed on the classpath.

All classes must be on the classpath to ensure that entity managers from
different persistence units that map the same class will be accessing the
same identical class.

====== Annotated Classes in the Root of the Persistence Unit

By default, in the Java EE environment, the root of the persistence
unit is searched for annotated managed persistence classes—classes
with an `Entity`, `Embeddable`, `MappedSuperclass`, or `Converter`
annotation—and mapping metadata annotations found on these classes
are processed. Where mapping annotations are missing, the classes
are mapped using mapping annotation defaults.

This behavior is disabled if the `exclude-unlisted-classes` of the
`persistence.xml` file is specified as `true`. In this case, an
annotated persistence class located in the root of the persistence
unit is not included in the persistence unit unless it is explicitly
listed in a `class` element of the `persistence.xml` file or in a
mapping file.

In the Java SE environment, this behavior is not required. Portable
Java SE applications should explicitly list each persistence class
in a `class` element of the `persistence.xml` file or in a mapping
file. The `exclude-unlisted-classes` element is not intended for use
in Java SE environments.

====== Object/relational Mapping Files

An object/relational mapping XML file contains mapping information for
the classes it lists.

- An object/relational mapping XML file named `orm.xml` may be located
  in the `META-INF` directory in the root of the persistence unit or in
  the `META-INF` directory of any jar file referenced by the
  `persistence.xml`.

- Alternatively, or in addition, one or more mapping files may be
  referenced by the `mapping-file` elements of the `persistence-unit`
  element. These mapping files may be present anywhere on the class path.

An `orm.xml` mapping file or other mapping file is loaded as a resource
by the persistence provider. If a mapping file is specified, the classes
and mapping information listed in the mapping file are used as described
in <<a16944>>.

If multiple mapping files are specified (possibly including one or more
`orm.xml` files), the resulting mappings are obtained by combining the
mappings from all the files. If multiple mapping files referenced within
a single persistence unit (including any `orm.xml` file) contain
overlapping mapping information for a given class, the result is
undefined. That is, the object/relational mapping information contained
in any given mapping file referenced within the persistence unit must be
disjoint at the class level from object/relational mapping information
contained in other mapping files referenced within the persistence unit.

====== Jar Files

One or more JAR files may be specified using `jar-file` elements instead
of, or in addition to, the mapping files listed by the `mapping-file`
elements. These JAR files are searched for managed persistence classes
and any mapping metadata annotations found on them are processed. Where
mapping annotations are missing, the classes are mapped using the mapping
annotation defaults defined by this specification. Such JAR files are
specified relative to the directory or jar file that `contains` the root
of the persistence unit.footnote:[Persistence providers are encouraged to
support this syntax for use in Java SE environments.]

The following examples illustrate the use of the `jar-file` element to
reference additional persistence classes. These examples make use of the
convention that a jar file with a name terminating in "`PUnit`" contains
the `persistence.xml` file and that a jar file with a name terminating in
"`Entities`" contains additional persistence classes.

*Example 1:*

----
app.ear
    lib/earEntities.jar
    earRootPUnit.jar (with META-INF/persistence.xml)
----

`persistence.xml` contains:

[source,xml]
----
<jar-file>lib/earEntities.jar</jar-file>
----

*Example 2:*

----
app.ear
    lib/earEntities.jar
    lib/earLibPUnit.jar (with META-INF/persistence.xml)
----

`persistence.xml` contains:

[source,xml]
----
<jar-file>earEntities.jar</jar-file>
----

*Example 3:*

----
app.ear
    lib/earEntities.jar
    ejbjar.jar (with META-INF/persistence.xml)
----

`persistence.xml` contains:

[source,xml]
----
<jar-file>lib/earEntities.jar</jar-file>
----

*Example 4:*

----
app.ear
    war1.war
        WEB-INF/lib/warEntities.jar
        WEB-INF/lib/warPUnit.jar (with META-INF/persistence.xml)
----

`persistence.xml` contains:

[source,xml]
----
<jar-file>warEntities.jar</jar-file>
----

*Example 5:*

----
app.ear
    war2.war
        WEB-INF/lib/warEntities.jar
        WEB-INF/classes/META-INF/persistence.xml
----

`persistence.xml` contains:

[source,xml]
----
<jar-file>lib/warEntities.jar</jar-file>
----

*Example 6:*

----
app.ear
    lib/earEntities.jar
    war2.war
        WEB-INF/classes/META-INF/persistence.xml
----

`persistence.xml` contains:

[source,xml]
----
<jar-file>../../lib/earEntities.jar</jar-file>
----

*Example 7:*

----
app.ear
    lib/earEntities.jar
    war1.war
        WEB-INF/lib/warPUnit.jar (with META-INF/persistence.xml)
----

`persistence.xml` contains:

[source,xml]
----
<jar-file>../../../lib/earEntities.jar</jar-file>
----

====== List of Managed Classes

A list of named managed persistence classes—entity classes, embeddable
classes, mapped superclasses, and converter classes—may be specified
instead of, or in addition to, the listed JAR files and mapping files.
Any mapping metadata annotations found on these classes are processed.
Where mapping annotations are missing, the classes are mapped using
the mapping annotation defaults. The `class` element is used to list
a managed persistence class.

In Java SE environments, an explicit list of all managed persistence
class names must be specified to insure portability. Portable Java SE
applications should not rely on the other mechanisms described here to
determine the managed persistence classes of a persistence unit. In
Java SE environments, a persistence provider may require that the set
of entity classes and other classes to be managed is fully enumerated
in each `persistence.xml` file.

===== shared-cache-mode [[a12380]]

The `shared-cache-mode` element determines whether second-level caching
is in effect for the persistence unit. See <<a3065>>.

===== validation-mode [[a12382]]

The `validation-mode` element determines whether automatic lifecycle
event time validation is in effect. See <<a2374>>.

===== properties [[a12384]]

The `properties` element is used to specify both standard and
vendor-specific properties and hints that apply to the persistence unit
and its entity manager factory configuration.

The following properties and hints defined by this specification are
intended for use in both Jakarta EE and Java SE environments:

`jakarta.persistence.lock.timeout`::

The pessimistic lock timeout in milliseconds. This is a hint only.
`jakarta.persistence.query.timeout`::
The query timeout in milliseconds. This is a hint only.
`jakarta.persistence.validation.group.pre-persist`::
Bean Validation groups that are targeted for validation upon the
pre-persist event (overrides the default behavior).
`jakarta.persistence.validation.group.pre-update`::
Bean Validation groups that are targeted for validation upon the
pre-update event (overrides the default behavior).
`jakarta.persistence.validation.group.pre-remove`::
Bean Validation groups that are targeted for validation upon the
pre-remove event (overrides the default behavior).

The following properties defined by this specification are intended
for use in Java SE environments.

`jakarta.persistence.jdbc.driver`::
Fully qualified name of the JDBC driver class.
`jakarta.persistence.jdbc.url`::
Driver-specific connection URL.
`jakarta.persistence.jdbc.user`::
Username for database connection authentication.
`jakarta.persistence.jdbc.password`::
Password for database connection authentication

Scripts for use in schema generation may be specified using the
`jakarta.persistence.schema-generation.create-script-source` and
`jakarta.persistence.schema-generation.drop-script-source` properties.
A script to specify SQL for the bulk loading of data may be specified
by the `jakarta.persistence.sql-load-script-source` property. These
properties are intended for use in both Jakarta EE and Java SE
environments:

`jakarta.persistence.schema-generation.create-script-source`::
Name of a script packaged as part of the persistence application or
a string identifying a file URL that designates a script.
`jakarta.persistence.schema-generation.drop-script-source`::
Name of a script packaged as part of the persistence application or
a string identifying a file URL that designates a script.
`jakarta.persistence.sql-load-script-source`::
Name of a script packaged as part of the persistence unit or a string
identifying a file URL that designates a script.

When scripts are packaged as part of the persistence application, these
properties must specify locations relative to the root of the persistence
unit. When scripts are provided externally (or when schema generation is
configured to write script files, as described below), strings identifying
file URLs must be specified. In Jakarta EE environments, such file URLs
must be absolute paths. In Jakarta EE environments, all source and target
file locations must be accessible to the application server deploying the
persistence unit.

In general, it is expected that schema generation will be initiated by
means of the APIs described in <<a12917>>. However, schema generation
actions may also be specified by means of the following properties used
in the `persistence.xml` file.

`jakarta.persistence.schema-generation.database.action` ::
The `jakarta.persistence.schema-generation.database.action` property specifies
the action to be taken by the persistence provider with regard to the
database artifacts. The values for this property are `none`, `create`,
`drop-and-create`, `drop`, `validate`. If this property is not specified,
it is assumed that schema generation is not needed or will be initiated by
other means, and, by default, no schema generation actions will be taken
on the database. (See <<a12917>>.)
`jakarta.persistence.schema-generation.scripts.action` ::
The `jakarta.persistence.schema-generation.scripts.action` property specifies
which scripts are to be generated by the persistence provider. The
values for this property are `none`, `create`, `drop-and-create`,
`drop`. A script will only be generated if the script target is
specified. If this property is not specified, it is assumed that script
generation is not needed or will be initiated by other means, and, by
default, no scripts will be generated. (See <<a12917>>.)
`jakarta.persistence.schema-generation.create-source` ::
The `jakarta.persistence.schema-generation.create-source` property specifies
whether the creation of database artifacts is to occur on the basis of
the object/relational mapping metadata, DDL script, or a combination of
the two. The values for this property are `metadata`, `script`,
`metadata-then-script`, `script-then-metadata`. If this property is
not specified, and a script is specified by the
`jakarta.persistence.schema-generation.create-script-source` property, the
script (only) will be used for schema generation; otherwise if this
property is not specified, schema generation will occur on the basis of
the object/relational mapping metadata (only). The
`metadata-then-script` and `script-then-metadata` values specify that a
combination of metadata and script is to be used and the order in which
this use is to occur. If either of these values is specified and the
resulting database actions are not disjoint, the results are undefined
and schema generation may fail.
`jakarta.persistence.schema-generation.drop-source` ::
The `jakarta.persistence.schema-generation.drop-source` property specifies
whether the dropping of database artifacts is to occur on the basis of
the object/relational mapping metadata, DDL script, or a combination of
the two. The values for this property are `metadata`, `script`,
`metadata-then-script`, `script-then-metadata`. If this property is
not specified, and a script is specified by the
`jakarta.persistence.schema-generation.drop-script-source` property, the
script (only) will be used for the dropping of database artifacts;
otherwise if this property is not specified, the dropping of database
artifacts will occur on the basis of the object/relational mapping
metadata (only). The `metadata-then-script` and `script-then-metadata`
values specify that a combination of metadata and script is to be used
and the order in which this use is to occur. If either of these values
is specified and the resulting database actions are not disjoint, the
results are undefined and the dropping of database artifacts may fail.
`jakarta.persistence.schema-generation.scripts.create-target`, ::
`jakarta.persistence.schema-generation.scripts.drop-target` ::
If scripts are to be generated, the target
locations for the writing of these scripts must be specified. These
targets are specified as strings corresponding to file URLs.

If a persistence provider does not recognize a property (other than a
property defined by this specification), the provider must ignore it.

Vendors should define properties in vendor-specific namespaces, (e.g
`com.acme.persistence.logging`). The namespace `jakarta.persistence`
is reserved for use by this specification, and must not be used to
define vendor-specific properties.

The following are sample contents of a `persistence.xml` file.

*Example 1:*

[source,xml]
----
<persistence-unit name="OrderManagement"/>
----

A persistence unit named `OrderManagement` is created.

Any annotated managed persistence classes
found in the root of the persistence unit are added to the list of
managed persistence classes. If a `META-INF/orm.xml` file exists, any
classes referenced by it and mapping information contained in it are
used as specified above. Because no provider is specified, the
persistence unit is assumed to be portable across providers. Because the
transaction type is not specified, JTA is assumed for Jakarta EE
environments. The container must provide the data source (it may be
specified at application deployment, for example). In Java SE
environments, the data source may be specified by other means and a
transaction type of `RESOURCE_LOCAL` is assumed.

*Example 2:*

[source,xml]
----
<persistence-unit name="OrderManagement2">
    <mapping-file>mappings.xml</mapping-file>
</persistence-unit>
----

A persistence unit named `OrderManagement2`
is created. Any annotated managed persistence classes found in the root
of the persistence unit are added to the list of managed persistence
classes. The `mappings.xml` resource exists on the classpath and any
classes and mapping information contained in it are used as specified
above. If a `META-INF/orm.xml` file exists, any classes and mapping
information contained in it are used as well. The transaction type, data
source, and provider are as described above.

*Example 3:*

[source,xml]
----
<persistence-unit name="OrderManagement3">
    <jar-file>order.jar</jar-file>
    <jar-file>order-supplemental.jar</jar-file>
</persistence-unit>
----

A persistence unit named `OrderManagement3`
is created. Any annotated managed persistence classes found in the root
of the persistence unit are added to the list of managed persistence
classes. If a `META-INF/orm.xml` file exists, any classes and mapping
information contained in it are used as specified above. The `order.jar`
and `order-supplemental.jar` files are searched for managed persistence
classes and any annotated managed persistence classes found in them
and/or any classes specified in the `orm.xml` files of these jar files
are added. The transaction-type, data source and provider are as
described above.

*Example 4:*

[source,xml]
----
<persistence-unit name="OrderManagement4" transaction-type=RESOURCE_LOCAL>
    <non-jta-data-source>java:app/jdbc/MyDB</non-jta-data-source>
    <mapping-file>order-mappings.xml</mapping-file>
    <class>com.acme.Order</class>
    <class>com.acme.Customer</class>
    <class>com.acme.Item</class>
    <exclude-unlisted-classes/>
</persistence-unit>
----

A persistence unit named `OrderManagement4`
is created. The file `order-mappings.xml` is read as a resource and any
classes referenced by it and mapping information contained in it are
usedfootnote:[Note that in this
example a META-INF/orm.xml file is assumed not to exist.].
The annotated `Order`, `Customer` and
`Item` classes are loaded and are added. No (other) classes contained in
the root of the persistence unit are added to the list of managed
persistence classes. The persistence unit assumed to be portable across
providers. A entity manager factory supplying resource-local entity
managers will be created. The data source `java:app/jdbc/MyDB` must be
used.

*Example 5:*

[source,xml]
----
<persistence-unit name="OrderManagement5">
    <provider>com.acme.AcmePersistence</provider>
    <mapping-file>order1.xml</mapping-file>
    <mapping-file>order2.xml</mapping-file>
    <jar-file>order.jar</jar-file>
    <jar-file>order-supplemental.jar</jar-file>
</persistence-unit>
----

A persistence unit named `OrderManagement5`
is created. Any annotated managed persistence classes found in the root
of the persistence unit are added to the list of managed classes. The
`order1.xml` and `order2.xml` files are read as resources and any
classes referenced by them and mapping information contained in them are
also used as specified above. The `order.jar` is a jar file on the
classpath containing another persistence unit, while
`order-supplemental.jar` is just a library of classes. Both of these jar
files are searched for annotated managed persistence classes and any
annotated managed persistence classes found in them and any classes
specified in the `orm.xml` files (if any) of these jar files are added.
The provider `com.acme.AcmePersistence` must be used.

[NOTE]
====
Note that the `persistence.xml` file
contained in `order.jar` is not used to augment the persistence unit
`OrderManagement5` with the classes of the persistence unit whose root
is `order.jar`.
====

==== Persistence Unit Scope [[a12459]]

An EJB-JAR, WAR, application client JAR, or EAR can define a persistence
unit. When referencing a persistence unit using the `unitName` annotation
element or `persistence-unit-name` deployment descriptor element, the
visibility scope of the persistence unit is determined by its point of
definition:

- A persistence unit defined at the level of an EJB-JAR, WAR, or
  application client JAR is scoped to that EJB-JAR, WAR, or application
  JAR respectively and is visible to the components defined in that jar
  or WAR.
- A persistence unit defined at the level of an EAR is generally visible
  to all components in the application. However, if a persistence unit of
  the same name is defined by an EJB-JAR, WAR, or application JAR file
  within the EAR, the persistence unit of that name defined at EAR level
  will not be visible to the components defined by that EJB-JAR, WAR, or
  application JAR file, unless the persistence unit reference uses the
  persistence unit name # syntax to specify a path name to disambiguate
  the reference.

The # syntax may be used with both the `unitName` annotation element or
`persistence-unit-name` deployment descriptor element to reference a
persistence unit defined at EAR level.

When the # syntax is used, the path name is interpreted relative to the
referencing application component jar file. For example, the syntax
`../lib/persistenceUnitRoot.jar#myPersistenceUnit` refers to a persistence
unit with:

- name `myPersistenceUnit`, as specified in the `name` element of the
  `persistence.xml` file, and
- root given by the relative path name `../lib/persistenceUnitRoot.jar`.

=== persistence.xml Schema

This section provides the XML schema for the `persistence.xml` file.

[source,xml]
----
include::../../../../api/src/main/resources/jakarta/persistence/persistence_4_0.xsd[lines=1..1]
include::../../../../api/src/main/resources/jakarta/persistence/persistence_4_0.xsd[lines=15..-1]
----