//
// Copyright (c) 2017, 2024 Contributors to the Eclipse Foundation
//

== Container and Provider Contracts for Deployment and Bootstrapping

This chapter defines requirements on the Jakarta EE container and on
the persistence provider for deployment and bootstrapping.

=== Jakarta EE Deployment [[a12802]]

Each persistence unit deployed into a Jakarta EE
container consists of a single `persistence.xml` file, any number of
mapping files, and any number of class files.

At deployment time the container is
responsible for scanning the locations specified in <<a12236>> and
discovering the `persistence.xml` files and processing them.

When the container finds a `persistence.xml`
file, it must process the persistence unit definitions that it contains.
The container must validate the `persistence.xml` file against the
`persistence_4_0.xsd`, `persistence_3_2.xsd`, `persistence_3_0.xsd`
or `persistence_2_2.xsd` schema in accordance with
the version specified by the `persistence.xml` file and report any validation errors.
Provider or data source information not specified in the `persistence.xml` file
must be provided at deployment time or defaulted by the container. The
container may optionally add any container-specific properties to be
passed to the provider when creating the entity manager factory for the
persistence unit.

Once the container has read the persistence
metadata, it determines the `jakarta.persistence.spi.PersistenceProvider`
implementation class for each deployed named persistence unit. The
container then creates an instance of the `PersistenceProvider`
implementation class for each deployed named persistence unit and
invokes the `createContainerEntityManagerFactory` method on that
instance.

* The container must implement the
`PersistenceUnitInfo` interface described in <<a13160>> and pass the
metadata—in the form of a `PersistenceUnitInfo` instance—to the
persistence provider as part of this call.
* If a Bean Validation provider exists in the
container environment and the `validation-mode` `NONE` is not specified,
a `ValidatorFactory` instance must be made available by the container.
The container is responsible for passing this `ValidatorFactory`
instance via the map that is passed as an argument to the
`createContainerEntityManagerFactory` call. The map key used must be the
standard property name `jakarta.persistence.validation.factory`.
* If CDI is enabled, a `BeanManager` instance
must be made available by the container. The container is responsible
for passing this `BeanManager` instance via the map that is passed as an
argument to the `createContainerEntityManagerFactory` call. The map key
used must be the standard property name `jakarta.persistence.bean.manager`.

The `EntityManagerFactory` instance obtained
as a result will be used by the container to create container-managed
entity managers. Only one `EntityManagerFactory` is permitted to be
created for each deployed persistence unit configuration. Any number of
`EntityManager` instances may be created from a given factory.

In a Jakarta EE environment, the classes of the
persistence unit should not be loaded by the application class loader or
any of its parent class loaders until after the entity manager factory
for the persistence unit has been created.

When a persistence unit is redeployed, the
container should call the `close` method on the previous
`EntityManagerFactory` instance and call the
`createContainerEntityManagerFactory` method again, with the required
`PersistenceUnitInfo` metadata, to achieve the redeployment.

=== Bootstrapping in Java SE Environments

In Java SE environments, the
`Persistence.createEntityManagerFactory` method is used by the
application to create an entity manager factoryfootnote:[Use of these Java SE
bootstrapping APIs may be supported in Jakarta EE containers; however,
support for such use is not required.].

A persistence provider implementation running
in a Java SE environment should also act as a service provider by
supplying a service provider configuration file as defined by the Java
SE platform.

The provider configuration file serves to
export the provider implementation class to the `Persistence` bootstrap
class, positioning the provider as a candidate for backing named
persistence units. The provider supplies the provider configuration file
by creating a text file named
`jakarta.persistence.spi.PersistenceProvider` and placing it in the
`META-INF/services` directory of one of its JAR files. The contents of
the file should be the name of the provider implementation class of the
`jakarta.persistence.spi.PersistenceProvider` interface.

*Example:*

A persistence vendor called ACME persistence
products ships a JAR called `acme.jar` that contains its persistence
provider implementation. The JAR includes the provider configuration
file.

----
acme.jar
    META-INF/services/jakarta.persistence.spi.PersistenceProvider
    com.acme.PersistenceProvider
    ...
----

The contents of the
`META-INF/services/jakarta.persistence.spi.PersistenceProvider` file is
nothing more than the name of the implementation class:
`com.acme.PersistenceProvider`.

Persistence provider jars may be installed or
made available in the same ways as other service providers, e.g. as
extensions or added to the application classpath.

The `Persistence` bootstrap class must locate
all of the persistence providers using the `PersistenceProviderResolver`
mechanism described in <<a12837>> and call
`createEntityManagerFactory` on them in turn until an appropriate
backing provider returns an `EntityManagerFactory` instance. A provider
may deem itself as appropriate for the persistence unit if any of the
following are true:

* Its implementation class has been specified
in the `provider` element for that persistence unit in the
`persistence.xml` file and has not been overridden by a different
`jakarta.persistence.provider` property value included in the Map passed
to the `createEntityManagerFactory` method.
* The `jakarta.persistence.provider` property was
included in the Map passed to `createEntityManagerFactory` and the value
of the property is the provider's implementation class.
* No provider was specified for the persistence
unit in either the `persistence.xml` or the property map.

If a provider does not qualify as the
provider for the named persistence unit, it must return `null` when
`createEntityManagerFactory` is invoked on it.

==== Schema Generation [[a12803]]

In Java SE environments, the
`Persistence.generateSchema` method may be used by the application to
cause schema generation to occur as a separate phase from entity manager
factory creation.

In this case, the `Persistence` bootstrap
class must locate all of the persistence providers using the
`PersistenceProviderResolver` mechanism described in <<a12837>>
and call `generateSchema` on them in turn until an
appropriate backing provider returns `true`. A provider may deem itself
as appropriate for the persistence unit if any of the following are
true:

* Its implementation class has been specified
in the `provider` element for that persistence unit in the
`persistence.xml` file and has not been overridden by a different
`jakarta.persistence.provider` property value included in the Map passed
to the `generateSchema` method.
* The `jakarta.persistence.provider` property was
included in the Map passed to `generateSchema` and the value of the
property is the provider's implementation class.
* No provider was specified for the persistence
unit in either the `persistence.xml` or the property map.

If a provider does not qualify as the
provider for the named persistence unit, it must return `false` when
`generateSchema` is invoked on it.

=== Determining the Available Persistence Providers [[a12837]]

The `PersistenceProviderResolver` and
`PersistenceProviderResolverHolder` mechanism supports the dynamic
discovery of persistence providers.footnote:[In dynamic environments
(e.g., OSGi-based environments, containers based on dynamic kernels,
etc.), the list of persistence providers may change.]

- The `PersistenceProviderResolver` instance is responsible for
   returning the list of providers available in the environment.

- The `PersistenceProviderResolverHolder` class holds the
  `PersistenceProviderResolver` instance that is in use.

These interfaces may be found in <<persistence-spi>>.

The implementation of `PersistenceProviderResolverHolder` must be
threadsafe, but no guarantee is made against multiple threads setting
the resolver.

The container is allowed to implement
and set a specific `PersistenceProviderResolver` provided that it
respects the `PersistenceProviderResolver` contract. The
`PersistenceProviderResolver` instance to be used is set by the
container using the
`PersistenceProviderResolverHolder.setPersistenceProviderResolver`
method.footnote:[If a custom
PersistenceProviderResolver is needed in a JavaSE environment, it must
be set before Persistence.createEntityManagerFactory is called. Note,
however, that the setPersistenceProviderResolver method is not intended
for general use, but rather is aimed at containers maintaining a dynamic
environment.]

If no `PersistenceProviderResolver` is set,
the `PersistenceProviderResolverHolder` must return a
`PersistenceProviderResolver` that returns the providers whose
persistence provider jars have been installed or made available as
service providers or extensions. This default
`PersistenceProviderResolver` instance does not guarantee the order in
which persistence providers are returned.

A `PersistenceProviderResolver` must be threadsafe.

The
`PersistenceProviderResolver.getPersistenceProviders()` method must be
used to determine the list of available persistence providers.

The results of calling the
`PersistenceProviderResolverHolder.getPersistenceProviderResolver` and
the `PersistenceProviderResolver.getPersistenceProviders` methods must
not be cached. In particular, the following methods must use the
`PersistenceProviderResolver` instance returned by the
`PersistenceProviderResolverHolder.getPersistenceProviderResolver`
method to determine the list of available providers:


* `Persistence.createEntityManagerFactory(String)`
* `Persistence.createEntityManagerFactory(String, Map)`
* `PersistenceUtil.isLoaded(Object)`
* `PersistenceUtil.isLoaded(Object, String)`

These methods must not cache the list of
providers and must not cache the `PersistenceProviderResolver` instance.

[NOTE]
====
Note that the
`PersistenceProviderResolver.getPersistenceProviders()` method can
potentially be called many times. It is therefore recommended that the
implementation of this method make use of caching.
====

Note that only a single
`PersistenceProviderResolver` instance can be defined in a given
classloader hierarchy at a given time.

=== Schema Generation [[a12917]]

In cases where a preconfigured database (or a
“legacy” database) is not used or is not available, the Jakarta Persistence
schema generation facility may be used to generate the tables and other
database artifacts required by the persistence application. Whether
schema generation entails the creation of schemas proper in the database
is determined by the environment and the configuration of the schema
generation process, as described below.

Schema generation may happen either prior to
application deployment or when the entity manager factory is created as
part of the application deployment and initialization process.

* In Jakarta EE environments, the container may
call the `PersistenceProvider` `generateSchema` method separately from
and/or prior to the creation of the entity manager factory for the
persistence unit, or the container may pass additional information to
the `createContainerEntityManagerFactory` call to cause schema
generation to happen as part of the entity manager factory creation and
application initialization process. The information passed to these
methods controls whether the generation occurs directly in the target
database, whether DDL scripts for schema generation are created, or
both.
* In Java SE environments, the application may
call the `Persistence` `generateSchema` method separately from and/or
prior to the creation of the entity manager factory or may pass
information to the `createEntityManagerFactory` method to cause schema
generation to occur as part of the entity manager factory creation.

The application may provide DDL scripts to be
used for schema generation as described in <<a12384>>. The application developer
may package these scripts as part of the persistence unit or may specify
strings corresponding to file URLs for the location of such scripts. In
Jakarta EE environments, such scripts may be executed by the container, or
the container may direct the persistence provider to execute the
scripts. In Java SE environments, the execution of the scripts is the
responsibility of the persistence provider. In the absence of the
specification of scripts, schema generation, if requested, will be
determined by the object/relational metadata of the persistence unit.

The following standard properties are defined
for configuring the schema generation process. In Jakarta EE environments
these properties are passed by the container in the `Map` argument to
either the `PersistenceProvider` `generateSchema` method or the
`createContainerEntityManagerFactory` method. In Java SE environments,
they are passed in the `Map` argument to either the `Persistence`
`generateSchema` method or `createEntityManagerFactory` method.

In Jakarta EE environments, any strings
corresponding to file URLs for script sources or targets must specify
absolute paths (not relative). In Jakarta EE environments, all source and
target file locations must be accessible to the application server
deploying the persistence unit

`jakarta.persistence.schema-generation.database.action` ::
The `jakarta.persistence.schema-generation.database.action` property specifies
the action to be taken by the persistence provider with regard to the
database artifacts. The values for this property are _"none"_,
_"create"_, _"drop-and-create"_, _"drop"_, _"validate"_. If the
`jakarta.persistence.schema-generation.database.action` property is not
specified, no schema generation actions must be taken on the database.
`jakarta.persistence.schema-generation.scripts.action` ::
The `jakarta.persistence.schema-generation.scripts.action` property specifies
which scripts are to be generated by the persistence provider. The
values for this property are _"none"_, _"create"_, _"drop-and-create"_
, _"drop"_. A script will only be generated if the script target is
specified. If this property is not specified, no scripts will be
generated.
`jakarta.persistence.schema-generation.create-source` ::
The `jakarta.persistence.schema-generation.create-source` property specifies
whether the creation of database artifacts is to occur on the basis of
the object/relational mapping metadata, DDL script, or a combination of
the two. The values for this property are _"metadata"_, _"script"_,
_"metadata-then-script"_, _"script-then-metadata"_. If this property
is not specified, and a script is specified by the
`jakarta.persistence.schema-generation.create-script-source` property, the
script (only) will be used for schema generation; otherwise if this
property is not specified, schema generation will occur on the basis of
the object/relational mapping metadata (only). The
_"metadata-then-script"_ and _"script-then-metadata"_ values specify
that a combination of metadata and script is to be used and the order in
which this use is to occur. If either of these values is specified and
the resulting database actions are not disjoint, the results are
undefined and schema generation may fail.
`jakarta.persistence.schema-generation.drop-source` ::
The `jakarta.persistence.schema-generation.drop-source` property specifies
whether the dropping of database artifacts is to occur on the basis of
the object/relational mapping metadata, DDL script, or a combination of
the two. The values for this property are _"metadata"_, _"script"_,
_"metadata-then-script"_, _"script-then-metadata"_. If this property
is not specified, and a script is specified by the
`jakarta.persistence.schema-generation.drop-script-source` property, the
script (only) will be used for the dropping of database artifacts;
otherwise if this property is not specified, the dropping of database
artifacts will occur on the basis of the object/relational mapping
metadata (only). The _"metadata-then-script"_ and
_"script-then-metadata"_ values specify that a combination of metadata
and script is to be used and the order in which this use is to occur. If
either of these values is specified and the resulting database actions
are not disjoint, the results are undefined and the dropping of database
artifacts may fail.
`jakarta.persistence.schema-generation.create-database-schemas` ::
In Jakarta EE environments, it is anticipated
that the Jakarta EE platform provider may wish to control the creation of
database schemas rather than delegate this task to the persistence
provider. The
`jakarta.persistence.schema-generation.create-database-schemas` property
specifies whether the persistence provider is to create the database
schema(s) in addition to creating database objects such as tables,
sequences, constraints, etc. The value of this boolean property should
be set to true if the persistence provider is to create schemas in the
database or to generate DDL that contains “CREATE SCHEMA” commands. If
this property is not supplied, the provider should not attempt to create
database schemas. This property may also be specified in Java SE
environments.
`jakarta.persistence.schema-generation.scripts.create-target`, +
`jakarta.persistence.schema-generation.scripts.drop-target` ::
If scripts are to be generated, the target
locations for the writing of these scripts must be specified. +
The `jakarta.persistence.schema-generation.scripts.create-target` property
specifies a `java.io.Writer` configured for use by the persistence
provider for output of the DDL script or a string specifying the file
URL for the DDL script. This property should only be specified if
scripts are to be generated. +
The `jakarta.persistence.schema-generation.scripts.drop-target` property
specifies a `java.io.Writer` configured for use by the persistence
provider for output of the DDL script or a string specifying the file
URL for the DDL script. This property should only be specified if
scripts are to be generated.
`jakarta.persistence.database-product-name`, ::
`jakarta.persistence.database-major-version`, ::
`jakarta.persistence.database-minor-version` ::
If scripts are to be generated by the
persistence provider and a connection to the target database is not
supplied, the `jakarta.persistence.database-product-name` property must be
specified. The value of this property should be the value returned for
the target database by the JDBC `DatabaseMetaData` method
`getDatabaseProductName`. If sufficient database version information is
not included in the result of this method, the
`jakarta.persistence.database-major-version` and
`jakarta.persistence.database-minor-version` properties should be
specified as needed. These should contain the values returned by the
JDBC `getDatabaseMajorVersion` and `getDatabaseMinorVersion` methods
respectively.
`jakarta.persistence.schema-generation.create-script-source`, +
`jakarta.persistence.schema-generation.drop-script-source` ::
The `jakarta.persistence.schema-generation.create-script-source` and
`jakarta.persistence.schema-generation.drop-script-source` properties are
used for script execution. In Jakarta EE container environments, it is
generally expected that the container will be responsible for executing
DDL scripts, although the container is permitted to delegate this task
to the persistence provider. If DDL scripts are to be used in Java SE
environments or if the Jakarta EE container delegates the execution of
scripts to the persistence provider, these properties must be specified. +
The
`jakarta.persistence.schema-generation.create-script-source` property
specifies a `java.io.Reader` configured for reading of the DDL script or
a string designating a file URL for the DDL script. +
The
`jakarta.persistence.schema-generation.drop-script-source` property
specifies a `java.io.Reader` configured for reading of the DDL script or
a string designating a file URL for the DDL script.
`jakarta.persistence.schema-generation.connection` ::
The `jakarta.persistence.schema-generation.connection` property specifies the
JDBC connection to be used for schema generation. This is intended for
use in Jakarta EE environments, where the platform provider may want to
control the database privileges that are available to the persistence
provider. This connection is provided by the container, and should be
closed by the container when the schema generation request or entity
manager factory creation completes. The connection provided must have
credentials sufficient for the persistence provider to carry out the
requested actions. If this property is not specified, the persistence
provider should use the DataSource that has otherwise been provided.

==== Data Loading

Data loading, by means of the use of SQL
scripts, may occur as part of the schema generation process after the
creation of the database artifacts or independently of schema
generation. The specification of the
`jakarta.persistence.sql-load-script-source` controls whether data loading
will occur.

`jakarta.persistence.sql-load-script-source` ::
In Jakarta EE container environments, it is
generally expected that the container will be responsible for executing
data load scripts, although the container is permitted to delegate this
task to the persistence provider. If a load script is to be used in Java
SE environments or if the Jakarta EE container delegates the execution of
the load script to the persistence provider, this property must be
specified. + The
`jakarta.persistence.sql-load-script-source` property specifies a
`java.io.Reader` configured for reading of the SQL load script for
database initialization or a string designating a file URL for the
script.

=== Responsibilities of the Persistence Provider

The persistence provider must implement the
`PersistenceProvider` SPI.

In Jakarta EE environments, the persistence
provider must process the metadata that is passed to it at the time
`createContainerEntityManagerFactory` method is called and create an
instance of `EntityManagerFactory` using the `PersistenceUnitInfo`
metadata for the factory. The factory is then returned to the container.

In Java SE environments, the persistence
provider must validate the `persistence.xml` file against the
`persistence` schema that corresponds to the version specified by the
`persistence.xml` file and report any validation errors.

The persistence provider processes the
metadata annotations on the managed classes of the persistence unit.

When the entity manager factory for a
persistence unit is created, it is the responsibility of the persistence
provider to initialize the state of the metamodel classes of the
persistence unit.

When the persistence provider obtains an
object/relational mapping file, it processes the definitions that it
contains. The persistence provider must validate any object/relational
mapping files against the object/relational mapping schema version
specified by the object/relational mapping file and report any
validation errors. The object relational mapping file must specify the
object/relational mapping schema that it is written against by
indicating the `version` element.

In Java SE environments, the application can
pass the `ValidatorFactory` instance via the map that is passed as an
argument to the `Persistence.createEntityManagerFactory` call. The map
key used must be the standard property name
`jakarta.persistence.validation.factory`. If no `ValidatorFactory`
instance is provided by the application, and if a Bean Validation
provider is present in the classpath, the persistence provider must
instantiate the `ValidatorFactory` using the default bootstrapping
approach as defined by the Bean Validation specification
<<a19498>>, namely
`Validation.buildDefaultValidatorFactory()`.

==== jakarta.persistence.spi.PersistenceProvider

The `PersistenceProvider` interface found in <<_persistenceprovider_>>
must be implemented by the persistence provider.

The `PersistenceProvider` implementation class must have a public
constructor with no parameters.

An instance of `PersistenceProvider` is responsible for creating
provider-specific implementations of `EntityManagerFactory`. It
is invoked by the container in Jakarta EE environments and by the
`jakarta.persistence.Persistence` class in Java SE environments. The
`jakarta.persistence.spi.PersistenceProvider` implementation is not
intended to be used by the application.

The properties passed to the `createEntityManagerFactory()` method
in Java SE environments are described further in <<a13443>> below.

==== jakarta.persistence.spi.ProviderUtil

The `ProviderUtil` interface found in <<_providerutil_>> is called by
the `PersistenceUtil` implementation to determine the load status of
an entity or entity attribute. It is not intended to be invoked by the
application.

=== jakarta.persistence.spi.PersistenceUnitInfo Interface [[a13160]]

The `PersistenceUnitInfo` interface may be found in <<_persistenceunitinfo_>>.

The enum `jakarta.persistence.spi.PersistenceUnitTransactionType`
defines whether the entity managers created by the factory will be
JTA or resource-local entity managers. This enum is deprecated.

[source,java]
----
include::../../../../api/src/main/java/jakarta/persistence/spi/PersistenceUnitTransactionType.java[lines=18..-1]
----

The enum `jakarta.persistence.SharedCacheMode`
defines the use of caching. The `persistence.xml` `shared-cache-mode`
element has no default value. The `getSharedCacheMode` method must
return `UNSPECIFIED` if the `shared-cache-mode` element has not been
specified for the persistence unit.

[source,java]
----
include::../../../../api/src/main/java/jakarta/persistence/SharedCacheMode.java[lines=18..-1]
----

The enum `jakarta.persistence.ValidationMode`
defines the validation mode.

[source,java]
----
include::../../../../api/src/main/java/jakarta/persistence/ValidationMode.java[lines=18..-1]
----

==== jakarta.persistence.spi.ClassTransformer Interface

The `ClassTransformer` interface found in <<_classtransformer_>> may be
implemented by a persistence provider to transform entities and managed
classes at class load time or at class redefinition time. A persistence
provider is not required to implement this interface.

=== jakarta.persistence.Persistence Class [[a13443]]

The `Persistence` class may be found in <<_persistence_>>.

The `Persistence` class is used to obtain an `EntityManagerFactory` instance
in Java SE environments. It may also be used for schema generation—i.e., to
create database schemas and/or tables and/or to create DDL scripts.

The `Persistence` class is also available in a Jakarta EE container environment;
however, support for the Java SE bootstrapping APIs is not required in container
environments.

The `Persistence` class is used to obtain a `PersistenceUtil` instance in both
Jakarta EE and Java SE environments.

The `properties` argument passed to the `createEntityManagerFactory`
method is used to specify both standard and vendor-specific properties
and hints intended for use in creating the entity manager factory and
controlling its behavior.

The following properties correspond to the elements and attributes in the
`persistence.xml` file. When any of these properties are specified in the
`Map` parameter passed to the `createEntityManagerFactory` method, their
values override the values of the corresponding elements and attributes
in the `persistence.xml` file for the named persistence unit. They also
override any defaults that the persistence provider might have applied.

[cols="40,10,25,~"]
|===
| Property | Type | Corresponding element in `persistence.xml` | Notes

| `jakarta.persistence.provider`
| `String`
| `provider`
| See <<a12300>>.
| `jakarta.persistence.qualifiers`
| `String[]` | `qualifier`
| See <<a12310>>.
| `jakarta.persistence.scope`
| `String`
| `scope`
| See <<a12310>>.
| `jakarta.persistence.transactionType`
| `String`
| `transaction-type`
| See <<a12296>>.
| `jakarta.persistence.jtaDataSource`
| `String`
| `jta-data-source`
| See <<a12302>>.
| `jakarta.persistence.nonJtaDataSource`
| `String`
| `non-jta-data-source`
| See <<a12302>>.
| `jakarta.persistence.sharedCache.mode`
| `String`
| `shared-cache-mode`
| See <<a12380>>.
| `jakarta.persistence.validation.mode`
| `String`
| `validation-mode`
| Legal values are " `auto` ", " `callback` ", or " `none` ".
See <<a12382>> and <<a2374>>.
|===

The following properties correspond to the  properties in the `persistence.xml`
ile. When any of these properties are specified in the `Map` parameter passed
to the `createEntityManagerFactory` method, their values override the values of
the corresponding properties in the `persistence.xml` file for the named
persistence unit. They also override any defaults that the persistence provider
might have applied.

[cols="35,10,35,~"]
|===
| Property | Type | Corresponding property in `persistence.xml` | Notes

| `jakarta.persistence.lock.timeout`
| `Integer` or `String`
| `jakarta.persistence.lock.timeout`
| Hint only.
Value in milliseconds for pessimistic lock timeout.
See <<a2132>>.
| `jakarta.persistence.query.timeout`
| `Integer` or `String`
| `jakarta.persistence.query.timeout`
| Hint only.
Value in milliseconds for query timeout.
See <<a4391>>.
| `jakarta.persistence.validation.group.pre-persist`
| `String`
| `jakarta.persistence.validation.group.pre-persist`
| See <<a12384>> and <<a2380>>.
| `jakarta.persistence.validation.group.pre-update`
| `String`
| `jakarta.persistence.validation.group.pre-update`
| See <<a12384>> and <<a2380>>.
| `jakarta.persistence.validation.group.pre-remove`
| `String`
| `jakarta.persistence.validation.group.pre-remove`
| See <<a12384>> and <<a2380>>.
| `jakarta.persistence.schema-generation.create-script-source`
| `String`
| `jakarta.persistence.schema-generation.create-script-source`
| See <<a12384>>.
| `jakarta.persistence.schema-generation.drop-script-source`
| `String`
| `jakarta.persistence.schema-generation.drop-script-source`
| See <<a12384>>.
| `jakarta.persistence.sql-load-script-source`
| `String`
| `jakarta.persistence.sql-load-script-source`
| See <<a12384>>.
| `jakarta.persistence.schema-generation.database.action`
| `String`
| `jakarta.persistence.schema-generation.database.action`
| See <<a12384>>.
| `jakarta.persistence.schema-generation.scripts.action`
| `String`
| `jakarta.persistence.schema-generation.scripts.action`
| See <<a12384>>.
| `jakarta.persistence.schema-generation.create-source`
| `String`
| `jakarta.persistence.schema-generation.create-source`
| See <<a12384>>.
| `jakarta.persistence.schema-generation.drop-source`
| `String`
| `jakarta.persistence.schema-generation.drop-source`
| See <<a12384>>.
| `jakarta.persistence.schema-generation.scripts.create-target`
| `String`
| `jakarta.persistence.schema-generation.scripts.create-target`
| See <<a12384>>.
| `jakarta.persistence.schema-generation.scripts.drop-target`
| `String`
| `jakarta.persistence.schema-generation.scripts.drop-target`
| See <<a12384>>.
|===

The following additional standard properties are defined by this specification
for the configuration of the entity manager factory:

[cols="40,~"]
|===
| Property | Value

| `jakarta.persistence.jdbc.driver`
| Fully qualified name of the driver class.
| `jakarta.persistence.jdbc.url`
| Driver-specific JDBC URL as a string.
| `jakarta.persistence.jdbc.user`
| Username for database connection.
| `jakarta.persistence.jdbc.password`
| Password for database connection authentication.
| `jakarta.persistence.dataSource`
| Instance of `javax.sql.DataSource` to be used for the specified
persistence unit.
| `jakarta.persistence.validation.factory`
| Instance of `jakarta.validation.ValidatorFactory`.
|===

Any number of vendor-specific properties may
also be included in the map. If a persistence provider does not
recognize a property (other than a property defined by this
specification), the provider must ignore it.

Vendors should use vendor namespaces for
properties (e.g., `com.acme.persistence.logging`). Entries that make
use of the namespace `jakarta.persistence` and its subnamespaces must not
be used for vendor-specific information. The namespace
`jakarta.persistence` is reserved for use by this specification.

=== jakarta.persistence.PersistenceConfiguration Class [[a13444]]

The `PersistenceConfiguration` class found in <<_persistenceconfiguration_>>
is used to programmatically define and configure a persistence unit and create
an `EntityManagerFactory` instance directly. Thus, `PersistenceConfiguration`
is an alternative to XML-based configuration using `persistence.xml`, and so
the configuration options available via this API reflect the similarly-named
elements of `persistence.xml`. See <<a12237>>.

A programmatically-configured persistence unit is considered a Java SE
persistence unit, even when this API is used within the Jakarta EE
environment.footnote:[Persistence units defined programmatically using the
`PersistenceConfiguration` class do not support JNDI lookup or injection via
the `PersistenceContext` or `PersistenceUnit` annotations.]

A persistence provider may define a subclass of `PersistenceConfiguration`
with vendor-specific configuration options. A provider must support
configuration via any instance of `PersistenceConfiguration` or of any
subclass of `PersistenceConfiguration`. If a subclass defines configuration
options the provider does not recognize, it should ignore those options.

=== PersistenceUtil Interface

The `PersistenceUtil` interface found in <<_persistenceutil_>> is used to
determine the load state of entity instances. The semantics of the methods
of this interface are defined in <<a13592>> below.

==== Contracts for Determining the Load State of an Entity or Entity Attribute [[a13592]]

The implementation of the
`PersistenceUtil.isLoaded(Object)` method must determine the list of
persistence providers available in the runtime
environmentfootnote:[The determining of
the persistence providers that are available is discussed in <<a12837>>.] and call the
`ProviderUtil.isLoaded(Object)` method on each of them until either:

* one provider returns `LoadState.LOADED`. In
this case `PersistenceUtil.isLoaded` returns `true`.
* one provider returns `LoadState.NOT_LOADED`.
In this case `PersistenceUtil.isLoaded` returns `false`.
* all providers return `LoadState.UNKNOWN`. In
this case `PersistenceUtil.isLoaded` returns `true`.

If the `PersistenceUtil` implementation
determines that only a single provider is available in the environment,
it is permitted to use provider-specific methods to determine the result
of `isLoaded(Object)` as long as the semantics defined in <<a2019>> are observed.

The implementation of the
_PersistenceUtil.isLoaded(Object,String)_ method must determine the list
of persistence providers available in the environment and call the
`ProviderUtil.isLoadedWithoutReference` method on each of them until
either:

* one provider returns `LoadState.LOADED`. In
this case `PersistenceUtil.isLoaded` returns `true`.
* one provider returns `LoadState.NOT_LOADED`.
In this case `PersistenceUtil.isLoaded` returns `false`.
* all providers return `LoadState.UNKNOWN`. In
this case, the `PersistenceUtil.isLoaded` method then calls
`ProviderUtil.isLoadedWithReference` on each of the providers until:
** one provider returns `LoadState.LOADED`. In
this case `PersistenceUtil.isLoaded` return `true`.
** one provider returns `LoadState.NOT_LOADED`.
In this case, `PersistenceUtil.isLoaded` returns `false`.
** all providers return `LoadState.UNKNOWN`. In
this case, `PersistenceUtil.isLoaded` returns `true`.

If the `PersistenceUtil` implementation
determines that only a single provider is available in the environment,
it is permitted to use provider specific methods to determine the result
of _isLoaded(Object, String)_ as long as the semantics defined in
<<a2019>> are observed.

NOTE: The rationale for splitting the
determination of load state between the methods isLoadedWithoutReference
and isLoadedWithReference is the following.

* _It is assumed that the provider that loaded
the entity is present in the environment._
* _Providers that use bytecode enhancement
don't need to access an attribute reference to determine its load state,
and can determine if the entity has been provided by them._
* _By first querying all providers using
bytecode enhancement, it is insured that no attribute will be loaded by
side effect._
* _Proxy-based providers do need to access an
attribute reference to determine load state, but will not trigger
attribute loading as a side effect._
* _If no provider recognizes an entity as
provided by it, it is assumed to be an object that is not instrumented
and is considered loaded._