//
// Copyright (c) 2017, 2026 Contributors to the Eclipse Foundation
//

== Metadata Annotations [[metadata-annotations]]

This chapter and chapter <<a13915>> describe the metadata annotations
introduced by this specification.

The XML schema defined in chapter <<a16944>> provides an alternative
to the use of metadata annotations.

The following annotations are declared in the packages
`jakarta.persistence` and `jakarta.persistence.query`.

=== Entity [[entity-annotation]]

The `@Entity` annotation declares that the annotated class is an entity,
as defined in <<a18>>.

[source,java]
----
@Documented
@Target(TYPE)
@Retention(RUNTIME)
public @interface Entity {
    String name() default "";
}
----

`name` :: specifies the entity name. If the `name` is not specified,
  the entity name defaults to the unqualified name of the entity class.
  This name is used to refer to the entity in queries, as specified in
  <<naming>>. The name must be a legal Java identifier and must not be
  a reserved identifier in the Jakarta Persistence query language.

=== Entity Listeners and Callback Annotations

The following annotations are used to declare entity listeners
and callback methods, as specified in <<a2153>>.

==== `EntityListener` Annotation

The `@EntityListener` annotation declares an entity listener class
and determines the entity classes to which it applies. The entity
listener receives entity lifecycle callbacks for every entity
class belonging to the persistence unit and assignable to one of
its declared entity lifecycle callback methods. It is not
necessary to separately declare the entity classes to which the
listener applies.

[source,java]
----
@Target(TYPE)
@Retention(RUNTIME)
@Discoverable
public @interface EntityListener {
}
----

==== `EntityListeners` Annotation

Alternatively, the `@EntityListeners` annotation specifies the
entity listener classes associated with the annotated class,
package, or module.
This annotation may be applied:

- directly to an entity class or mapped superclass, to specify
  its listener classes,
- to a package descriptor to specify listener classes applying
  to every entity contained in the package, or
- to a module descriptor to specify listener classes applying
  to every entity contained in any package belonging to the
  module.

Entity listeners specified using this annotation do not need to
be annotated `@EntityListener`.

[source,java]
----
@Target({TYPE, PACKAGE, MODULE})
@Retention(RUNTIME)
@Discoverable
public @interface EntityListeners {
    Class<?>[] value();
}
----

The `@ExcludeSuperclassListeners` annotation specifies that the
invocation of superclass listeners is to be excluded for the
annotated entity class or mapped superclass and for its subclasses.

[source,java]
----
@Target({TYPE})
@Retention(RUNTIME)
public @interface ExcludeSuperclassListeners {
}
----

The `@ExcludeDefaultListeners` annotation specifies that the
invocation of default listeners is to be excluded for the
annotated entity class or mapped superclass and for its
subclasses.

[source,java]
----
@Target({TYPE})
@Retention(RUNTIME)
public @interface ExcludeDefaultListeners {
}
----

==== Callback methods

The following annotations are used to declare callback methods
for the corresponding lifecycle events, as specified in
<<lifecycle-callback-methods>>. These annotations may be applied
to methods of an entity class, of a mapped superclass, or of an
entity listener class.

[source,java]
----
@Target({METHOD})
@Retention(RUNTIME)
public @interface PrePersist {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PostPersist {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PreRemove {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PostRemove {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PreMerge {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PreInsert {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PostInsert {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PreUpdate {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PostUpdate {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PreUpsert {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PostUpsert {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PreDelete {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PostDelete {}

@Target({METHOD})
@Retention(RUNTIME)
public @interface PostLoad {}
----

=== EntityGraph Annotations [[a13662]]

The following annotations are used to declare named entity graphs and
attribute-level fetch options. Entity graphs are specified in <<a2397>>.

==== NamedEntityGraph and NamedEntityGraphs Annotations

The `@NamedEntityGraph` annotation defines a named entity graph or a
subgraph of a named entity graph. The annotation must be applied to the
root entity of the graph or subgraph. The nodes and subgraphs of the
entity graph specify the limits of the graph of associated attributes
and entities fetched when an operation which retrieves an instance or
instances of the root entity is executed.

The nodes and subgraphs of a named entity graph defined using annotations
may be specified by:

- nesting `@NamedAttributeNode` and `@NamedSubgraph` annotations within
  the `@NamedEntityGraph` annotation,
- by annotating persistent attributes with `@Fetch`, or
- by mixing these two approaches.

[source,java]
----
@Target({TYPE})
@Retention(RUNTIME)
@Repeatable(NamedEntityGraphs.class)
public @interface NamedEntityGraph {
    String name() default "";
    NamedAttributeNode[] attributeNodes() default {};
    boolean includeAllAttributes() default false;
    NamedSubgraph[] subgraphs() default {};
    NamedSubgraph[] subclassSubgraphs() default {};
}
----

`name` :: assigns a name to the entity graph, and is used to identify the
  entity graph in calls to `EntityHandler.getEntityGraph()`. If no name is
  explicitly specified, the name defaults to the entity name of the
  annotated root entity. Entity graph names must be unique within the
  persistence unit, unless two `@NamedEntityGraph` annotations declare the
  same name and one is a subgraph of the other, as specified by `@Fetch`
  annotations belonging to the named graph.

`attributeNodes` :: a list of attributes of the root entity that are
  included as attribute nodes in the entity graph. Each attribute is
  declared via a `@NamedAttributeNode` annotation. Optionally, a node may
  specify the name of a `subgraph` or `keySubgraph` rooted at the node, as
  specified below in <<named-attribute-node>>.

`includeAllAttributes` :: specifies that every attribute of the annotated
  entity class is included in the entity graph.footnote:[Even when every
  attribute is included in the graph, the `attributeNode` element might
  still be useful to specify a subgraph rooted at an attribute.]

`subgraphs` :: a list of named subgraphs of the named entity graph. Each
  subgraph is declared via a `@NamedSubgraph` annotation. A subgraph must
  be referenced by name from a `subgraph` or `keySubgraph` element of a
  `@NamedAttributeNode` annotation of the graph. A subgraph may declare
  its own attribute nodes via nested `@NamedAttributeNode` annotations,
  as specified below in <<named-subgraph>>.

`subclassSubgraphs` :: a list of subgraphs representing subclasses of the
  root entity of the graph. Each `@NamedSubgraph` must specify a `type`
  which is a subclass of the annotated root entity of the graph and may
  declare additional attribute nodes representing attributes belonging to
  that subclass.

As an alternative to nesting `@NamedAttributeNode` and `@NamedSubgraph`
annotations within `@NamedEntityGraph`, the `@Fetch` annotation defined
below in <<fetch>> may be applied to a persistent attribute of an entity
class. When its `graph` member names a named entity graph, the annotated
attribute is included as an attribute node of that graph. Its `subgraph`
member names one or more entity graphs to be attached as subgraphs to the
attribute node.

A well-defined entity graph is a tree. The application is responsible
for ensuring that every named entity graph is acyclic. If a named entity
graph contains a cycle, the behavior is undefined. A provider may reject
the graph at runtime; it may reject it when the persistence unit is
initialized; or it may transform the graph into an acyclic graph according
to some vendor-specific algorithm. Portable applications must avoid relying
on such behavior.

The `@NamedEntityGraphs` annotation may be used to declare multiple named
entity graphs for the annotated entity.

[source,java]
----
@Target({TYPE})
@Retention(RUNTIME)
public @interface NamedEntityGraphs {
    NamedEntityGraph[] value();
}
----

==== NamedAttributeNode Annotation [[named-attribute-node]]

The `@NamedAttributeNode` annotation declares an attribute node of an
entity graph or subgraph.

[source,java]
----
@Target({})
@Retention(RUNTIME)
public @interface NamedAttributeNode {
    String value();
    String subgraph() default "";
    String keySubgraph() default "";
}
----

`value` :: specifies the name of the attribute represented by the node.

`subgraph` :: declares a subgraph rooted at the attribute node. If the
  attribute represented by the node is a collection, the subgraph
  represents the elements of the collection, or, in the case of a `Map`,
  the values of the map.

`keySubgraph` :: may only be used when an attribute node represents an
  attribute of type `Map`. It declares a subgraph representing the key
  of the map.

Optionally, a node may specify the name of a `subgraph` or `keySubgraph`
rooted at the node. A subgraph name must resolve to:

- the `name` of a `@NamedSubgraph` annotation nested within the same
  `@NamedEntityGraph`, or to
- the `name` of a subgraph declared by a different `@NamedEntityGraph`
  annotation.

The type of the specified subgraph must be compatible with the type of
the attribute represented by the node. In the case of a `@NamedSubgraph`,
the type of the subgraph is given by its `type` element; in the case of
`@NamedEntityGraph`, it is the annotated entity type.

If the root type of the subgraph is an entity type with entity subclasses,
there might be more than one `@NamedSubgraph` annotation with the specified
name. In this case, every such matching subgraph is considered to be rooted
at the node.

==== NamedSubgraph Annotation [[named-subgraph]]

The `@NamedSubgraph` annotation declares a named subgraph of a
`@NamedEntityGraph` representing an associated or embedded entity or
embeddable type.

[source,java]
----
@Target({})
@Retention(RUNTIME)
public @interface NamedSubgraph {
    String name();
    Class<?> type() default void.class;
    NamedAttributeNode[] attributeNodes();
}
----

`name` :: the name of the subgraph. A subgraph must be referenced by name
  from a `subgraph` or `keySubgraph` element of a `@NamedAttributeNode`
  annotation of the graph.

`type` :: the entity or embeddable type represented by the subgraph,
  which defaults to the declared type of the attribute represented by
  the referencing attribute node. The `type` must be explicitly specified
  when the subgraph represents an entity subclass of the entity type of
  the attribute.

`attributeNodes` :: a list of attributes of the entity or embedded type
  represented by the subgraph that are included as attribute nodes in the
  entity graph. Each attribute is declared via a `@NamedAttributeNode`
  annotation. If the subgraph represents an entity subclass of the entity
  type of the attribute, only attributes declared by the subclass may be
  included in the list.

The name of the subgraph is scoped to the containing named entity graph.
If two subgraphs belonging to a given named entity graph have the same
name, the types represented by the subgraphs must belong to the same
entity inheritance hierarchy, as defined in <<a765>>.

==== Fetch Annotation [[fetch]]

The `@Fetch` annotation specifies options which influence how a persistent
attribute is fetched.

[source,java]
----
@Target({FIELD, METHOD})
@Retention(RUNTIME)
@Repeatable(Fetch.Fetches.class)
public @interface Fetch {
    String graph() default "";
    String[] subgraph() default {};
    FetchType type() default FetchType.EAGER;
    int batchSize() default -1;
    CacheStoreMode cacheStoreMode() default CacheStoreMode.USE;
    CacheRetrieveMode cacheRetrieveMode() default CacheRetrieveMode.USE;
    QueryHint[] hints() default {};
}
----

`graph` :: specifies the name of an entity graph. When a graph name is
  specified, the annotated attribute is an attribute node of that graph.
  Otherwise, the annotation specifies fetching options which apply when
  the attribute is fetched without the use of an entity graph.

`subgraph` :: specifies the names of one or more named entity graphs to
  be attached as subgraphs of the entity graph named by the `graph`
  member, to the attribute node representing the annotated  association.
  The annotated attribute must be an association.

`type` :: specifies the fetching policy for the annotated attribute,
  overriding any value specified by the `fetch` member of the
  `Basic`, `OneToOne`, `ManyToOne`, `OneToMany`, `ManyToMany`, or
  `ElementCollection` annotation.

`batchSize` :: a hint specifying how many entities should be fetched
  in each request to the database. The persistence provider may ignore
  this hint.

`cacheStoreMode` :: determines whether the persistence provider should
  cache the associated entity after fetching it from the database.

`cacheRetrieveMode` :: determines whether the persistence provider is
  permitted to read the associated entity data from the cache.

`hints` :: specifies vendor-specific fetching hints. Any hint not
  recognized by a provider is ignored.

The `@Fetch` annotation may be used with or without a named entity graph.

- When the `graph` member specifies the name of a named entity graph, the
  annotated attribute is an attribute node of the named graph, and the
  fetching options specified by the annotation apply when the attribute is
  fetched using that entity graph.

- When the `graph` member is not specified, the annotation does not declare
  an attribute node of an entity graph. The fetching options specified by
  the annotation apply when the attribute is fetched without the use of an
  entity graph.

Multiple `@Fetch` annotations may be specified for a persistent attribute.

=== Annotations for Named Queries [[a13710]]

The following annotations are used to declare named queries.

Each of the following annotations can be applied to any class or interface
belonging to the persistence unit, as specified in <<a12305>>, or to a
package or module descriptor belonging to the persistence unit.

==== NamedQuery Annotation [[a13711]]

The `@NamedQuery` annotation declares a named query written in the Jakarta
Persistence query language.

[source,java]
----
@Repeatable(NamedQueries.class)
@Target({TYPE, PACKAGE, MODULE})
@Retention(RUNTIME)
@Discoverable
public @interface NamedQuery {
    String name();
    String query();
    Class<?> resultClass() default void.class;
    LockModeType lockMode() default LockModeType.NONE;
    PessimisticLockScope lockScope() default PessimisticLockScope.NORMAL;
    QueryHint[] hints() default {};
    String entityGraph() default "";
    QueryFlushMode flush() default QueryFlushMode.DEFAULT;
}
----

`name` :: assigns a name to the query, which is used to identify the
  query in calls to `EntityHandler.createNamedQuery()`.

`query` :: must specify the query string itself, written in the Jakarta
  Persistence query language. It should be a legal JPQL `select` query.
  For the backward compatibility, it is permitted to be an `update` or
  `delete` statement.

`resultClass` :: specifies the Java class of each query result.

`lockMode` :: specifies a lock mode for the entity instances in results
  returned by the query. If a lock mode other than `NONE` is specified,
  the query may only be executed within a persistence context with an
  associated active transaction.

`lockScope` :: specifies the corresponding scope for a pessimistic lock.

`hints` :: specifies query properties and hints. Properties defined by
  this specification must be observed by the provider; hints defined by
  this specification should be observed by the provider when possible.
  Vendor-specific hints that are not recognized by a provider must be
  ignored.

`entityGraph` :: may specify the name of a named entity graph interpreted
  as a load graph and applied to the entity returned by the query. The
  named `EntityGraph` may be overridden by calling
  `StatementOrTypedQuery.withEntityGraph()`.

`flush` :: controls the query flush mode defined in <<a4374>>.

When the result class is explicitly specified, either:

1. the select list of the query contains only a single item, which must
   be assignable to the result class,
2. the result class is `Object[].class`, or
3. the result class is a non-abstract class or record type with a
   constructor with the same number of parameters as the query has
   items in its select list, and the constructor parameter types must
   exactly match the types of the corresponding items in the select
   list.

In the first case, each query result is returned directly to the caller.
In the second case, each query result is packaged in an array, with the
array elements corresponding by position with the items of the query
select list. In the third case, each query result is automatically
packaged in a new instance of the result class by calling the matching
constructor.

If the result class of a named query is not specified, it defaults to
`Object` if the query has a single item in its select list or to
`Object[]` if the query has multiple items in its select list. When
generating the canonical static metamodel for a named query, the
generator is permitted to infer a more precise type from the items in
the select list.

The result class may be overridden by explicitly passing a class object
to `EntityManager.createNamedQuery(String, Class)`.

// [source,java]
// ----
//
// @Target({})
// @Retention(RUNTIME)
// public @interface QueryHint {
//     String name();
//     String value();
// }
// ----

==== NamedStatement Annotation

The `@NamedStatement` annotation declares a named statement written in
the Jakarta Persistence query language.

[source,java]
----
@Repeatable(NamedStatements.class)
@Target({TYPE, PACKAGE, MODULE})
@Retention(RUNTIME)
@Discoverable
public @interface NamedStatement {
	String name();
	String statement();
	QueryHint[] hints() default {};
}
----

`name` :: assigns a name to the statement, which is used to identify
  the statement in calls to `EntityHandler.createNamedStatement()`.

`statement` :: must specify the statement string itself, written in the
  Jakarta Persistence query language. It must be a legal JPQL `update`
  or `delete` statement.

`hints` :: specifies query properties and hints. Properties defined by
  this specification must be observed by the provider; hints defined by
  this specification should be observed by the provider when possible.
  Vendor-specific hints that are not recognized by a provider must be
  ignored.

==== NamedNativeQuery Annotation

The `@NamedNativeQuery` annotation declares a named native SQL query.

[source,java]
----
@Repeatable(NamedNativeQueries.class)
@Target({TYPE, PACKAGE, MODULE})
@Retention(RUNTIME)
@Discoverable
public @interface NamedNativeQuery {
    String name();
    String query();
    Class<?> resultClass() default void.class;
    String resultSetMapping() default "";
    EntityResult[] entities() default {};
    ConstructorResult[] classes() default {};
    ColumnResult[] columns() default {};
    QueryHint[] hints() default {};
    QueryFlushMode flush() default QueryFlushMode.DEFAULT;
}
----

`name` :: assigns a name to the query, which is used to identify the
  query in calls to `EntityHandler.createNamedQuery()`.

`query` :: must specify the query string itself, written in the native
  SQL dialect of the database. The query should return a result set.
  For backward compatibility it is permitted to be a statement which
  returns a row count.

`resultClass` :: specifies the class of each query result.

`resultSetMapping` :: specifies the name of a `@SqlResultSetMapping`
  specification declared elsewhere in metadata, as defined below in
  <<a13797>>.

`entities`, `classes`, `columns` :: define a result set mapping.
  These elements may not be used in conjunction with `resultSetMapping`.

`hints` :: specifies query properties and hints. Properties defined by
  this specification must be observed by the provider; hints defined by
  this specification should be observed by the provider when possible.
  Vendor-specific hints which are not recognized by a provider must be
  ignored.

`flush` :: controls the query flush mode defined in <<a4374>>.

When the result class is explicitly specified and the result set
mapping is not, either:

1. the result class is an entity class and is interpreted as a managed
   entity result with implicit field mappings determined by the names
   of the columns in the result set and the object/relational mapping
   of the entity,
2. the result class is the class of a basic type and the result set
   must have a single column which is interpreted as a scalar result,
3. the result class is a non-abstract class or record type with a
   constructor with the same number of parameters as the result set
   has columns, and is interpreted as a constructor result including
   all the columns of the result set, or
4. the result class is `Object[].class` and each query result is
   packaged in an array of type `Object[]`, with the array elements
   corresponding by position with the columns of the select list and
   column values obtained according to the default type mappings
   defined by the JDBC specification.

Otherwise, if a result set mapping is specified, an explicitly
specified result class must agree with the type inferred from the
result set mapping.

If the result class is not explicitly specified, then:

- it is inferred from the result set mapping, if any, or
- it defaults to `Object` if the result set has a single column or
  `Object[]` if the result set has multiple columns.

When neither result class nor result set mapping is specified,
column values are obtained according to the default type mappings
defined by the JDBC specification.

The result class may be overridden by explicitly passing a class
object to `EntityHandler.createNamedQuery(String, Class)`.

==== NamedNativeStatement Annotation

The `@NamedNativeStatement` annotation declares a named native SQL
statement that returns a row count.

[source,java]
----
@Repeatable(NamedNativeStatements.class)
@Target({TYPE, PACKAGE, MODULE})
@Retention(RUNTIME)
@Discoverable
public @interface NamedNativeStatement {
	String name();
	String statement();
	QueryHint[] hints() default {};
}
----

`name` :: assigns a name to the statement, which is used to identify
  the statement in calls to `EntityHandler.createNamedStatement()`.

`statement` :: must specify the statement string itself, written in
  the native SQL dialect of the database.

`hints` :: specifies query properties and hints. Properties defined by
  this specification must be observed by the provider; hints defined by
  this specification should be observed by the provider when possible.
  Vendor-specific hints which are not recognized by the provider must
  be ignored.

==== NamedStoredProcedureQuery Annotation [[a13759]]

The `@NamedStoredProcedureQuery` annotation declares a named stored
procedure, its parameters, and its result type.

[source,java]
----
@Repeatable(NamedStoredProcedureQueries.class)
@Target({TYPE, PACKAGE, MODULE})
@Retention(RUNTIME)
@Discoverable
public @interface NamedStoredProcedureQuery {
    String name();
    String procedureName();
    StoredProcedureParameter[] parameters() default {};
    Class<?>[] resultClasses() default {};
    String[] resultSetMappings() default {};
    QueryHint[] hints() default {};
}
----

`name` :: the name that is passed as an argument to the
  `createNamedStoredProcedureQuery()` method to create an executable
  `StoredProcedureQuery` object.

`procedureName` :: the name of the stored procedure in the database.

`parameters` :: the parameters of the stored procedure, in the order
  in which they occur in the parameter list of the stored procedure.

`resultClasses` :: specifies the class (or classes) that represent
  the results.

`resultSetMappings` :: the names of one or more result set mappings
  declared by `@SqlResultSetMapping` annotations, as defined below in
  <<a13797>>.

`hints` :: specifies query properties and hints. Properties defined by
  this specification must be observed by the provider; hints defined by
  this specification should be observed by the provider when possible.
  Vendor-specific hints which are not recognized by a provider must be
  ignored.

When the result classes are explicitly specified and the result set
mappings are not, either:

- the result class is an entity class and is interpreted as a managed
  entity result with implicit field mappings determined by the names of
  the columns in the result set and the object/relational mapping of the
  entity,
- the result class is the class of a basic type and the result set must
  have a single column which is interpreted as a scalar result,
- the result class is a non-abstract class or record type with a
  constructor with the same number of parameters as the result set has
  columns, and is interpreted as a constructor result including all the
  columns of the result set, or
- the result class is `Object[].class` and each query result is packaged
  in an array of type `Object[]`, with the array elements corresponding
  by position with the columns of the select list and column values
  obtained according to the default type mappings defined by the JDBC
  specification.

If a stored procedure returns multiple result sets, they are all mapped
using the same mechanism: either all via a set of result class mappings
or all via a set of result set mappings. The order of the specification
of these mappings must be the same as the order in which the result sets
are returned by the stored procedure invocation. If the stored procedure
returns one or more result sets and no `resultClasses` or `resultSetMappings`
element is specified, any result set will be returned as a list of type
`Object[]`.

Every parameter of a named stored procedure query must be declared using
the `@StoredProcedureParameter` annotation.

[source,java]
----
@Target({})
@Retention(RUNTIME)
public @interface StoredProcedureParameter {
    String name() default "";
    ParameterMode mode() default ParameterMode.IN;
    Class<?> type();
}
----
[source,java]
----
public enum ParameterMode {
    IN,
    INOUT,
    OUT,
    REF_CURSOR
}
----

`name` :: the name of the parameter as defined by the stored procedure
  in the database. If a `name` is not specified, it is assumed that the
  stored procedure uses positional parameters.

`mode` :: specifies whether the parameter is an `IN`, `INOUT`, `OUT`,
  or `REF_CURSOR` parameter. `REF_CURSOR` parameters are used by some
  databases to return result sets from stored procedures.

`type` :: determines the JDBC type of the parameter according to the
  default type mappings defined by the JDBC specification.

=== Annotations for SQL Result Set Mappings [[a13797]]

The `@SqlResultSetMapping` annotation specifies a mapping of the result
set of a native SQL query or stored procedure.

[source,java]
----
@Repeatable(SqlResultSetMappings.class)
@Target({TYPE, METHOD})
@Retention(RUNTIME)
@Discoverable
public @interface SqlResultSetMapping {
    String name();
    EntityResult[] entities() default {};
    ConstructorResult[] classes() default {};
    ColumnResult[] columns() default {};
}
----

`name` :: the name given to the result set mapping, which is used to
  identify it when calling methods of the `EntityManager` which create
  instances of `Query` and `StoredProcedureQuery`.

`entities`, `classes`, `columns` :: specify the mapping of the result set
  columns to entities, to constructors, and to scalar values, respectively.

==== EntityResult Annotation

[source,java]
----
@Target(METHOD)
@Retention(RUNTIME)
@Repeatable(EntityResult.EntityResults.class)
public @interface EntityResult {
    Class<?> entityClass();
    LockModeType lockMode() default LockModeType.NONE;
    FieldResult[] fields() default {};
    String discriminatorColumn() default "";
    ...
}
----

`entityClass` :: specifies the class of the result.

`lockMode` :: specifies the `LockModeType` obtained when the native
  SQL query is executed.

`fields` :: maps the columns specified in the `SELECT` list of the
  query to the properties or fields of the entity class.

`discriminatorColumn` :: specifies the column name or alias of the
  column in the `SELECT` list that determines the type of the entity
  instance.

==== FieldResult Annotation

[source,java]
----
@Target({})
@Retention(RUNTIME)
public @interface FieldResult {
    String name();
    String column();
}
----

`name` :: the name of the persistent field or property of the class.

`column` :: specifies the name of the corresponding column in the
  `SELECT` list, that is, a column alias, if applicable.

==== ConstructorResult Annotation

[source,java]
----
@Target(METHOD)
@Retention(RUNTIME)
@Repeatable(ConstructorResult.ConstructorResults.class)
public @interface ConstructorResult {
    Class<?> targetClass();
    ColumnResult[] columns() default {};
    EntityResult[] entities() default {};
    ...
}
----

`targetClass` :: specifies the class whose constructor is to be invoked.

`columns` :: specifies the mapping of columns in the `SELECT` list to
  the arguments of the intended constructor.

==== ColumnResult Annotation

[source,java]
----
@Target(METHOD)
@Retention(RUNTIME)
@Repeatable(ColumnResult.ColumnResults.class)
public @interface ColumnResult {
    String name();
    Class<?> type() default void.class;
    ...
}
----

`name` :: specifies the name of the column in the `SELECT` list.

`type` :: specifies the Java type to which the column type is mapped.
  The specified type must be one of the basic types listed in <<a486>>.
  If the `type` element is not specified, the default JDBC type mapping
  for the column type is used.

=== References to EntityManager, EntityAgent, and EntityManagerFactory

Each of the following annotations expresses a dependency on an entity
manager, entity agent, or entity manager factory, making the object
available in the environment referencing context of the annotated
managed bean. When an annotation occurs on a field or method, it
specifies that the dependency is injected by the Jakarta EE container,
as defined in <<a11464>>, <<a11465>>, and <<a11463>>.

==== PersistenceContext Annotation

The `@PersistenceContext` annotation expresses a dependency on a
container-managed entity manager and its associated persistence context.
When this annotation occurs on a method or field of a managed bean, it
declares an injection point of type `EntityManager`. When the annotation
occurs on a managed bean class, it assigns a name to the entity manager
in the environment referencing context `java:comp/env` of the containing
module.

[source,java]
----
@Target({TYPE, METHOD, FIELD})
@Retention(RUNTIME)
@Repeatable(PersistenceContexts.class)
public @interface PersistenceContext {
    String name() default "";
    String unitName() default "";
    PersistenceContextType type() default TRANSACTION;
    SynchronizationType synchronization() default SYNCHRONIZED;
    PersistenceProperty[] properties() default {};
}
----

`name` :: specifies the name at which the `EntityManager` is accessed in
  the environment referencing context. If the specified name does not
  begin with `java`, then the prefix `java:comp/env` is assumed. This
  member is not usually specified when `@PersistenceContext` annotates an
  injection point.

`unitName` :: references the name of the persistence unit as defined in
  the `persistence.xml` file. This member is optional if there is only
  one persistence unit defined by the containing module.

`type` :: specifies whether a transaction-scoped or extended persistence
  context is required, as defined in <<persistence-context-types>>. If
  the `type` element is not specified, a transaction-scoped persistence
  context is assumed.

`synchronizationType` :: specifies whether the persistence context is
  always automatically synchronized with the current transaction or
  whether the persistence context must be explicitly joined to the current
  transaction by calling the `joinTransaction()` method of `EntityManager`,
  as defined in <<synchronization-type>>.

`properties` :: specifies properties for the container or persistence provider.
  Properties defined by this specification must be observed by the provider.
  Vendor-specific properties may be included in the set of properties and are
  passed to the persistence provider by the container when the entity manager
  is created. Properties that are not recognized by a vendor must be ignored.

[source,java]
----
public enum PersistenceContextType {
    TRANSACTION,
    EXTENDED
}
----
[source,java]
----

public enum SynchronizationType {
    SYNCHRONIZED,
    UNSYNCHRONIZED
}
----
// [source,java]
// ----
// @Target({})
// @Retention(RUNTIME)
// public @interface PersistenceProperty {
//     String name();
//     String value();
// }
// ----

The `@PersistenceContexts` annotation declares one or more
`@PersistenceContext` annotations. It expresses a dependency on multiple
persistence contextsfootnote:[Multiple persistence contexts may be needed,
for example, when multiple persistence units are used.].

[source,java]
----
@Target({TYPE})
@Retention(RUNTIME)
public @interface PersistenceContexts {
    PersistenceContext[] value();
}
----

==== PersistenceAgent Annotation

The `@PersistenceAgent` annotation expresses a dependency on an
entity agent.

[source,java]
----
@Target({TYPE, METHOD, FIELD})
@Retention(RUNTIME)
@Repeatable(PersistenceAgents.class)
public @interface PersistenceAgent {
    String name() default "";
    String unitName() default "";
    PersistenceProperty[] properties() default {};
}
----

`name` :: specifies the name at which the `EntityAgent` is accessed in
  the environment referencing context. If the specified name does not
  begin with `java`, then the prefix `java:comp/env` is assumed. This
  member is not usually specified when `@PersistenceAgent` annotates
  an injection point.

`unitName` :: references the name of the persistence unit as defined in
  the `persistence.xml` file. This member is optional if there is only
  one persistence unit defined by the containing module.

`properties` :: specifies properties for the container or persistence provider.
  Properties defined by this specification must be observed by the provider.
  Vendor-specific properties may be included in the set of properties and are
  passed to the persistence provider by the container when the entity agent
  is created. Properties that are not recognized by a vendor must be ignored.

The `@PersistenceAgents` annotation declares one or more
`@PersistenceAgent` annotations. It expresses a dependency on multiple
entity agents.

[source,java]
----
@Target(TYPE)
@Retention(RUNTIME)
public @interface PersistenceAgents {
    PersistenceAgent[] value();
}
----

==== PersistenceUnit Annotation [[a13887]]

The `@PersistenceUnit` annotation expresses a dependency on an entity
manager factory and its associated persistence unit. When this
annotation occurs on a method or field of a managed bean, it declares
an injection point of type `EntityManagerFactory`. When the annotation
occurs on a managed bean class, it assigns a name to the entity manager
factory in the environment referencing context `java:comp/env` of the
containing module.

[source,java]
----
@Target({TYPE, METHOD, FIELD})
@Retention(RUNTIME)
@Repeatable(PersistenceUnits.class)
public @interface PersistenceUnit {
    String name() default "";
    String unitName() default "";
}
----

`name` :: specifies the name at which the `EntityManagerFactory` is
  accessed in the environment referencing context. If the specified name
  does not begin with `java:`, then the prefix `java:comp/env` is assumed.
  This member is not usually specified when `@PersistenceUnit` annotates
  an injection point.

`unitName` :: references the name of the persistence unit as defined in
  the `persistence.xml` file. This member is optional if there is only
  one persistence unit defined by the containing module.

The `@PersistenceUnits` annotation declares one or more
`@PersistenceUnit` annotations. It expresses a dependency on multiple
persistence unitsfootnote:[Multiple persistence units may be needed,
for example, when mapping to multiple databases.].

[source,java]
----
@Target(TYPE)
@Retention(RUNTIME)
public @interface PersistenceUnits {
    PersistenceUnit[] value();
}
----

=== Annotations for Attribute Converter Classes [[a13903]]

The `@Converter` annotation declares that the annotated class is a converter
and specifies whether the converter is applied automatically. Every converter
class must implement `AttributeConverter` and must be annotated with the
`@Converter` annotation or declared as a converter in the XML descriptor. The
target type for a converter is determined by the actual type argument of the
first type parameter of `AttributeConverter`.

[source,java]
----
@Target({TYPE})
@Retention(RUNTIME)
public @interface Converter {
    boolean autoApply() default false;
}
----

If the `autoApply` element is specified as `true`, the persistence provider
must automatically apply the converter to every mapped attribute of the
specified target type belonging to any entity in the persistence unit, except
for attributes for which conversion is overridden by means of the `@Convert`
annotation (or XML equivalent). The `@Convert` annotation is described in
<<a14398>>. The `@Convert` annotation may be used to override or disable
auto-apply conversion on a per-attribute basis.

- In determining whether a converter applies to an attribute, the provider
  must treat primitive types and wrapper types as equivalent.

- A converter never applies to id attributes, version attributes,
  relationship attributes, or to attributes explicitly annotated as
  `@Enumerated` or `@Temporal` (or designated as such via XML).

- A converter never applies to any attribute annotated
  `@Convert(disableConversion=true)` or to an attribute for which the
  `@Convert` annotation explicitly specifies a different converter.

- If `autoApply` is `false`, the converter applies only to attributes of the
  target type for which conversion is explicitly enabled via the `@Convert`
  annotation (or corresponding XML element).

- If there is more than one converter defined for the same target type, the
  `@Convert` annotation must be used to explicitly specify which converter
  applies.

=== Annotations for Static Queries

These annotations are used to declare queries associated with methods.
In the context of Jakarta Data<<a19502>>, they are used to declare repository
query methods.

The persistence provider must treat each such static query as a named query,
where the query name agrees with the convention for Javadoc links, that is:
the concatenation of the fully qualified name of the type declaring the
annotated method, with the string `#`, the name of the annotated method,
and the raw types of the method parameters, enclosed in parentheses and
separated by commas, for example,
`"org.example.Library#findBooksByTitle(java.lang.String)"`.

==== JakartaQuery Annotation

Specifies a query expressed in the Jakarta Persistence query language.
This annotation may be applied to:

- any method of any class or interface belonging to the persistence unit,
  or
- a query method of a Jakarta Data repository with an implementation backed
  by Jakarta Persistence.

[source,java]
----
@Target(METHOD)
@Retention(RUNTIME)
public @interface JakartaQuery {
    String value();
}
----

`value` :: the query, written in the Jakarta Persistence Query Language.

The semantics of this annotation are defined by its Javadoc, and in
<<canonical-metamodel>>.

The persistence provider must treat the annotation
`jakarta.data.repository.Query` as a synonym for `JakartaQuery`.

==== NativeQuery Annotation

Specifies a query expressed in the native SQL dialect of the database.
This annotation may be applied to:

- any method of any class or interface belonging to the persistence unit,
  or
- a query method of a Jakarta Data repository with an implementation backed
  by Jakarta Persistence.

[source,java]
----
@Target(METHOD)
@Retention(RUNTIME)
public @interface NativeQuery {
    String value();
}
----

`value` :: the query, written in the native SQL dialect of the database.

The semantics of this annotation are defined by its Javadoc, and in
<<canonical-metamodel>>.

==== QueryOptions Annotation

Configures options that affect the execution of a static query. This
annotation may be applied to:

- a method with a `JakartaQuery` or Jakarta Data
  `jakarta.data.repository.Query` annotation,
- a method with a `NativeQuery` annotation, or
- a Jakarta Data repository method annotated
  `jakarta.data.repository.Find`.

[source,java]
----
@Target(METHOD)
@Retention(RUNTIME)
public @interface QueryOptions {
    CacheStoreMode cacheStoreMode() default CacheStoreMode.USE;
    CacheRetrieveMode cacheRetrieveMode() default CacheRetrieveMode.USE;
    int timeout() default -1;
    QueryHint[] hints() default {};
    LockModeType lockMode() default LockModeType.NONE;
    PessimisticLockScope lockScope() default PessimisticLockScope.NORMAL;
    String entityGraph() default "";
    QueryFlushMode flush() default QueryFlushMode.DEFAULT;
}
----

`cacheStoreMode` :: the cache store mode to use. The presence of this
  annotation overrides the default cache store mode of the persistence
  context. This option applies when the query is a JPQL `select` query
  or a native query that returns a result set.

`cacheRetrieveMode` :: the cache retrieve mode to use. The presence of
  this annotation overrides the default cache retrieve mode of the
  persistence context. This option applies when the query is a JPQL
  `select` query or a native query that returns a result set.

`timeout` :: the query timeout, in milliseconds. By default, there is
  no timeout.

`hints` :: query properties and hints. Hints defined by this
  specification should be observed by the provider when possible.
  Vendor-specific hints that are not recognized by a provider must be
  ignored.

`lockMode` :: the lock mode type to use in query execution. If a
  `lockMode` other than `LockModeType.NONE` is specified, the query
  must be executed in a transaction, and the persistence context must
  be joined to the transaction. If a lock mode is explicitly specified
  for a native query, the behavior is undefined and unportable between
  persistence providers. This option applies when the query is a JPQL
  `select` query or a native query that returns a result set.

`lockScope` :: the pessimistic lock scope to use in query execution if
  a pessimistic lock mode is specified via `lockMode`. This option
  applies when the query is a JPQL `select` query or a native query
  that returns a result set.

`entityGraph` :: the name of a `@NamedEntityGraph` applied to the
  entity returned by the query. By default, no entity graph is applied.
  The named entity graph must be compatible with the entity type
  returned by the query. If the result type of the query is not an
  entity type, the behavior is undefined. The entity graph is
  interpreted as a load graph. This option applies when the query is a
  JPQL `select` query.

`flush` :: the query flush mode to use when executing the query.
