== XML Object/Relational Mapping Descriptor [[a16944]]

The XML object/relational mapping descriptor
serves as both an alternative to and an overriding mechanism for Java
language metadata annotations.

=== Use of the XML Descriptor

The XML schema for the object
relational/mapping descriptor is contained in <<a17175>>. The root element of this
schema is the _entity-mappings_ element. The absence or present of the
_xml-mapping-metadata-complete_ subelement contained in the
_persistence-unit-defaults_ subelement of the _entity-mappings_ element
controls whether the XML object/relational mapping descriptor is used to
selectively override annotation values or whether it serves as a
complete alternative to Java language metadata annotations.

If the _xml-mapping-metadata-complete_
subelement is specified, the complete set of mapping metadata for the
persistence unit is contained in the XML mapping files for the
persistence unit, and any persistence annotations on the classes are
ignored.

If _xml-mapping-metadata-complete_ is
specified and XML elements are omitted, the default values apply. These
default values are the same as the corresponding defaults when
annotations are used, except in the cases specified in <<a16953>> below. When the
_xml-mapping-metadata-complete_ element is specified, any
_metadata-complete_ attributes specified within the _entity_,
_mapped-superclass_, and _embeddable_ elements are ignored.

If the _xml-mapping-metadata-complete_
subelement is not specified, the XML descriptor overrides the values set
or defaulted by the use of annotations, as described below.

The mapping files used by the application
developer must conform to the XML schema defined in <<a17175>> or to the object/relational
mapping schema defined in a previous version of this specification
<<a19493>>, <<a19501>>.

The Java Persistence persistence provider
must support use of older versions of the object/relational mapping
schema as well as the object/relational mapping schema defined in
<<a17175>>, whether singly or
in combination when multiple mapping files are used.

=== XML Overriding Rules [[a16953]]

This section defines the rules that apply
when the XML descriptor is used to override annotations, and the rules
pertaining to the interaction of XML elements specified as subelements
of the _persistence-unit-defaults_, _entity-mappings_, _entity_,
_mapped-superclass_, and _embeddable_ elements.

==== persistence-unit-defaults Subelements

===== schema

The _schema_ subelement applies to all
entities, tables, secondary tables, join tables, collection tables,
table generators, and sequence generators in the persistence unit.

The _schema_ subelement is overridden by any
_schema_ subelement of the _entity-mappings_ element; any _schema_
element explicitly specified in the _Table_ or _SecondaryTable_
annotation on an entity or any _schema_ attribute on any _table_ or
_secondary-table_ subelement defined within an _entity_ element; any
_schema_ element explicitly specified in a _TableGenerator_ annotation
or _table-generator_ subelement; any _schema_ element explicitly
specified in a _SequenceGenerator_ annotation or _sequence-generator_
subelement; any _schema_ element explicitly specified in a _JoinTable_
annotation or _join-table_ subelement; and any _schema_ element
explicitly specified in a _CollectionTable_ annotation or
_collection-table_ subelement.

===== catalog

The _catalog_ subelement applies to all
entities, tables, secondary tables, join tables, collection tables,
table generators, and sequence generators in the persistence unit.

The _catalog_ subelement is overridden by any
_catalog_ subelement of the _entity-mappings_ element; any _catalog_
element explicitly specified in the _Table_ or _SecondaryTable_
annotation on an entity or any _catalog_ attribute on any _table_ or
_secondary-table_ subelement defined within an _entity_ XML element; any
_catalog_ element explicitly specified in a _TableGenerator_ annotation
or _table-generator_ subelement; any _catalog_ element explicitly
specified in a _SequenceGenerator_ annotation or _sequence-generator_
subelement; any _catalog_ element explicitly specified in a _JoinTable_
annotation or _join-table_ subelement; and any _catalog_ element
explicitly specified in a _CollectionTable_ annotation or
_collection-table_ subelement.

===== delimited-identifiers

The _delimited-identifiers_ subelement
applies to the naming of database objects, as described in <<a988>>. It
specifies that all database table-, schema-, and column-level
identifiers in use for the persistence unit be treated as delimited
identifiers.

The _delimited-identifiers_ subelement cannot
be overridden in this release.

===== access

The _access_ subelement applies to all
managed classes in the persistence unit.

The _access_ subelement is overridden by the
use of any annotations specifying mapping information on the fields or
properties of the entity class; by any _Access_ annotation on the entity
class, mapped superclass, or embeddable class; by any _access_
subelement of the _entity-mappings_ element; by any _Access_ annotation
on a field or property of an entity class, mapped superclass, or
embeddable class; by any _access_ attribute defined within an _entity_,
_mapped-superclass_, or _embeddable_ XML element, or by any _access_
attribute defined within an _id_, _embedded-id_, _version_, _basic_,
_embedded_, _many-to-one_, _one-to-one_, _one-to-many_,
_many-to-many_, or _element-collection_ element.

===== cascade-persist

The _cascade-persist_ subelement applies to
all relationships in the persistence unit.

Specifying this subelement adds the cascade
persist option to all relationships in addition to any settings
specified in annotations or XML.

The _cascade-persist_ subelement cannot be
overridden in this release.

[NOTE]
====
The ability to override the _cascade-persist_
of the _persistence-unit-defaults_ element will be added in a future
release of this specification.
====

===== entity-listeners

The _entity-listeners_ subelement defines
default entity listeners for the persistence unit. These entity
listeners are called before any other entity listeners for an entity
unless the entity listener order is overridden within a
_mapped-superclass_ or _entity_ element, or the
_ExcludeDefaultListeners_ annotation is present on the entity or mapped
superclass or the _exclude-default-listeners_ subelement is specified
within the corresponding _entity_ or _mapped-superclass_ XML element.

==== Other Subelements of the entity-mappings element

===== package

The _package_ subelement specifies the
package of the classes listed within the subelements and attributes of
the same mapping file only. The _package_ subelement is overridden if
the fully qualified class name is specified for a class and the two
disagree.

===== schema

The _schema_ subelement applies only to the
entities, tables, secondary tables, join tables, collection tables,
table generators, and sequence generators listed within the same mapping
file.

The _schema_ subelement is overridden by any
_schema_ element explicitly specified in the _Table_, _SecondaryTable_
, _JoinTable_, or _CollectionTable_ annotation on an entity listed
within the mapping file or any _schema_ attribute on any _table_ or
_secondary-table_ subelement defined within the _entity_ element for
such an entity, or by any _schema_ attribute on any _join-table_ or
_collection-table_ subelement of an attribute defined within the
_attributes_ subelement of the _entity_ element for such an entity, or
by the _schema_ attribute of any _table-generator_ or
_sequence-generator_ element within the mapping file.

===== catalog

The _catalog_ subelement applies only to the
entities, tables, secondary tables, join tables, collection tables,
table generators, and sequence generators listed within the same mapping
file.

The _catalog_ subelement is overridden by any
_catalog_ element explicitly specified in the _Table_, _SecondaryTable_
, _JoinTable_, or _CollectionTable_ annotation on an entity listed
within the mapping file or any _catalog_ attribute on any _table_ or
_secondary-table_ subelement defined within the _entity_ element for
such an entity, or by any _catalog_ attribute on any _join-table_ or
_collection-table_ subelement of an attribute defined within the
_attributes_ subelement of the _entity_ element for such an entity, or
by the _catalog_ attribute of any _table-generator_ or
_sequence-generator_ element within the mapping file.

===== access

The _access_ subelement applies to the
managed classes listed within the same mapping file.

The _access_ subelement is overridden by the
use of any annotations specifying mapping information on the fields or
properties of the entity class; by any _Access_ annotation on the entity
class, mapped superclass, or embeddable class; by any _Access_
annotation on a field or property of an entity class, mapped superclass,
or embeddable class; by any _access_ attribute defined within an
_entity_, _mapped-superclass_, or _embeddable_ XML element, or by any
_access_ attribute defined within an _id_, _embedded-id_, _version_,
_basic_, _embedded_, _many-to-one_, _one-to-one_, _one-to-many_,
_many-to-many_, or _element-collection_ element.

===== sequence-generator

The generator defined by the
_sequence-generator_ subelement applies to the persistence unit. It is
undefined if multiple mapping files for the persistence unit contain
generators of the same name.

The generator defined is added to any
generators defined in annotations. If a generator of the same name is
defined in annotations, the generator defined by this subelement
overrides that definition.

===== table-generator

The generator defined by the
_table-generator_ subelement applies to the persistence unit. It is
undefined if multiple mapping files for the persistence unit contain
generators of the same name.

The generator defined is added to any
generators defined in annotations. If a generator of the same name is
defined in annotations, the generator defined by this subelement
overrides that definition.

===== named-query

The named query defined by the _named-query_
subelement applies to the persistence unit. It is undefined if multiple
mapping files for the persistence unit contain named queries of the same
name.

The named query defined is added to the named
queries defined in annotations. If a named query of the same name is
defined in annotations, the named query defined by this subelement
overrides that definition.

===== named-native-query

The named native query defined by the
_named-native-query_ subelement applies to the persistence unit. It is
undefined if multiple mapping files for the persistence unit contain
named queries of the same name.

The named native query defined is added to
the named native queries defined in annotations. If a named query of the
same name is defined in annotations, the named query defined by this
subelement overrides that definition.

===== named-stored-procedure-query

The named stored procedure query defined by
the _named-stored-procedure-query_ subelement applies to the persistence
unit. It is undefined if multiple mapping files for the persistence unit
contain named stored procedure queries of the same name.

The named stored procedure query defined is
added to the named stored procedure queries defined in annotations. If a
named stored procedure query of the same name is defined in annotations,
the named stored procedure query defined by this subelement overrides
that definition.

===== sql-result-set-mapping

The SQL result set mapping defined by the
_sql-result-set-mapping_ subelement applies to the persistence unit. It
is undefined if multiple mapping files for the persistence unit contain
SQL result set mappings of the same name.

The SQL result set mapping defined is added
to the SQL result set mappings defined in annotations. If a SQL result
set mapping of the same name is defined in annotations, the SQL result
set mapping defined by this subelement overrides that definition.

===== entity

The _entity_ subelement defines an entity of
the persistence unit. It is undefined if multiple mapping files for the
persistence unit contain entries for the same entity.

The entity class may or may not have been
annotated as _Entity_. The subelements and attributes of the _entity_
element override as specified in <<a17017>>.

===== mapped-superclass

The _mapped-superclass_ subelement defines a
mapped superclass of the persistence unit. It is undefined if multiple
mapping files for the persistence unit contain entries for the same
mapped superclass.

The mapped superclass may or may not have
been annotated as _MappedSuperclass_. The subelements and attributes of
the _mapped-superclass_ element override as specified in <<a17106>>.

===== embeddable

The _embeddable_ subelement defines an
embeddable class of the persistence unit. It is undefined if multiple
mapping files for the persistence unit contain entries for the same
embeddable class.

The _embeddable_ class may or may not have
been annotated as _Embeddable_. The subelements and attributes of the
_embeddable_ element override as specified in <<a17150>>.

===== converter

The converter defined by the _converter_
subelement applies to the persistence unit. It is undefined if multiple
mapping files for the persistence unit contain converters for the same
target type.

The converter defined is added to the
converters defined in annotations. If a converter for the same target
type is defined in annotations, the converter defined by this subelement
overrides that definition.

==== entity Subelements and Attributes [[a17017]]

These apply only to the entity for which they
are subelements or attributes, unless otherwise specified below.

===== metadata-complete

If the _metadata-complete_ attribute of the
_entity_ element is specified as _true_, any annotations on the entity
class (and its fields and properties) are ignored. When
_metadata-complete_ is specified as _true_ and XML attributes or
sub-elements of the _entity_ element are omitted, the default values for
those attributes and elements are applied.

===== access

The _access_ attribute defines the access
type for the entity. The _access_ attribute overrides any access type
specified by the _persistence-unit-defaults_ element or
_entity-mappings_ element for the given entity. The access type for a
field or property of the entity may be overridden by specifying by
overriding the mapping for that field or property using the appropriate
XML subelement, as described in <<a17082>> below.

Caution must be exercised in overriding an
access type that was specified or defaulted using annotations, as doing
so may cause applications to break.

===== cacheable

The _cacheable_ attribute defines whether the
entity should be cached or must not be cached when the
_shared-cache-mode_ element of the _persistence.xml_ file is specified
as _ENABLE_SELECTIVE_ or _DISABLE_SELECTIVE_. If the _Cacheable_
annotation was specified for the entity, its value is overridden by this
attribute. The value of the _cacheable_ attribute is inherited by
subclasses (unless otherwise overridden for a subclass by the
_Cacheable_ annotation or _cacheable_ XML attribute).

===== name

The name attribute defines the entity name.
The _name_ attribute overrides the value of the entity name defined by
the _name_ element of the _Entity_ annotation (whether explicitly
specified or defaulted). Caution must be exercised in overriding the
entity name, as doing so may cause applications to break.

===== table

The _table_ subelement overrides any _Table_
annotation (including defaulted _Table_ values) on the entity. If a
_table_ subelement is present, and attributes or subelements of that
_table_ subelement are not explicitly specified, their default values
are applied.

===== secondary-table

The _secondary-table_ subelement overrides
all _SecondaryTable_ and _SecondaryTables_ annotations (including
defaulted _SecondaryTable_ values) on the entity. If a _secondary-table_
subelement is present, and attributes or subelements of that _secondary_
- _table_ subelement are not explicitly specified, their default values
are applied.

===== primary-key-join-column

The _primary-key-join-column_ subelement of
the entity element specifies a primary key column that is used to join
the table of an entity subclass to the primary table for the entity when
the joined strategy is used. The _primary-key-join-column_ subelement
overrides all _PrimaryKeyJoinColumn_ and _PrimaryKeyJoinColumns_
annotations (including defaulted _PrimaryKeyJoinColumn_ values) on the
entity. If a _primary-key-join-column_ subelement is present, and
attributes or subelements of that _primary-key-join-column_ subelement
are not explicitly specified, their default values are applied.

===== id-class

The _id-class_ subelement overrides any
_IdClass_ annotation specified on the entity.

===== inheritance

The _inheritance_ subelement overrides any
_Inheritance_ annotation (including defaulted _Inheritance_ values) on
the entity. If an _inheritance_ subelement is present, and the
_strategy_ attribute is not explicitly specified, its default value is
applied.

This element applies to the entity and its
subclasses (unless otherwise overridden for a subclass by an annotation
or XML element).

Support for the combination of inheritance
strategies is not required by this specification. Portable applications
should use only a single inheritance strategy within an entity
hierarchy.

===== discriminator-value

The _discriminator-value_ subelement
overrides any _DiscriminatorValue_ annotations (including defaulted
_DiscriminatorValue_ values) on the entity.

===== discriminator-column

The _discriminator-column_ subelement
overrides any _DiscriminatorColumn_ annotation (including defaulted
_DiscriminatorColumn_ values) on the entity. If a _discriminator-column_
subelement is present, and attributes of that _discriminator-column_
subelement are not explicitly specified, their default values are
applied.

This element applies to the entity and its
subclasses (unless otherwise overridden for a subclass by an annotation
or XML element).

===== sequence-generator

The generator defined by the
_sequence-generator_ subelement is added to any generators defined in
annotations and any other generators defined in XML. If a generator of
the same name is defined in annotations, the generator defined by this
subelement overrides that definition. If a _sequence-generator_
subelement is present, and attributes or subelements of that
_sequence-generator_ subelement are not explicitly specified, their
default values are applied.

The generator defined by the
_sequence-generator_ subelement applies to the persistence unit. It is
undefined if multiple mapping files for the persistence unit contain
generators of the same name.

===== table-generator

The generator defined by the
_table-generator_ subelement is added to any generators defined in
annotations and any other generators defined in XML. If a generator of
the same name is defined in annotations, the generator defined by this
subelement overrides that definition. If a _table-generator_ subelement
is present, and attributes or subelements of that _table-generator_
subelement are not explicitly specified, their default values are
applied.

The generator defined by the
_table-generator_ subelement applies to the persistence unit. It is
undefined if multiple mapping files for the persistence unit contain
generators of the same name.

===== attribute-override

The _attribute-override_ subelement is
additive to any _AttributeOverride_ or _AttributeOverrides_ annotations
on the entity. It overrides any _AttributeOverride_ elements for the
same attribute name. If an _attribute-override_ subelement is present,
and attributes or subelements of that _attribute-override_ subelement
are not explicitly specified, their default values are applied.

===== association-override

The _association-override_ subelement is
additive to any _AssociationOverride_ or _AssociationOverrides a_
nnotations on the entity. It overrides any _AssociationOverride_
elements for the same attribute name. If an _association-override_
subelement is present, and attributes or subelements of that
_association-override_ subelement are not explicitly specified, their
default values are applied.

===== convert

The _convert_ subelement is additive to any
_Convert_ or _Converts_ annotations on the entity. It overrides any
_Convert_ annotation for the same attribute name. If a _convert_
subelement is present, and attributes or subelements of that _convert_
subelement are not explicitly specified, their default values are
applied.

===== named-entity-graph

The _named-entity-graph_ subelement is
additive to any _NamedEntityGraph_ annotations on the entity. It
overrides any _NamedEntityGraph_ annotation with the same name.

===== named-query

The named query defined by the _named-query_
subelement is added to any named queries defined in annotations, and any
other named queries defined in XML. If a named query of the same name is
defined in annotations, the named query defined by this subelement
overrides that definition. If a _named-query_ subelement is present, and
attributes or subelements of that _named-query_ subelement are not
explicitly specified, their default values are applied.

The named query defined by the _named-query_
subelement applies to the persistence unit. It is undefined if multiple
mapping files for the persistence unit contain named queries of the same
name.

===== named-native-query

The named query defined by the
_named-native-query_ subelement is added to any named queries defined in
annotations, and any other named queries defined in XML. If a named
query of the same name is defined in annotations, the named query
defined by this subelement overrides that definition. If a
_named-native-query_ subelement is present, and attributes or
subelements of that _named-native-query_ subelement are not explicitly
specified, their default values are applied.

The named native query defined by the
_named-native-query_ subelement applies to the persistence unit. It is
undefined if multiple mapping files for the persistence unit contain
named queries of the same name.

===== named-stored-procedure-query

The named stored procedure query defined by
the _named-stored-procedure-query_ subelement is added to any named
stored procedure queries defined in annotations, and any other named
stored procedure queries defined in XML. If a named stored procedure
query of the same name is defined in annotations, the named stored
procedure query defined by this subelement overrides that definition. If
a _named-stored-procedure-query_ subelement is present, and attributes
or subelements of that _named-stored-procedure-query_ subelement are not
explicitly specified, their default values are applied.

The named stored procedure query defined by
the _named-stored-procedure-query_ subelement applies to the persistence
unit. It is undefined if multiple mapping files for the persistence unit
contain named stored procedure queries of the same name.

===== sql-result-set-mapping

The SQL result set mapping defined by the
_sql-result-set-mapping_ is added to the SQL result set mappings defined
in annotations, and any other SQL result set mappings defined in XML. If
a SQL result set mapping of the same name is defined in annotations, the
SQL result set mapping defined by this subelement overrides that
definition. If a _sql-result-set-mapping_ subelement is present, and
attributes or subelements of that _sql-result-set-mapping_ subelement
are not explicitly specified, their default values are applied.

The SQL result set mapping defined by the
_sql-result-set-mapping_ subelement applies to the persistence unit. It
is undefined if multiple mapping files for the persistence unit contain
SQL result set mappings of the same name.

===== exclude-default-listeners

The _exclude-default-listeners_ subelement
applies whether or not the _ExcludeDefaultListeners_ annotation was
specified on the entity.

This element causes the default entity
listeners to be excluded for the entity and its subclasses.

===== exclude-superclass-listeners

The _exclude-superclass-listeners_ subelement
applies whether or not the _ExcludeSuperclassListeners_ annotation was
specified on the entity.

This element causes any superclass listeners
to be excluded for the entity and its subclasses.

===== entity-listeners

The _entity-listeners_ subelement overrides
any _EntityListeners_ annotation on the entity.

These listeners apply to the entity and its
subclasses unless otherwise excluded.

===== pre-persist, post-persist, pre-remove, post-remove, pre-update, post-update, post-load

These subelements override any lifecycle
callback methods defined by the corresponding annotations on the entity.

===== attributes [[a17082]]

The _attributes_ element groups the mapping
subelements for the fields and properties of the entity. It may be
sparsely populated to include only a subset of the fields and
properties. If the value of _metadata-complete_ is _true_, the
remainder of the attributes will be defaulted according to the default
rules. If _metadata-complete_ is not specified, or is _false_, the
mappings for only those properties and fields that are explicitly
specified will be overridden.

====== id

The _id_ subelement overrides the mapping for
the specified field or property. If an _id_ subelement is present, and
attributes or subelements of that _id_ subelement are not explicitly
specified, their default values are applied.

====== embedded-id

The _embedded-id_ subelement overrides the
mapping for the specified field or property. If an _embedded-id_
subelement is present, and attributes or subelements of that
_embedded-id_ subelement are not explicitly specified, their default
values are applied.

====== basic

The _basic_ subelement overrides the mapping
for the specified field or property. If a _basic_ subelement is present,
and attributes or subelements of that _basic_ subelement are not
explicitly specified, their default values are applied.

====== version

The _version_ subelement overrides the
mapping for the specified field or property. If a _version_ subelement
is present, and attributes or subelements of that _version_ subelement
are not explicitly specified, their default values are applied.

====== many-to-one

The _many-to-one_ subelement overrides the
mapping for the specified field or property. If a _many-to-one_
subelement is present, and attributes or subelements of that
_many-to-one_ subelement are not explicitly specified, their default
values are applied.

====== one-to-many

The _one-to-many_ subelement overrides the
mapping for the specified field or property. If a _one-to-many_
subelement is present, and attributes or subelements of that
_one-to-many_ subelement are not explicitly specified, their default
values are applied.

====== one-to-one

The _one-to-one_ subelement overrides the
mapping for the specified field or property. If a _one-to-one_
subelement is present, and attributes or subelements of that
_one-to-one_ subelement are not explicitly specified, their default
values are applied.

====== many-to-many

The _many-to-many_ subelement overrides the
mapping for the specified field or property. If a _many-to-many_
subelement is present, and attributes or subelements of that
_many-to-many_ subelement are not explicitly specified, their default
values are applied.

====== element-collection

The _element-collection_ subelement overrides
the mapping for the specified field or property. If an
_element-collection_ subelement is present, and attributes or
subelements of that _element-collection_ subelement are not explicitly
specified, their default values are applied.

====== embedded

The _embedded_ subelement overrides the
mapping for the specified field or property. If an _embedded_ subelement
is present, and attributes or subelements of that _embedded_ subelement
are not explicitly specified, their default values are applied.

====== transient

The _transient_ subelement overrides the
mapping for the specified field or property.

==== mapped-superclass Subelements and Attributes [[a17106]]

These apply only to the mapped-superclass for
which they are subelements or attributes, unless otherwise specified
below.

===== metadata-complete

If the _metadata-complete_ attribute of the
_mapped-superclass_ element is specified as _true_, any annotations on
the mapped superclass (and its fields and properties) are ignored. When
_metadata-complete_ is specified as _true_ and attributes or
sub-elements of the _mapped-superclass_ element are omitted, the default
values for those attributes and elements are applied.

===== access

The _access_ attribute defines the access
type for the mapped superclass. The _access_ attribute overrides any
access type specified by the _persistence-unit-defaults_ element or
_entity-mappings_ element for the given mapped superclass. The access
type for a field or property of the mapped superclass may be overridden
by specifying by overriding the mapping for that field or property using
the appropriate XML subelement, as described in <<a17126>> below.

Caution must be exercised in overriding an
access type that was specified or defaulted using annotations, as doing
so may cause applications to break.

===== id-class

The _id-class_ subelement overrides any
_IdClass_ annotation specified on the mapped superclass.

===== exclude-default-listeners

The _exclude-default-listeners_ subelement
applies whether or not the _ExcludeDefaultListeners_ annotation was
specified on the mapped superclass.

This element causes the default entity
listeners to be excluded for the mapped superclass and its subclasses.

===== exclude-superclass-listeners

The _exclude-superclass-listeners_ subelement
applies whether or not the _ExcludeSuperclassListeners_ annotation was
specified on the mapped superclass.

This element causes any superclass listeners
to be excluded for the mapped superclass and its subclasses.

===== entity-listeners

The _entity-listeners_ subelement overrides
any _EntityListeners_ annotation on the mapped superclass.

These listeners apply to the mapped
superclass and its subclasses unless otherwise excluded.

===== pre-persist, post-persist, pre-remove, post-remove, pre-update, post-update, post-load

These subelements override any lifecycle
callback methods defined by the corresponding annotations on the mapped
superclass.

===== [[a17126]]attributes

The _attributes_ element groups the mapping
subelements for the fields and properties defined by the mapped
superclass. It may be sparsely populated to include only a subset of the
fields and properties. If the value of _metadata-complete_ is _true_,
the remainder of the attributes will be defaulted according to the
default rules. If _metadata-complete_ is not specified, or is _false_,
the mappings for only those properties and fields that are explicitly
specified will be overridden.

====== id

The _id_ subelement overrides the mapping for
the specified field or property. If an _id_ subelement is present, and
attributes or subelements of that _id_ subelement are not explicitly
specified, their default values are applied.

====== embedded-id

The _embedded-id_ subelement overrides the
mapping for the specified field or property. If an _embedded-id_
subelement is present, and attributes or subelements of that
_embedded-id_ subelement are not explicitly specified, their default
values are applied.

====== basic

The _basic_ subelement overrides the mapping
for the specified field or property. If a _basic_ subelement is present,
and attributes or subelements of that _basic_ subelement are not
explicitly specified, their default values are applied.

====== version

The _version_ subelement overrides the
mapping for the specified field or property. If a _version_ subelement
is present, and attributes or subelements of that _version_ subelement
are not explicitly specified, their default values are applied.

====== many-to-one

The _many-to-one_ subelement overrides the
mapping for the specified field or property. If a _many-to-one_
subelement is present, and attributes or subelements of that
_many-to-one_ subelement are not explicitly specified, their default
values are applied.

====== one-to-many

The _one-to-many_ subelement overrides the
mapping for the specified field or property. If a _one-to-many_
subelement is present, and attributes or subelements of that
_one-to-many_ subelement are not explicitly specified, their default
values are applied.

====== one-to-one

The _one-to-one_ subelement overrides the
mapping for the specified field or property. If a _one-to-one_
subelement is present, and attributes or subelements of that
_one-to-one_ subelement are not explicitly specified, their default
values are applied.

====== many-to-many

The _many-to-many_ subelement overrides the
mapping for the specified field or property. If a _many-to-many_
subelement is present, and attributes or subelements of that
_many-to-many_ subelement are not explicitly specified, their default
values are applied.

====== element-collection

The _element-collection_ subelement overrides
the mapping for the specified field or property. If an
_element-collection_ subelement is present, and attributes or
subelements of that _element-collection_ subelement are not explicitly
specified, their default values are applied.

====== embedded

The _embedded_ subelement overrides the
mapping for the specified field or property. If an _embedded_ subelement
is present, and attributes or subelements of that _embedded_ subelement
are not explicitly specified, their default values are applied.

====== transient

The _transient_ subelement overrides the
mapping for the specified field or property.

==== embeddable Subelements and Attributes [[a17150]]

These apply only to the embeddable for which
they are subelements or attributes.

===== metadata-complete

If the _metadata-complete_ attribute of the
_embeddable_ element is specified as _true_, any annotations on the
embeddable class (and its fields and properties) are ignored. When
_metadata-complete_ is specified as _true_ and attributes and
sub-elements of the _embeddable_ element are omitted, the default values
for those attributes and elements are applied.

===== access

The _access_ attribute defines the access
type for the embeddable class. The _access_ attribute overrides any
access type specified by the _persistence-unit-defaults_ element or
_entity-mappings_ element for the given embeddable class. The access
type for a field or property of the embeddable class may be overridden
by specifying by overriding the mapping for that field or property using
the appropriate XML subelement, as described in <<a17157>> below.

Caution must be exercised in overriding an
access type that was specified or defaulted using annotations, as doing
so may cause applications to break.

===== attributes [[a17157]]

The _attributes_ element groups the mapping
subelements for the fields and properties defined by the embeddable
class. It may be sparsely populated to include only a subset of the
fields and properties. If the value of _metadata-complete_ is _true_,
the remainder of the attributes will be defaulted according to the
default rules. If _metadata-complete_ is not specified, or is _false_,
the mappings for only those properties and fields that are explicitly
specified will be overridden.

====== basic

The _basic_ subelement overrides the mapping
for the specified field or property. If a _basic_ subelement is present,
and attributes or subelements of that _basic_ subelement are not
explicitly specified, their default values are applied.

====== many-to-one

The _many-to-one_ subelement overrides the
mapping for the specified field or property. If a _many-to-one_
subelement is present, and attributes or subelements of that
_many-to-one_ subelement are not explicitly specified, their default
values are applied.

====== one-to-many

The _one-to-many_ subelement overrides the
mapping for the specified field or property. If a _one-to-many_
subelement is present, and attributes or subelements of that
_one-to-many_ subelement are not explicitly specified, their default
values are applied.

====== one-to-one

The _one-to-one_ subelement overrides the
mapping for the specified field or property. If a _one-to-one_
subelement is present, and attributes or subelements of that
_one-to-one_ subelement are not explicitly specified, their default
values are applied.

====== many-to-many

The _many-to-many_ subelement overrides the
mapping for the specified field or property. If a _many-to-many_
subelement is present, and attributes or subelements of that
_many-to-many_ subelement are not explicitly specified, their default
values are applied.

====== element-collection

The _element-collection_ subelement overrides
the mapping for the specified field or property. If an
_element-collection_ subelement is present, and attributes or
subelements of that _element-collection_ subelement are not explicitly
specified, their default values are applied.

====== embedded

The _embedded_ subelement overrides the
mapping for the specified field or property. If an _embedded_ subelement
is present, and attributes or subelements of that _embedded_ subelement
are not explicitly specified, their default values are applied.

====== transient

The _transient_ subelement overrides the
mapping for the specified field or property.

=== XML Schema [[a17175]]

This section provides the XML
object/relational mapping schema for use with the persistence API.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<!-- persistence.xml schema -->
<xsd:schema targetNamespace="https://xmlns.jakarta.ee/xml/ns/persistence"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:persistence="https://xmlns.jakarta.ee/xml/ns/persistence"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  version="3.0">

  <xsd:annotation>
    <xsd:documentation>
      @(#)persistence_3_0.xsd 3.0  February 10, 2020
    </xsd:documentation>
  </xsd:annotation>

  <xsd:annotation>
    <xsd:documentation>

  Copyright (c) 2008, 2020 Oracle and/or its affiliates. All rights reserved.

  This program and the accompanying materials are made available under the
  terms of the Eclipse Public License v. 2.0 which is available at
  http://www.eclipse.org/legal/epl-2.0,
  or the Eclipse Distribution License v. 1.0 which is available at
  http://www.eclipse.org/org/documents/edl-v10.php.

  SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause

    </xsd:documentation>
  </xsd:annotation>

   <xsd:annotation>
     <xsd:documentation><![CDATA[

     This is the XML Schema for the persistence configuration file.
     The file must be named "META-INF/persistence.xml" in the
     persistence archive.

     Persistence configuration files must indicate
     the persistence schema by using the persistence namespace:

     https://xmlns.jakarta.ee/xml/ns/persistence

     and indicate the version of the schema by
     using the version element as shown below:

      <persistence xmlns="https://xmlns.jakarta.ee/xml/ns/persistence"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://xmlns.jakarta.ee/xml/ns/persistence
          https://xmlns.jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
        version="3.0">
          ...
      </persistence>

    ]]></xsd:documentation>
  </xsd:annotation>

  <xsd:simpleType name="versionType">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="[0-9]+(\.[0-9]+)*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <!-- **************************************************** -->

  <xsd:element name="persistence">
    <xsd:complexType>
      <xsd:sequence>

        <!-- **************************************************** -->

        <xsd:element name="persistence-unit"
                     minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:annotation>
              <xsd:documentation>

                Configuration of a persistence unit.

              </xsd:documentation>
            </xsd:annotation>
            <xsd:sequence>

            <!-- **************************************************** -->

              <xsd:element name="description" type="xsd:string"
                           minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>

                    Description of this persistence unit.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="provider" type="xsd:string"
                           minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>

                    Provider class that supplies EntityManagers for this
                    persistence unit.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="jta-data-source" type="xsd:string"
                           minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>

                    The container-specific name of the JTA datasource to use.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="non-jta-data-source" type="xsd:string"
                           minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>

                    The container-specific name of a non-JTA datasource to use.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="mapping-file" type="xsd:string"
                           minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>

                    File containing mapping information. Loaded as a resource
                    by the persistence provider.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="jar-file" type="xsd:string"
                           minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>

                    Jar file that is to be scanned for managed classes.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="class" type="xsd:string"
                           minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>

                    Managed class to be included in the persistence unit and
                    to scan for annotations.  It should be annotated
                    with either @Entity, @Embeddable or @MappedSuperclass.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="exclude-unlisted-classes" type="xsd:boolean"
                           default="true" minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>

                    When set to true then only listed classes and jars will
                    be scanned for persistent classes, otherwise the
                    enclosing jar or directory will also be scanned.
                    Not applicable to Java SE persistence units.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="shared-cache-mode"
                           type="persistence:persistence-unit-caching-type"
                           minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>

                    Defines whether caching is enabled for the
                    persistence unit if caching is supported by the
                    persistence provider. When set to ALL, all entities
                    will be cached. When set to NONE, no entities will
                    be cached. When set to ENABLE_SELECTIVE, only entities
                    specified as cacheable will be cached. When set to
                    DISABLE_SELECTIVE, entities specified as not cacheable
                    will not be cached. When not specified or when set to
                    UNSPECIFIED, provider defaults may apply.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>

              <!-- **************************************************** -->

              <xsd:element name="validation-mode"
                           type="persistence:persistence-unit-validation-mode-type"
                           minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>

                    The validation mode to be used for the persistence unit.

                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>


              <!-- **************************************************** -->

              <xsd:element name="properties" minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>

                    A list of standard and vendor-specific properties
                    and hints.

                  </xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="property"
                                 minOccurs="0" maxOccurs="unbounded">
                      <xsd:annotation>
                        <xsd:documentation>
                          A name-value pair.
                        </xsd:documentation>
                      </xsd:annotation>
                      <xsd:complexType>
                        <xsd:attribute name="name" type="xsd:string"
                                       use="required"/>
                        <xsd:attribute name="value" type="xsd:string"
                                       use="required"/>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>

            </xsd:sequence>

            <!-- **************************************************** -->

            <xsd:attribute name="name" type="xsd:string" use="required">
              <xsd:annotation>
                <xsd:documentation>

                  Name used in code to reference this persistence unit.

                </xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>

            <!-- **************************************************** -->

            <xsd:attribute name="transaction-type"
                           type="persistence:persistence-unit-transaction-type">
              <xsd:annotation>
                <xsd:documentation>

                  Type of transactions used by EntityManagers from this
                  persistence unit.

                </xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>

          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="version" type="persistence:versionType"
                     fixed="3.0" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <!-- **************************************************** -->

  <xsd:simpleType name="persistence-unit-transaction-type">
    <xsd:annotation>
      <xsd:documentation>

        public enum PersistenceUnitTransactionType {JTA, RESOURCE_LOCAL};

      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:token">
      <xsd:enumeration value="JTA"/>
      <xsd:enumeration value="RESOURCE_LOCAL"/>
    </xsd:restriction>
  </xsd:simpleType>

<!-- **************************************************** -->

  <xsd:simpleType name="persistence-unit-caching-type">
    <xsd:annotation>
      <xsd:documentation>

        public enum SharedCacheMode { ALL, NONE, ENABLE_SELECTIVE, DISABLE_SELECTIVE, UNSPECIFIED};

      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:token">
      <xsd:enumeration value="ALL"/>
      <xsd:enumeration value="NONE"/>
      <xsd:enumeration value="ENABLE_SELECTIVE"/>
      <xsd:enumeration value="DISABLE_SELECTIVE"/>
      <xsd:enumeration value="UNSPECIFIED"/>
    </xsd:restriction>
  </xsd:simpleType>

<!-- **************************************************** -->

  <xsd:simpleType name="persistence-unit-validation-mode-type">
    <xsd:annotation>
      <xsd:documentation>

        public enum ValidationMode { AUTO, CALLBACK, NONE};

      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:token">
      <xsd:enumeration value="AUTO"/>
      <xsd:enumeration value="CALLBACK"/>
      <xsd:enumeration value="NONE"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>
----