/*
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0,
 * or the Eclipse Distribution License v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

// Contributors:
//     Gavin King       - 4.0

package jakarta.persistence.query;

import jakarta.persistence.CacheRetrieveMode;
import jakarta.persistence.CacheStoreMode;
import jakarta.persistence.LockModeType;
import jakarta.persistence.PessimisticLockScope;
import jakarta.persistence.Timeout;
import jakarta.persistence.TypedQueryReference;

import java.util.List;
import java.util.Map;
import java.util.Objects;

import static java.util.Collections.emptyMap;

/**
 * A reference to a query declared using a {@link StaticQuery}
 * or {@link StaticNativeQuery} annotation. An instance of this
 * class is usually instantiated by a generated method of the
 * {@linkplain jakarta.persistence.metamodel.StaticMetamodel
 * static metamodel} for the annotated program element.
 *
 * @param <R> The result type of the query
 *
 * @since 4.0
 */
public class StaticQueryReference<R>
        implements TypedQueryReference<R> {
    private final Class<?> annotatedClass;
    private final String annotatedMemberName;
    private final Class<R> resultType;
    private final String name;
    private final List<Class<?>> parameterTypes;
    private final List<String> parameterNames;
    private final List<Object> arguments;
    private final Map<String, Object> hints;
    private final CacheRetrieveMode cacheRetrieveMode;
    private final CacheStoreMode cacheStoreMode;
    private final LockModeType lockMode;
    private final PessimisticLockScope lockScope;
    private final Timeout timeout;
    private final String entityGraphName;

    /**
     * Intended for use in code generated by an annotation processor.
     * This constructor overload is adapted to the case where the
     * program element is annotated with {@link ReadQueryOptions}.
     *
     * @param queryName The name of the query, the concatenation of
     *                  the unqualified name of the annotated type,
     *                  with the string {@code "."}, and the name of
     *                  the annotated member
     * @param annotatedClass The annotated class
     * @param annotatedMemberName The name of the annotated member
     * @param resultType The result type of the query, the type of
     *                   the annotated member
     * @param parameterTypes The types of the parameters of the
     *                       annotated member
     * @param parameterNames The names of the parameters of the
     *                       annotated member
     * @param arguments The arguments supplied to the parameters
     *                  at runtime
     * @param cacheRetrieveMode See {@link ReadQueryOptions#cacheRetrieveMode}
     * @param cacheStoreMode See {@link ReadQueryOptions#cacheStoreMode}
     * @param lockMode See {@link ReadQueryOptions#lockMode}
     * @param lockScope See {@link ReadQueryOptions#lockScope}
     * @param timeout See {@link ReadQueryOptions#timeout}
     * @param entityGraphName See {@link ReadQueryOptions#entityGraph}
     * @param hints See {@link ReadQueryOptions#hints}
     */
    public StaticQueryReference(
            String queryName,
            Class<?> annotatedClass,
            String annotatedMemberName,
            Class<R> resultType,
            List<Class<?>> parameterTypes,
            List<String> parameterNames,
            List<Object> arguments,
            CacheRetrieveMode cacheRetrieveMode,
            CacheStoreMode cacheStoreMode,
            LockModeType lockMode,
            PessimisticLockScope lockScope,
            Timeout timeout,
            String entityGraphName,
            Map<String, Object> hints) {
        this.name = queryName;
        this.annotatedClass = annotatedClass;
        this.annotatedMemberName = annotatedMemberName;
        this.resultType = resultType;
        this.parameterTypes = parameterTypes;
        this.parameterNames = parameterNames;
        this.arguments = arguments;
        this.cacheRetrieveMode = cacheRetrieveMode;
        this.cacheStoreMode = cacheStoreMode;
        this.lockMode = lockMode;
        this.lockScope = lockScope;
        this.timeout = timeout;
        this.entityGraphName = entityGraphName;
        this.hints = hints;
    }

    /**
     * Intended for use in code generated by an annotation processor.
     * This constructor overload is adapted to the case where the
     * program element is annotated with {@link WriteQueryOptions}.
     *
     * @param queryName The name of the query, the concatenation of
     *                  the unqualified name of the annotated type,
     *                  with the string {@code "."}, and the name of
     *                  the annotated member
     * @param annotatedClass The annotated class
     * @param annotatedMemberName The name of the annotated member
     * @param resultType The result type of the query, the type of
     *                   the annotated member
     * @param parameterTypes The types of the parameters of the
     *                       annotated member
     * @param parameterNames The names of the parameters of the
     *                       annotated member
     * @param arguments The arguments supplied to the parameters
     *                  at runtime
     * @param timeout See {@link WriteQueryOptions#timeout}
     * @param hints See {@link WriteQueryOptions#hints}
     */
    public StaticQueryReference(
            String queryName,
            Class<?> annotatedClass,
            String annotatedMemberName,
            Class<R> resultType,
            List<Class<?>> parameterTypes,
            List<String> parameterNames,
            List<Object> arguments,
            Timeout timeout,
            Map<String, Object> hints) {
        this(queryName, annotatedClass, annotatedMemberName, resultType,
                parameterTypes, parameterNames, arguments,
                null, null,
                LockModeType.NONE, PessimisticLockScope.NORMAL,
                timeout,
                null,
                hints);
    }

    /**
     * Intended for use in code generated by an annotation processor.
     * This constructor overload is adapted to the case where the
     * program element is not annotated with {@link ReadQueryOptions}
     * or {@link WriteQueryOptions}.
     *
     * @param queryName The name of the query, the concatenation of
     *                  the unqualified name of the annotated type,
     *                  with the string {@code "."}, and the name of
     *                  the annotated member
     * @param annotatedClass The annotated class
     * @param annotatedMemberName The name of the annotated member
     * @param resultType The result type of the query, the type of
     *                   the annotated member
     * @param parameterTypes The types of the parameters of the
     *                       annotated member
     * @param parameterNames The names of the parameters of the
     *                       annotated member
     * @param arguments The arguments supplied to the parameters
     *                  at runtime
     */
    public StaticQueryReference(
            String queryName,
            Class<?> annotatedClass,
            String annotatedMemberName,
            Class<R> resultType,
            List<Class<?>> parameterTypes,
            List<String> parameterNames,
            List<Object> arguments) {
        this(queryName, annotatedClass, annotatedMemberName, resultType,
                parameterTypes, parameterNames, arguments,
                null, null,
                LockModeType.NONE, PessimisticLockScope.NORMAL,
                null,
                null,
                emptyMap());
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public Class<? extends R> getResultType() {
        return resultType;
    }

    @Override
    public Map<String, Object> getHints() {
        return hints;
    }

    @Override
    public CacheRetrieveMode getCacheRetrieveMode() {
        return cacheRetrieveMode;
    }

    @Override
    public CacheStoreMode getCacheStoreMode() {
        return cacheStoreMode;
    }

    @Override
    public LockModeType getLockMode() {
        return lockMode;
    }

    @Override
    public PessimisticLockScope getPessimisticLockScope() {
        return lockScope;
    }

    @Override
    public Timeout getTimeout() {
        return timeout;
    }

    @Override
    public String getEntityGraphName() {
        return entityGraphName;
    }

    @Override
    public List<Class<?>> getParameterTypes() {
        return parameterTypes;
    }

    @Override
    public List<String> getParameterNames() {
        return parameterNames;
    }

    @Override
    public List<Object> getArguments() {
        return arguments;
    }

    public Class<?> getAnnotatedClass() {
        return annotatedClass;
    }

    public String getAnnotatedMemberName() {
        return annotatedMemberName;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        else if ((!(obj instanceof StaticQueryReference<?> that))) {
            return false;
        }
        else {
            return Objects.equals(this.resultType, that.resultType)
                && Objects.equals(this.name, that.name)
                && Objects.equals(this.parameterTypes, that.parameterTypes)
                && Objects.equals(this.parameterNames, that.parameterNames)
                && Objects.equals(this.arguments, that.arguments)
                && Objects.equals(this.cacheRetrieveMode, that.cacheRetrieveMode)
                && Objects.equals(this.cacheStoreMode, that.cacheStoreMode)
                && Objects.equals(this.lockMode, that.lockMode)
                && Objects.equals(this.lockScope, that.lockScope)
                && Objects.equals(this.timeout, that.timeout)
                && Objects.equals(this.hints, that.hints);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(resultType, name, parameterTypes, parameterNames, arguments);
    }

    @Override
    public String toString() {
        return "StaticQueryReference["
                + "resultType=" + resultType + ", "
                + "name=" + name + ", "
                + "parameterNames=" + parameterNames + ", "
                + "arguments=" + arguments + ", "
                + "options=" + List.of(cacheRetrieveMode, cacheStoreMode, lockMode, lockScope, timeout)
                + "hints =" + hints
                + ']';
    }
}
