/*
 * Copyright (c) 2025,2026 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0,
 * or the Eclipse Distribution License v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

// Contributors:
//     Gavin King       - 4.0

package jakarta.persistence.query;

import jakarta.annotation.Nonnull;
import jakarta.persistence.Statement;
import jakarta.persistence.StatementReference;

import java.util.*;

import static java.util.Collections.emptyMap;

/**
 * A reference to a statement declared using a {@link JakartaQuery}
 * or {@link NativeQuery} annotation. An instance of this
 * class is usually instantiated by a generated method of the
 * {@linkplain jakarta.persistence.metamodel.StaticMetamodel
 * static metamodel} for the annotated program element.
 *
 * @since 4.0
 */
public class StaticStatementReference
        implements StatementReference {

    @Nonnull private final Class<?> annotatedClass;
    @Nonnull private final String annotatedMemberName;
    @Nonnull private final String name;
    @Nonnull private final List<Class<?>> parameterTypes;
    @Nonnull private final List<String> parameterNames;
    @Nonnull private final List<Object> arguments;
    @Nonnull private final Map<String, Object> hints;
    @Nonnull private final Set<Statement.Option> options;

    /**
     * Intended for use in code generated by an annotation processor.
     * This constructor overload is adapted to the case where the
     * program element is annotated with {@link QueryOptions}.
     *
     * @param queryName The name of the query, the concatenation of
     *                  the unqualified name of the annotated type,
     *                  with the string {@code "."}, and the name of
     *                  the annotated member
     * @param annotatedClass The annotated class
     * @param annotatedMemberName The name of the annotated member
     * @param parameterTypes The types of the parameters of the
     *                       annotated member
     * @param parameterNames The names of the parameters of the
     *                       annotated member
     * @param arguments The arguments supplied to the parameters
     *                  at runtime
     * @param hints See {@link QueryOptions#hints}
     * @param options All specified {@linkplain Statement.Option options}
     */
    public StaticStatementReference(
            @Nonnull String queryName,
            @Nonnull Class<?> annotatedClass,
            @Nonnull String annotatedMemberName,
            @Nonnull List<Class<?>> parameterTypes,
            @Nonnull List<String> parameterNames,
            @Nonnull List<Object> arguments,
            @Nonnull Map<String, Object> hints,
            @Nonnull Statement.Option... options) {
        this.name = queryName;
        this.annotatedClass = annotatedClass;
        this.annotatedMemberName = annotatedMemberName;
        this.parameterTypes = parameterTypes;
        this.parameterNames = parameterNames;
        this.arguments = arguments;
        this.hints = hints;
        this.options = Set.of(options);
    }

    /**
     * Intended for use in code generated by an annotation processor.
     * This constructor overload is adapted to the case where the
     * program element is not annotated with {@link QueryOptions}.
     *
     * @param queryName The name of the query, the concatenation of
     *                  the unqualified name of the annotated type,
     *                  with the string {@code "."}, and the name of
     *                  the annotated member
     * @param annotatedClass The annotated class
     * @param annotatedMemberName The name of the annotated member
     * @param parameterTypes The types of the parameters of the
     *                       annotated member
     * @param parameterNames The names of the parameters of the
     *                       annotated member
     * @param arguments The arguments supplied to the parameters
     *                  at runtime
     */
    public StaticStatementReference(
            @Nonnull String queryName,
            @Nonnull Class<?> annotatedClass,
            @Nonnull String annotatedMemberName,
            @Nonnull List<Class<?>> parameterTypes,
            @Nonnull List<String> parameterNames,
            @Nonnull List<Object> arguments) {
        this(queryName, annotatedClass, annotatedMemberName,
                parameterTypes, parameterNames, arguments,
                emptyMap());
    }

    @Override
    @Nonnull
    public String getName() {
        return name;
    }

    @Override
    @Nonnull
    public Map<String, Object> getHints() {
        return hints;
    }

    @Override
    @Nonnull
    public List<Class<?>> getParameterTypes() {
        return parameterTypes;
    }

    @Override
    @Nonnull
    public List<String> getParameterNames() {
        return parameterNames;
    }

    @Override
    @Nonnull
    public List<Object> getArguments() {
        return arguments;
    }

    @Nonnull
    public Class<?> getAnnotatedClass() {
        return annotatedClass;
    }

    @Nonnull
    public String getAnnotatedMemberName() {
        return annotatedMemberName;
    }

    @Override
    @Nonnull
    public Set<Statement.Option> getOptions() {
        return new HashSet<>(options);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        else if ((!(obj instanceof StaticStatementReference that))) {
            return false;
        }
        else {
            return Objects.equals(this.name, that.name)
                && Objects.equals(this.parameterTypes, that.parameterTypes)
                && Objects.equals(this.parameterNames, that.parameterNames)
                && Objects.equals(this.arguments, that.arguments)
                && Objects.equals(this.options, that.options)
                && Objects.equals(this.hints, that.hints);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, parameterTypes, parameterNames, arguments);
    }

    @Override
    public String toString() {
        return "StaticStatementReference["
                + "name=" + name + ", "
                + "parameterNames=" + parameterNames + ", "
                + "arguments=" + arguments + ", "
                + "options=" + options + ", "
                + "hints=" + hints
                + ']';
    }
}
