/*
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0,
 * or the Eclipse Distribution License v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

// Contributors:
//     Gavin King       - 4.0

package jakarta.persistence.query;

import jakarta.persistence.StatementReference;
import jakarta.persistence.Timeout;

import java.util.List;
import java.util.Map;
import java.util.Objects;

import static java.util.Collections.emptyMap;

/**
 * A reference to a statement declared using a {@link StaticQuery}
 * or {@link StaticNativeQuery} annotation. An instance of this
 * class is usually instantiated by a generated method of the
 * {@linkplain jakarta.persistence.metamodel.StaticMetamodel
 * static metamodel} for the annotated program element.
 *
 * @since 4.0
 */
public class StaticStatementReference
        implements StatementReference {

    private final Class<?> annotatedClass;
    private final String annotatedMemberName;
    private final String name;
    private final List<Class<?>> parameterTypes;
    private final List<String> parameterNames;
    private final List<Object> arguments;
    private final Timeout timeout;
    private final Map<String, Object> hints;

    /**
     * Intended for use in code generated by an annotation processor.
     * This constructor overload is adapted to the case where the
     * program element is annotated with {@link WriteQueryOptions}.
     *
     * @param queryName The name of the query, the concatenation of
     *                  the unqualified name of the annotated type,
     *                  with the string {@code "."}, and the name of
     *                  the annotated member
     * @param annotatedClass The annotated class
     * @param annotatedMemberName The name of the annotated member
     * @param parameterTypes The types of the parameters of the
     *                       annotated member
     * @param parameterNames The names of the parameters of the
     *                       annotated member
     * @param arguments The arguments supplied to the parameters
     *                  at runtime
     * @param timeout See {@link WriteQueryOptions#timeout}
     * @param hints See {@link WriteQueryOptions#hints}
     */
    public StaticStatementReference(
            String queryName,
            Class<?> annotatedClass,
            String annotatedMemberName,
            List<Class<?>> parameterTypes,
            List<String> parameterNames,
            List<Object> arguments,
            Timeout timeout,
            Map<String, Object> hints) {
        this.name = queryName;
        this.annotatedClass = annotatedClass;
        this.annotatedMemberName = annotatedMemberName;
        this.parameterTypes = parameterTypes;
        this.parameterNames = parameterNames;
        this.arguments = arguments;
        this.timeout = timeout;
        this.hints = hints;
    }

    /**
     * Intended for use in code generated by an annotation processor.
     * This constructor overload is adapted to the case where the
     * program element is not annotated with {@link WriteQueryOptions}.
     *
     * @param queryName The name of the query, the concatenation of
     *                  the unqualified name of the annotated type,
     *                  with the string {@code "."}, and the name of
     *                  the annotated member
     * @param annotatedClass The annotated class
     * @param annotatedMemberName The name of the annotated member
     * @param parameterTypes The types of the parameters of the
     *                       annotated member
     * @param parameterNames The names of the parameters of the
     *                       annotated member
     * @param arguments The arguments supplied to the parameters
     *                  at runtime
     */
    public StaticStatementReference(
            String queryName,
            Class<?> annotatedClass,
            String annotatedMemberName,
            List<Class<?>> parameterTypes,
            List<String> parameterNames,
            List<Object> arguments) {
        this(queryName, annotatedClass, annotatedMemberName,
                parameterTypes, parameterNames, arguments,
                null, emptyMap());
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public Map<String, Object> getHints() {
        return hints;
    }

   @Override
    public List<Class<?>> getParameterTypes() {
        return parameterTypes;
    }

    @Override
    public List<String> getParameterNames() {
        return parameterNames;
    }

    @Override
    public List<Object> getArguments() {
        return arguments;
    }

    public Class<?> getAnnotatedClass() {
        return annotatedClass;
    }

    public String getAnnotatedMemberName() {
        return annotatedMemberName;
    }

    @Override
    public Timeout getTimeout() {
        return timeout;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        else if ((!(obj instanceof StaticStatementReference that))) {
            return false;
        }
        else {
            return Objects.equals(this.name, that.name)
                && Objects.equals(this.parameterTypes, that.parameterTypes)
                && Objects.equals(this.parameterNames, that.parameterNames)
                && Objects.equals(this.arguments, that.arguments)
                && Objects.equals(this.timeout, that.timeout)
                && Objects.equals(this.hints, that.hints);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, parameterTypes, parameterNames, arguments);
    }

    @Override
    public String toString() {
        return "StaticQueryReference["
                + "name=" + name + ", "
                + "parameterNames=" + parameterNames + ", "
                + "arguments=" + arguments + ", "
                + "timeout=" + timeout + ", "
                + "hints=" + hints
                + ']';
    }
}
