/*
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0,
 * or the Eclipse Distribution License v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

@Library('releng-pipeline') _

// Avoid running the pipeline on branch indexing
if (currentBuild.getBuildCauses().toString().contains('BranchIndexingCause')) {
	print "INFO: Build skipped due to trigger being Branch Indexing"
	currentBuild.result = 'NOT_BUILT'
	return
}

pipeline {
	agent {
		label 'basic'
	}
	tools {
		maven 'apache-maven-3.9.11'
		jdk 'openjdk-jdk25-latest'
	}
	options {
		buildDiscarder logRotator(daysToKeepStr: '30', numToKeepStr: '10')
		disableConcurrentBuilds(abortPrevious: false)
	}
	stages {
		stage('Make change and push to GitHub') {
			when {
				beforeAgent true
				// Releases must be triggered explicitly
				// This is just for safety; normally the Jenkins job for this pipeline
				// should be configured to "Suppress automatic SCM triggering"
				// See https://stackoverflow.com/questions/58259326/prevent-jenkins-multibranch-pipeline-from-triggering-builds-for-new-branches
				triggeredBy cause: "UserIdCause"
			}
			steps {
				script {
                    sshagent(['github-bot-ssh', 'projects-storage.eclipse.org-bot-ssh']) {
                        withCredentials([file(credentialsId: 'secret-subkeys.asc', variable: 'KEYRING')]) {
                            withMaven(mavenLocalRepo: env.WORKSPACE_TMP + '/.m2repository') {
                                sh "find . -type d -exec chmod -s {} \\;"
                                sh "find . -type d -exec chmod 0755 {} \\;"
                                sh 'gpg --batch --import "${KEYRING}"'
                                sh 'for fpr in $(gpg --list-keys --with-colons  | awk -F: \'/fpr:/ {print $10}\' | sort -u); do echo -e "5\ny\n" |  gpg --batch --command-fd 0 --expert --edit-key ${fpr} trust; done'

                                // Set up git so that we can create commits
                                sh 'git config --local user.name "jpa-bot"'
                                sh 'git config --local user.email "jpa-bot@eclipse.org"'

								// test github connection:
								sh 'ssh -v -T git@github.com | true'

                                // update version:
                                sh "echo 'This is a test line' >> README.md"

                                // commit and tag the "release version":
                                sh "git commit -a -m '[Jenkins job] Some not-so-meaningful comment'"

                                sh "git push origin HEAD:${env.GIT_BRANCH}"
                            }
                        }
                    }
				}
			}
		}
	}
}