
[[GEQNJ]][[additional-jpa-notes]]

1.2.7 Additional {TechnologyShortName} Notes
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In addition to the usual signature, API, and end-to-end tests,
the {TechnologyShortName} TCK also includes pluggability tests verify that the
implementation under test can use third-party persistence providers
instead of the one provided by the implementation.

[NOTE]
=======================================================================

The following may be useful to users of previous TCK versions:

No significant changes were made to how tests are run.

=======================================================================

