
*{techID}10* The presence of an XML comment in a Configuration
Descriptor, when processed by a Deployment Tool, must not cause the
functional programmatic behavior of the Deployment Tool to vary from
the functional programmatic behavior of the Deployment Tool in the
absence of that comment.

*{techID}11* The Runtime must report an error when processing a
Configuration Descriptor that does not conform to the Specifications.

*{techID}12* The presence of an XML comment in a Configuration
Descriptor, when processed by the Runtime, must not cause the
functional programmatic behavior of the Runtime to vary from
the functional programmatic behavior of the Runtime in the
absence of that comment.

*{techID}13* An error must be reported when processing a configuration
descriptor that includes a {TechnologyFullName} QL expression that does not
conform to the Specifications.
