/*
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0,
 * or the Eclipse Distribution License v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

@Library('releng-pipeline') _

// Avoid running the pipeline on branch indexing
if (currentBuild.getBuildCauses().toString().contains('BranchIndexingCause')) {
	print "INFO: Build skipped due to trigger being Branch Indexing"
	currentBuild.result = 'NOT_BUILT'
	return
}

pipeline {
	agent {
		label 'basic'
	}
	tools {
		maven 'apache-maven-3.9.11'
		jdk 'openjdk-jdk25-latest'
	}
	options {
		buildDiscarder logRotator(daysToKeepStr: '30', numToKeepStr: '10')
		disableConcurrentBuilds(abortPrevious: false)
	}
	parameters {
		string(
				name: 'RELEASE_VERSION',
				defaultValue: '',
				description: 'The version to be released, e.g. 4.0.',
				trim: true
		)
        string(
                name: 'DEVELOPMENT_VERSION',
                defaultValue: '',
                description: 'The next version to be used after the release, e.g. 4.1-SNAPSHOT.',
                trim: true
        )
        string(
                name: 'SPEC_STATUS',
                defaultValue: '',
                description: 'The specification status, e.g. DRAFT, BETA, etc., or blank for final.',
                trim: true
        )
	}
	stages {
		stage('Publish Release to Maven Central') {
			when {
				beforeAgent true
				// Releases must be triggered explicitly
				// This is just for safety; normally the Jenkins job for this pipeline
				// should be configured to "Suppress automatic SCM triggering"
				// See https://stackoverflow.com/questions/58259326/prevent-jenkins-multibranch-pipeline-from-triggering-builds-for-new-branches
				triggeredBy cause: "UserIdCause"
			}
			steps {
				script {
					// Check that all the necessary parameters are set
					if (!params.RELEASE_VERSION) {
						throw new IllegalArgumentException("Missing value for parameter RELEASE_VERSION.")
					}
					if (!params.DEVELOPMENT_VERSION) {
						throw new IllegalArgumentException("Missing value for parameter DEVELOPMENT_VERSION.")
					}
					echo "Performing release for version ${params.RELEASE_VERSION}"

                    sshagent(['github-bot-ssh']) {
						withMaven(mavenLocalRepo: env.WORKSPACE_TMP + '/.m2repository') {
							// Set up git so that we can create commits
                            sh 'git config --local user.name "jpa-bot"'
                            sh 'git config --local user.email "jpa-bot@eclipse.org"'

							// update version:
                            sh "mvn clean versions:set -DnewVersion=${params.RELEASE_VERSION} -DgenerateBackupPoms=false -f spec"

							// commit and tag the "release version":
							sh "git commit -a -m '[Jenkins release job] Preparing Specification release ${params.RELEASE_VERSION}'"
							sh "git tag -a -m 'Release Specification ${params.RELEASE_VERSION}' ${params.RELEASE_VERSION}-tag"

							// deploy to Maven Central:
							sh "mvn clean install -Poss-release -Dstatus=${params.SPEC_STATUS} -f spec"

							// reset the version back to dev:
							sh "mvn clean versions:set -DnewVersion=${params.DEVELOPMENT_VERSION} -DgenerateBackupPoms=false -f spec"

							// commit the dev version and push all back to git:
							sh "git commit -a -m '[Jenkins release job] Preparing next Specification development iteration'"

							sh "git push origin HEAD:${env.GIT_BRANCH}"
							sh "git push origin ${params.RELEASE_VERSION}"
						}
					}
				}
			}
            post {
                success {
                    archiveArtifacts artifacts: 'spec/target/generated-docs/**/*',
                            fingerprint: true,
                            allowEmptyArchive: false
                }
            }
		}
	}
}
