DROP PROCEDURE GetEmpOneFirstNameFromOut !
CREATE PROCEDURE GetEmpOneFirstNameFromOut (out OUT_PARAM VARCHAR(255)) LANGUAGE SQL BEGIN SELECT FIRSTNAME into OUT_PARAM FROM EMPLOYEE WHERE ID=1; END !

DROP PROCEDURE GetEmpFirstNameFromOut !
CREATE PROCEDURE GetEmpFirstNameFromOut (in IN_PARAM INTEGER, out OUT_PARAM VARCHAR(255)) LANGUAGE SQL BEGIN SELECT FIRSTNAME into OUT_PARAM FROM EMPLOYEE WHERE ID=IN_PARAM; END !

DROP PROCEDURE GetEmpLastNameFromInOut !
CREATE PROCEDURE GetEmpLastNameFromInOut (inout INOUT_PARAM VARCHAR(255)) LANGUAGE SQL BEGIN SELECT LASTNAME into INOUT_PARAM FROM EMPLOYEE WHERE ID=INOUT_PARAM; END !

DROP PROCEDURE GetEmpASCFromRS !
CREATE PROCEDURE GetEmpASCFromRS() DYNAMIC RESULT SETS 1 LANGUAGE SQL BEGIN DECLARE C1 CURSOR WITH RETURN FOR SELECT ID, FIRSTNAME, LASTNAME, HIREDATE, SALARY FROM EMPLOYEE ORDER BY ID ASC; OPEN C1; END !

DROP PROCEDURE GetEmpIdFNameLNameFromRS !
CREATE PROCEDURE GetEmpIdFNameLNameFromRS(in IN_PARAM INTEGER) RESULT SETS 1 LANGUAGE SQL BEGIN DECLARE C1 CURSOR WITH RETURN FOR SELECT ID, FIRSTNAME, LASTNAME  FROM EMPLOYEE WHERE ID=IN_PARAM; OPEN C1; END !

DROP PROCEDURE GetEmpIdUsingHireDateFromOut !
CREATE PROCEDURE GetEmpIdUsingHireDateFromOut (in IN_PARAM DATE, out OUT_PARAM INTEGER) LANGUAGE SQL BEGIN SELECT ID into OUT_PARAM FROM EMPLOYEE WHERE HIREDATE=IN_PARAM; END !

DROP PROCEDURE UpdateEmpSalaryColumn !
CREATE PROCEDURE UpdateEmpSalaryColumn() BEGIN UPDATE EMPLOYEE set SALARY=0.00; END !

DROP PROCEDURE DeleteAllEmp !
CREATE PROCEDURE DeleteAllEmp() BEGIN DELETE FROM EMPLOYEE; END !
