
ALTER TABLE PHONE_TABLE drop foreign key FK_FOR_ADDRESS !

ALTER TABLE ALIAS_TABLE drop foreign key FK1_FOR_CUSTOMER_TABLE !

ALTER TABLE ALIAS_TABLE drop foreign key FK2_FOR_CUSTOMER_TABLE !

ALTER TABLE FKS_ALIAS_CUSTOMER drop foreign key FK_FOR_CUSTOMER_TABLE !

ALTER TABLE FKS_ALIAS_CUSTOMER drop foreign key FK_FOR_ALIAS_TABLE !

ALTER TABLE CREDITCARD_TABLE drop foreign key FK3_FOR_CUSTOMER_TABLE !

ALTER TABLE CREDITCARD_TABLE drop foreign key FK_FOR_ORDER_TABLE !

ALTER TABLE ORDER_TABLE drop foreign key FK4_FOR_CUSTOMER_TABLE !

ALTER TABLE ORDER_TABLE drop foreign key FK0_FOR_LINEITEM_TABLE !

ALTER TABLE LINEITEM_TABLE drop foreign key FK_FOR_PRODUCT_TABLE !

ALTER TABLE LINEITEM_TABLE drop foreign key FK1_FOR_ORDER_TABLE !

ALTER TABLE CUSTOMER_TABLE drop foreign key FK5_FOR_CUSTOMER_TABLE !

ALTER TABLE CUSTOMER_TABLE drop foreign key FK6_FOR_CUSTOMER_TABLE !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK1_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK2_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK1_FOR_BEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK2_FOR_BEJB_1X1_BI_BTOB !

ALTER TABLE BEJB_1X1_BI_BTOB drop foreign key FK_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK1_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK2_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK1_FOR_BEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK2_FOR_BEJB_1X1_BI_CASCADE !

ALTER TABLE BEJB_1X1_BI_CASCADE drop foreign key FK_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK1_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK2_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK1_FOR_BEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK2_FOR_BEJB_1X1_UNI_BTOB !

ALTER TABLE BEJB_1X1_UNI_BTOB drop foreign key FK_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK1_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK2_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK1_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK2_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK3_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK4_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEJB_1XM_BI_BTOB drop foreign key FK_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK1_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK2_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK1_FOR_BEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK2_FOR_BEJB_1XM_BI_CASCADE !

ALTER TABLE BEJB_1XM_BI_CASCADE drop foreign key FK_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK1_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK2_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK1_FOR_BEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK2_FOR_BEJB_1XM_BI_DELETE !

ALTER TABLE BEJB_1XM_BI_DELETE drop foreign key FK_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK1_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK2_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK1_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK2_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK3_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK4_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEJB_1XM_UNI_BTOB drop foreign key FK_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK1_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK2_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK1_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK2_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK3_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK4_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEJB_MX1_UNI_BTOB drop foreign key FK_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK1_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK2_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK1_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK2_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK3_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK4_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEJB_MX1_UNI_DELETE drop foreign key FK_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK1_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK2_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK3_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK4_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK1_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK2_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK3_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK4_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE FKEYS_MXM_BI_BTOB drop foreign key FK_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE FKEYS_MXM_BI_BTOB drop foreign key FK_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK1_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK2_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK3_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK4_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK1_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK2_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK3_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK4_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE FKEYS_MXM_BI_DELETE drop foreign key FK_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE FKEYS_MXM_BI_DELETE drop foreign key FK_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK1_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK2_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK3_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK4_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK1_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK2_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK3_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK4_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE FKEYS_MXM_UNI_BTOB drop foreign key FK_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE FKEYS_MXM_UNI_BTOB drop foreign key FK_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE FKS_ANOOP_CNOOP  drop foreign key FK2_FOR_ALIAS_TABLE !

ALTER TABLE FKS_ANOOP_CNOOP  drop foreign key FK8_FOR_CUSTOMER_TABLE !

ALTER TABLE SPOUSE_TABLE drop foreign key FK7_FOR_CUSTOMER_TABLE !

ALTER TABLE SPOUSE_TABLE drop foreign key FK_FOR_INFO_TABLE !

ALTER TABLE INFO_TABLE drop foreign key FK_FOR_SPOUSE_TABLE !

ALTER TABLE EMPLOYEE drop foreign key FK_MGR !
ALTER TABLE EMPLOYEE drop foreign key FK_DEPT !
ALTER TABLE EMPLOYEE drop foreign key FK_INS !
ALTER TABLE EMPLOYEE drop foreign key FK_PROJECT !

ALTER TABLE PARTTIMEEMPLOYEE drop foreign key FK_ADDR !

ALTER TABLE COMPANY drop foreign key FK_ADDRESS!

ALTER TABLE DEPARTMENT drop foreign key FK_COMPANY !

ALTER TABLE TEAM DROP foreign key COMPANY_COMPANYID !

ALTER TABLE PERSON DROP foreign key INSURANCE_INSID !

ALTER TABLE PERSON DROP foreign key TEAM_TEAMID !

ALTER TABLE PERSON DROP foreign key PROJECT_PROJID !

ALTER TABLE PERSON_ANNUALREVIEW DROP foreign key ANNUALREVIEWS_AID !

ALTER TABLE PERSON_ANNUALREVIEW DROP foreign key PERSON_PERSONID!

ALTER TABLE PROJECT_PERSON DROP foreign key PROJECTS_PROJID!

ALTER TABLE PROJECT_PERSON DROP foreign key PERSONS_PERSONID!

ALTER TABLE PERSON_INSURANCE DROP foreign key P_PERSONID !

ALTER TABLE PERSON_INSURANCE DROP foreign key INS_INSID !

ALTER TABLE ORDER1 DROP foreign key FK1_FOR_ITEM !

ALTER TABLE ORDER2 DROP foreign key FK2_FOR_ITEM !

ALTER TABLE ORDER3 DROP foreign key FK3_FOR_ITEM !

ALTER TABLE PARTTIMEEMPLOYEE DROP foreign key FK_DEPT2 !
ALTER TABLE STUDENT_COURSE DROP foreign key STDNTCOURSEStdntID !
ALTER TABLE STUDENT_COURSE DROP foreign key STDNTCOURSEcrsesID !
ALTER TABLE ENROLLMENTS DROP foreign key ENROLLMENTSSTUDENT !
ALTER TABLE ENROLLMENTS DROP foreign key NROLLMENTSSEMESTER !
ALTER TABLE COURSE_STUDENT DROP foreign key CRSESTUDENTCurseID !
ALTER TABLE COURSE_STUDENT DROP foreign key CRSSTUDENTstdntsID !
ALTER TABLE RETAILORDER2 DROP foreign key FK_FOR_CUST !

ALTER TABLE EMP_MAPKEYCOL DROP foreign key FK_DEPT1 !
ALTER TABLE EMP_MAPKEYCOL DROP foreign key FK_DEPT3 !
ALTER TABLE EMP_MAPKEYCOL DROP foreign key FK_DEPT4 !
ALTER TABLE EMP_MAPKEYCOL2 DROP foreign key FK_DEPT5 !

drop table ADDRESS  !
create TABLE ADDRESS (id VARCHAR(255) PRIMARY KEY, street VARCHAR(255), city VARCHAR(255), state VARCHAR(255), zip VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
        
drop table PHONE_TABLE  !
create TABLE PHONE_TABLE (id VARCHAR(255) PRIMARY KEY, area VARCHAR(255), phone_number VARCHAR(255), FK_FOR_ADDRESS VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
        
drop table CUSTOMER_TABLE  !
create TABLE CUSTOMER_TABLE (id VARCHAR(255) PRIMARY KEY, name VARCHAR(255) , country VARCHAR(255), code VARCHAR(255), FK5_FOR_CUSTOMER_TABLE VARCHAR(255), FK6_FOR_CUSTOMER_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE PHONES DROP foreign key FK_FOR_PHONES !
ALTER TABLE EMPLOYEES DROP foreign key FK_FOR_EMPLOYEES !

drop table CUST_TABLE !
create TABLE CUST_TABLE ( cust_id VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), COUNTRY VARCHAR(255), CODE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table PHONES !
CREATE TABLE PHONES (ID VARCHAR(255), PHONE_NUMBER VARCHAR(255), FK_FOR_PHONES VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
ALTER TABLE PHONES add (constraint FK_FOR_PHONES Foreign Key (FK_FOR_PHONES) references CUST_TABLE(CUST_ID) ON DELETE CASCADE) !

DROP TABLE EMPLOYEES !
CREATE TABLE EMPLOYEES (ID VARCHAR(255), LASTNAMEEMPLOYEES VARCHAR(255), FK_FOR_EMPLOYEES VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
ALTER TABLE EMPLOYEES add (constraint FK_FOR_EMPLOYEES Foreign Key (FK_FOR_EMPLOYEES) references CUST_TABLE (CUST_ID) ON DELETE CASCADE) !

drop table TRIM_TABLE  !
create TABLE TRIM_TABLE (id VARCHAR(255) PRIMARY KEY, name CHAR(30) NOT NULL) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table ALIAS_TABLE  !
create TABLE ALIAS_TABLE (id VARCHAR(255) PRIMARY KEY, alias VARCHAR(255), FK1_FOR_CUSTOMER_TABLE  VARCHAR(255), FK2_FOR_CUSTOMER_TABLE  VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
         
drop table FKS_ALIAS_CUSTOMER  !
create TABLE FKS_ALIAS_CUSTOMER ( FK_FOR_CUSTOMER_TABLE VARCHAR(255) , FK_FOR_ALIAS_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table FKS_ANOOP_CNOOP !
create TABLE FKS_ANOOP_CNOOP( FK8_FOR_CUSTOMER_TABLE VARCHAR(255) , FK2_FOR_ALIAS_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CREDITCARD_TABLE  !
create TABLE CREDITCARD_TABLE (ID VARCHAR(255) PRIMARY KEY, TYPE VARCHAR(255), EXPIRES VARCHAR(255), APPROVED NUMERIC, CREDITCARD_NUMBER VARCHAR(255), BALANCE DOUBLE PRECISION, FK3_FOR_CUSTOMER_TABLE VARCHAR(255), FK_FOR_ORDER_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table ORDER_TABLE  !
create TABLE  ORDER_TABLE (ID VARCHAR(255) PRIMARY KEY, TOTALPRICE DOUBLE PRECISION , FK4_FOR_CUSTOMER_TABLE VARCHAR(255), FK0_FOR_LINEITEM_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table PRODUCT_DETAILS !
create TABLE PRODUCT_DETAILS ( ID VARCHAR(255)  PRIMARY KEY , WHOUSE VARCHAR(255) , LICENSE_KEY INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table PRODUCT_TABLE !
CREATE TABLE PRODUCT_TABLE (id VARCHAR(255) PRIMARY KEY, name VARCHAR(255), price float, quantity integer, pnum integer, PRODUCT_TYPE VARCHAR(255), INCEPTION DATE NULL, SOLD DATE NULL, MODEL integer, REV float ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE PRODUCT_TABLE_DISCRIMINATOR !
CREATE TABLE PRODUCT_TABLE_DISCRIMINATOR ( id VARCHAR(255) PRIMARY KEY, name VARCHAR(255), quantity integer, pnum integer, price float, PRODUCT_TYPE integer) !

DROP TABLE PRICED_PRODUCT_TABLE !
CREATE TABLE PRICED_PRODUCT_TABLE (ID VARCHAR(255) PRIMARY KEY , NAME VARCHAR(255), PRICE FLOAT, QUANTITY INTEGER, PNUM INTEGER ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table SPOUSE_TABLE !
create TABLE SPOUSE_TABLE (ID VARCHAR(255) PRIMARY KEY,  FIRSTNAME VARCHAR(255), MAIDENNAME VARCHAR(255), LASTNAME VARCHAR(255), SOCSECNUM VARCHAR(255), FK7_FOR_CUSTOMER_TABLE VARCHAR(255), FK_FOR_INFO_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table INFO_TABLE !
create TABLE INFO_TABLE (ID VARCHAR(255) PRIMARY KEY, INFOSTREET VARCHAR(255), INFOCITY VARCHAR(255), INFOSTATE VARCHAR(255), INFOZIP VARCHAR(255), FK_FOR_SPOUSE_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table LINEITEM_TABLE  !
create TABLE LINEITEM_TABLE (id VARCHAR(255) PRIMARY KEY, quantity integer, FK_FOR_PRODUCT_TABLE VARCHAR(255), FK1_FOR_ORDER_TABLE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
         
ALTER TABLE PHONE_TABLE add ( constraint FK_FOR_ADDRESS Foreign Key (FK_FOR_ADDRESS) references ADDRESS(id) ON DELETE CASCADE ) !

ALTER TABLE ALIAS_TABLE add ( constraint FK1_FOR_CUSTOMER_TABLE Foreign Key (FK1_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE ALIAS_TABLE add ( constraint FK2_FOR_CUSTOMER_TABLE Foreign Key (FK2_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_ALIAS_CUSTOMER  add ( constraint FK_FOR_CUSTOMER_TABLE Foreign Key (FK_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_ALIAS_CUSTOMER  add ( constraint FK_FOR_ALIAS_TABLE Foreign Key (FK_FOR_ALIAS_TABLE) references ALIAS_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_ANOOP_CNOOP  add ( constraint FK2_FOR_ALIAS_TABLE Foreign Key (FK2_FOR_ALIAS_TABLE) references ALIAS_TABLE(id) ON DELETE CASCADE)!

ALTER TABLE FKS_ANOOP_CNOOP  add (constraint FK8_FOR_CUSTOMER_TABLE Foreign Key (FK8_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE)!

ALTER TABLE CREDITCARD_TABLE add ( constraint FK3_FOR_CUSTOMER_TABLE Foreign Key (FK3_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE CREDITCARD_TABLE add ( constraint FK_FOR_ORDER_TABLE Foreign Key (FK_FOR_ORDER_TABLE) references ORDER_TABLE(id) ON DELETE CASCADE ) !
       
ALTER TABLE ORDER_TABLE add ( constraint FK4_FOR_CUSTOMER_TABLE Foreign Key (FK4_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE ORDER_TABLE add ( constraint FK0_FOR_LINEITEM_TABLE Foreign Key (FK0_FOR_LINEITEM_TABLE) references LINEITEM_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE LINEITEM_TABLE add ( constraint FK_FOR_PRODUCT_TABLE Foreign Key (FK_FOR_PRODUCT_TABLE) references PRODUCT_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE LINEITEM_TABLE add ( constraint FK1_FOR_ORDER_TABLE Foreign Key (FK1_FOR_ORDER_TABLE) references ORDER_TABLE(id) ON DELETE CASCADE ) !
 
ALTER TABLE CUSTOMER_TABLE add ( constraint FK5_FOR_CUSTOMER_TABLE Foreign Key (FK5_FOR_CUSTOMER_TABLE) references ADDRESS(id) ON DELETE CASCADE ) !

ALTER TABLE CUSTOMER_TABLE add ( constraint FK6_FOR_CUSTOMER_TABLE Foreign Key (FK6_FOR_CUSTOMER_TABLE) references ADDRESS(id) ON DELETE CASCADE ) !
   
ALTER TABLE SPOUSE_TABLE add (constraint FK7_FOR_CUSTOMER_TABLE Foreign Key(FK7_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) ON DELETE CASCADE) ! 

ALTER TABLE SPOUSE_TABLE add (constraint FK_FOR_INFO_TABLE Foreign Key (FK_FOR_INFO_TABLE) references INFO_TABLE(ID) ON DELETE CASCADE) !

ALTER TABLE INFO_TABLE add (constraint FK_FOR_SPOUSE_TABLE Foreign Key (FK_FOR_SPOUSE_TABLE) references SPOUSE_TABLE(ID) ON DELETE CASCADE) !

drop table BEANEJB_1X1_BI_BTOB  !
create TABLE BEANEJB_1X1_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_BI_BTOB VARCHAR(255), FK2_FOR_AEJB_1X1_BI_BTOB VARCHAR(255), FK1_FOR_BEJB_1X1_BI_BTOB VARCHAR(255), FK2_FOR_BEJB_1X1_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_BI_BTOB  !
create TABLE  AEJB_1X1_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_BI_BTOB  !
create TABLE BEJB_1X1_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK1_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK1_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK2_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK2_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK1_FOR_BEJB_1X1_BI_BTOB Foreign Key (FK1_FOR_BEJB_1X1_BI_BTOB) references BEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK2_FOR_BEJB_1X1_BI_BTOB Foreign Key (FK2_FOR_BEJB_1X1_BI_BTOB) references BEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEJB_1X1_BI_BTOB add ( constraint FK_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_1X1_BI_CASCADE  !
create TABLE BEANEJB_1X1_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255), FK2_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255), FK1_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255), FK2_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_BI_CASCADE  !
create TABLE  AEJB_1X1_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_BI_CASCADE  !
create TABLE BEJB_1X1_BI_CASCADE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK1_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK1_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK2_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK2_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK1_FOR_BEJB_1X1_BI_CASCADE Foreign Key (FK1_FOR_BEJB_1X1_BI_CASCADE) references BEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK2_FOR_BEJB_1X1_BI_CASCADE Foreign Key (FK2_FOR_BEJB_1X1_BI_CASCADE) references BEJB_1X1_BI_CASCADE(id)) !


ALTER TABLE BEJB_1X1_BI_CASCADE add ( constraint FK_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !
   
drop table BEANEJB_1X1_UNI_BTOB  !
create TABLE BEANEJB_1X1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_UNI_BTOB  !
create TABLE  AEJB_1X1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_UNI_BTOB  !
create TABLE BEJB_1X1_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK1_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK1_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK2_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK2_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK1_FOR_BEJB_1X1_UNI_BTOB Foreign Key (FK1_FOR_BEJB_1X1_UNI_BTOB) references BEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK2_FOR_BEJB_1X1_UNI_BTOB Foreign Key (FK2_FOR_BEJB_1X1_UNI_BTOB) references BEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_1X1_UNI_BTOB add ( constraint FK_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

drop table BEANEJB_1XM_BI_BTOB  !
create TABLE BEANEJB_1XM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_BTOB VARCHAR(255), FK2_FOR_AEJB_1XM_BI_BTOB VARCHAR(255), FK1_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK2_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK3_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK4_FOR_BEJB_1XM_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1XM_BI_BTOB  !
create TABLE  AEJB_1XM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_1XM_BI_BTOB  !
create TABLE BEJB_1XM_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK1_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK1_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK2_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK2_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK1_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK1_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK2_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK2_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK3_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK3_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK4_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK4_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEJB_1XM_BI_BTOB add ( constraint FK_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_1XM_BI_CASCADE  !
create TABLE BEANEJB_1XM_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255), FK2_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255), FK1_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255), FK2_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1XM_BI_CASCADE  !
create TABLE  AEJB_1XM_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1XM_BI_CASCADE  !
create TABLE BEJB_1XM_BI_CASCADE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK1_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK1_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK2_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK2_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !



ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK1_FOR_BEJB_1XM_BI_CASCADE Foreign Key (FK1_FOR_BEJB_1XM_BI_CASCADE) references BEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK2_FOR_BEJB_1XM_BI_CASCADE Foreign Key (FK2_FOR_BEJB_1XM_BI_CASCADE) references BEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEJB_1XM_BI_CASCADE add ( constraint FK_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !
   
drop table BEANEJB_1XM_BI_DELETE  !
create TABLE BEANEJB_1XM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_DELETE VARCHAR(255), FK2_FOR_AEJB_1XM_BI_DELETE VARCHAR(255), FK1_FOR_BEJB_1XM_BI_DELETE VARCHAR(255), FK2_FOR_BEJB_1XM_BI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_1XM_BI_DELETE  !
create TABLE  AEJB_1XM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_1XM_BI_DELETE  !
create TABLE BEJB_1XM_BI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK1_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK1_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK2_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK2_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !


ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK1_FOR_BEJB_1XM_BI_DELETE Foreign Key (FK1_FOR_BEJB_1XM_BI_DELETE) references BEJB_1XM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK2_FOR_BEJB_1XM_BI_DELETE Foreign Key (FK2_FOR_BEJB_1XM_BI_DELETE) references BEJB_1XM_BI_DELETE(id)) !


ALTER TABLE BEJB_1XM_BI_DELETE add ( constraint FK_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !
   
drop table BEANEJB_1XM_UNI_BTOB  !
create TABLE BEANEJB_1XM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK3_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK4_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_1XM_UNI_BTOB  !
create TABLE  AEJB_1XM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1XM_UNI_BTOB  !
create TABLE BEJB_1XM_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK1_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK1_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK2_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK2_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK1_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK1_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK2_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK2_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK3_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK3_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK4_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK4_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_1XM_UNI_BTOB add ( constraint FK_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_MX1_UNI_BTOB  !
create TABLE BEANEJB_MX1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK3_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK4_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_MX1_UNI_BTOB  !
create TABLE  AEJB_MX1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_MX1_UNI_BTOB  !
create TABLE BEJB_MX1_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK1_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK1_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK2_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK2_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK1_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK1_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK2_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK2_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK3_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK3_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK4_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK4_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_MX1_UNI_BTOB add ( constraint FK_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

drop table BEANEJB_MX1_UNI_DELETE  !
create TABLE BEANEJB_MX1_UNI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MX1_UNI_DELETE  !
create TABLE  AEJB_MX1_UNI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MX1_UNI_DELETE  !
create TABLE BEJB_MX1_UNI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK1_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK1_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK2_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK2_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK1_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK1_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK2_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK2_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !


ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK3_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK3_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK4_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK4_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEJB_MX1_UNI_DELETE add ( constraint FK_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !
   
drop table BEANEJB_MXM_BI_BTOB  !
create TABLE BEANEJB_MXM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_BI_BTOB  !
create TABLE  AEJB_MXM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MXM_BI_BTOB  !
create TABLE BEJB_MXM_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table FKEYS_MXM_BI_BTOB  !
create TABLE FKEYS_MXM_BI_BTOB ( FK_FOR_AEJB_MXM_BI_BTOB  VARCHAR(255), FK_FOR_BEJB_MXM_BI_BTOB  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!    

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK1_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK1_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK2_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK2_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK3_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK3_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK4_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK4_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK1_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK1_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK2_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK2_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK3_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK3_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK4_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK4_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_BI_BTOB add ( constraint FK_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_BI_BTOB add ( constraint FK_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_MXM_BI_DELETE  !
create TABLE BEANEJB_MXM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_BI_DELETE  !
create TABLE  AEJB_MXM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MXM_BI_DELETE  !
create TABLE BEJB_MXM_BI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table FKEYS_MXM_BI_DELETE  !
create TABLE FKEYS_MXM_BI_DELETE ( FK_FOR_AEJB_MXM_BI_DELETE  VARCHAR(255), FK_FOR_BEJB_MXM_BI_DELETE  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!    

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK1_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK1_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK2_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK2_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK3_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK3_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK4_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK4_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !


ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK1_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK1_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK2_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK2_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK3_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK3_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK4_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK4_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE FKEYS_MXM_BI_DELETE add ( constraint FK_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE FKEYS_MXM_BI_DELETE add ( constraint FK_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !
   
drop table BEANEJB_MXM_UNI_BTOB  !
create TABLE BEANEJB_MXM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_UNI_BTOB  !
create TABLE  AEJB_MXM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_MXM_UNI_BTOB  !
create TABLE BEJB_MXM_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table FKEYS_MXM_UNI_BTOB  !
create TABLE FKEYS_MXM_UNI_BTOB ( FK_FOR_AEJB_MXM_UNI_BTOB  VARCHAR(255), FK_FOR_BEJB_MXM_UNI_BTOB  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK1_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK1_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK2_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK2_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK3_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK3_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK4_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK4_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK1_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK1_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK2_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK2_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK3_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK3_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK4_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK4_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_UNI_BTOB add ( constraint FK_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_UNI_BTOB add ( constraint FK_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !
   

DROP TABLE PKEY !
CREATE TABLE PKEY ( PMIDINTEGER INTEGER  NOT NULL, PMIDSTRING VARCHAR(25) NOT NULL, PMIDFLOAT REAL NOT NULL, BRANDNAME VARCHAR(255) , PRICE REAL ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE DATATYPES !
CREATE TABLE DATATYPES (ID INTEGER NOT NULL, BOOLEANDATA SMALLINT NULL, CHARDATA CHAR NULL, SHORTDATA SMALLINT NULL, INTDATA INTEGER NULL, INTDATA2 INTEGER NULL, LONGDATA NUMERIC NULL, DBLDATA DOUBLE PRECISION NULL, FLOATDATA REAL NULL, ENUMODATA INTEGER NULL, ENUMSDATA VARCHAR(25), BYTEDATA SMALLINT NULL, TRANS SMALLINT NULL, BYTEARRAYDATA BLOB, CHARARRAYDATA VARCHAR(448), CONSTRAINT PK_DATATYPES PRIMARY KEY (ID) ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE DATATYPES2  !
CREATE TABLE DATATYPES2 ( DATATYPES2_ID DATE NOT NULL, DATEDATA DATE, TIMEDATA TIME, TSDATA TIMESTAMP, CONSTRAINT PK_DATATYPES2 PRIMARY KEY (DATATYPES2_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE DATATYPES3 !
CREATE TABLE DATATYPES3 ( ID DECIMAL(18,0) NOT NULL, THEVALUE DECIMAL(18,0), CONSTRAINT PK_DATATYPES3 PRIMARY KEY (ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE GENERATOR_TABLE !
CREATE TABLE GENERATOR_TABLE (PK_COL VARCHAR(10) NOT NULL, VAL_COL INTEGER ) ENGINE=innoDB DEFAULT CHARSET=latin1 !
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT_ID', 1) !
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT1_ID', 1) !
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT2_ID', 100) !
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT3_ID', 1000) !

DROP TABLE SEQUENCE !
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(10) PRIMARY KEY NOT NULL, SEQ_COUNT INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1 !
INSERT into SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0) !


DROP TABLE EMPLOYEE !
CREATE TABLE EMPLOYEE (ID NUMERIC NOT NULL, FIRSTNAME VARCHAR(255) NULL, LASTNAME VARCHAR(255) NULL, HIREDATE DATE NULL, SALARY REAL NOT NULL, STATUS VARCHAR(255), THEORDERCOLUMN INTEGER, EMPLOYEES_ORDER INTEGER, FK_MGR NUMERIC, FK_DEPT NUMERIC, FK_PROJECT INTEGER, FK_INS INTEGER, CONSTRAINT PK_EMPLOYEE PRIMARY KEY(ID) ) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE DEPARTMENT !
CREATE TABLE DEPARTMENT (NAME VARCHAR(255) NULL, ID NUMERIC PRIMARY KEY NOT NULL,  COMPANY_COMPANYID INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE DEPARTMENT2 !
CREATE TABLE DEPARTMENT2 (ID INTEGER PRIMARY KEY NOT NULL, NAME VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE COFFEE !
CREATE TABLE COFFEE (ID INTEGER PRIMARY KEY NOT NULL, BRANDNAME VARCHAR(25), PRICE REAL ) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE COMPANY !
CREATE TABLE COMPANY (COMPANYID INTEGER PRIMARY KEY NOT NULL, NAME VARCHAR(25), ADDRESS_ID VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1 !
DROP TABLE TEAM !
CREATE TABLE TEAM (NAME VARCHAR(255) NULL, TEAMID INTEGER PRIMARY KEY NOT NULL,  COMPANY_COMPANYID INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE COMPANY ADD ( CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID) ON DELETE CASCADE )!
ALTER TABLE DEPARTMENT ADD ( CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_COMPANYID) REFERENCES COMPANY (COMPANYID) ON DELETE CASCADE )!
ALTER TABLE TEAM ADD ( CONSTRAINT COMPANY_COMPANYID FOREIGN KEY (COMPANY_COMPANYID) REFERENCES COMPANY(COMPANYID) ON DELETE CASCADE ) !

DROP TABLE PROJECT!
CREATE TABLE PROJECT (PROJID INTEGER PRIMARY KEY NOT NULL, NAME VARCHAR(25), BUDGET NUMERIC ) ENGINE=innoDB DEFAULT CHARSET=latin1 !
DROP TABLE PERSON !
CREATE TABLE PERSON (PERSONID INTEGER PRIMARY KEY NOT NULL, FIRSTNAME VARCHAR(255) NULL, LASTNAME VARCHAR(255) NULL, PROJECT_PROJID INTEGER NULL, INSURANCE_INSID INTEGER NULL, TEAM_TEAMID INTEGER NULL) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE ANNUALREVIEW !
CREATE TABLE ANNUALREVIEW (AID INTEGER PRIMARY KEY NOT NULL, SERVICE INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE INSURANCE !
CREATE TABLE INSURANCE (INSID INTEGER PRIMARY KEY NOT NULL, CARRIER VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE PROJECT_PERSON !
CREATE TABLE PROJECT_PERSON (PROJECTS_PROJID INTEGER , PERSONS_PERSONID INTEGER ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE PERSON_ANNUALREVIEW !
CREATE TABLE PERSON_ANNUALREVIEW (PERSON_PERSONID INTEGER, ANNUALREVIEWS_AID INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE PERSON_INSURANCE !
CREATE TABLE PERSON_INSURANCE (PERSON_PERSONID INTEGER, INSURANCE_INSID INTEGER ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE PURCHASE_ORDER !
CREATE TABLE PURCHASE_ORDER (ID INTEGER NOT NULL, TOTAL INTEGER, DESCRIPTION VARCHAR(50), CONSTRAINT PURCHASE_ORDER PRIMARY KEY (ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

ALTER TABLE EMPLOYEE ADD ( CONSTRAINT FK_MGR FOREIGN KEY (FK_MGR) REFERENCES EMPLOYEE (ID) ) !

ALTER TABLE EMPLOYEE ADD ( CONSTRAINT FK_DEPT FOREIGN KEY (FK_DEPT) REFERENCES DEPARTMENT (ID) )!

ALTER TABLE EMPLOYEE ADD ( CONSTRAINT FK_PROJECT FOREIGN KEY (FK_PROJECT) REFERENCES PROJECT (PROJID) )!

ALTER TABLE EMPLOYEE ADD ( CONSTRAINT FK_INS FOREIGN KEY (FK_INS) REFERENCES INSURANCE (INSID) )!

ALTER TABLE PERSON ADD ( CONSTRAINT TEAM_TEAMID FOREIGN KEY (TEAM_TEAMID) REFERENCES TEAM(TEAMID) ) !

ALTER TABLE PERSON ADD ( CONSTRAINT PROJECT_PROJID FOREIGN KEY (PROJECT_PROJID) REFERENCES PROJECT(PROJID)) !

ALTER TABLE PERSON ADD ( CONSTRAINT INSURANCE_INSID FOREIGN KEY (INSURANCE_INSID) REFERENCES INSURANCE(INSID)) !

ALTER TABLE PROJECT_PERSON ADD ( CONSTRAINT PROJECTS_PROJID FOREIGN KEY (PROJECTS_PROJID) references PROJECT(PROJID) ) !

ALTER TABLE PROJECT_PERSON ADD ( CONSTRAINT PERSONS_PERSONID FOREIGN KEY (PERSONS_PERSONID) references PERSON(PERSONID) ) !

ALTER TABLE PERSON_ANNUALREVIEW ADD ( CONSTRAINT ANNUALREVIEWS_AID FOREIGN KEY (ANNUALREVIEWS_AID) references ANNUALREVIEW(AID))  !

ALTER TABLE PERSON_ANNUALREVIEW ADD ( CONSTRAINT PERSON_PERSONID FOREIGN KEY (PERSON_PERSONID) references PERSON(PERSONID) )  !

ALTER TABLE PERSON_INSURANCE ADD ( CONSTRAINT P_PERSONID FOREIGN KEY (PERSON_PERSONID) references PERSON(PERSONID) ) !

ALTER TABLE PERSON_INSURANCE  ADD ( CONSTRAINT INS_INSID FOREIGN KEY (INSURANCE_INSID) references INSURANCE(INSID) )  !

DROP TABLE ORDER1 !
CREATE TABLE ORDER1 (ID INTEGER PRIMARY KEY NOT NULL, TOTALPRICE DOUBLE PRECISION , FK1_FOR_ITEM INTEGER)  ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE ORDER2 !
CREATE TABLE ORDER2 (ID INTEGER PRIMARY KEY NOT NULL, totalPrice DOUBLE PRECISION , FK2_FOR_ITEM INTEGER)  ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE ORDER3 !
CREATE TABLE ORDER3 (ID INTEGER PRIMARY KEY NOT NULL, totalPrice DOUBLE PRECISION , FK3_FOR_ITEM INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE ITEM  !
CREATE TABLE ITEM (ID INTEGER PRIMARY KEY NOT NULL, ITEMNAME VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE ORDER1 add ( constraint FK1_FOR_ITEM Foreign Key (FK1_FOR_ITEM) references ITEM(ID) ) !
ALTER TABLE ORDER2 add ( constraint FK2_FOR_ITEM Foreign Key (FK2_FOR_ITEM) references ITEM(ID) ) !
ALTER TABLE ORDER3 add ( constraint FK3_FOR_ITEM Foreign Key (FK3_FOR_ITEM) references ITEM(ID) ) !

DROP TABLE MEMBER !
CREATE TABLE MEMBER (MEMBER_ID INTEGER NOT NULL, MEMBER_NAME VARCHAR(255), DUES SMALLINT, VERSION INTEGER, DONATION NUMERIC, CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !
 
DROP TABLE ACCOUNT !
CREATE TABLE ACCOUNT (ID INTEGER NOT NULL, BALANCE DOUBLE PRECISION, DEPOSIT DOUBLE PRECISION, WITHDRAW DOUBLE PRECISION, CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE PARTTIMEEMPLOYEE !
CREATE TABLE PARTTIMEEMPLOYEE (ID INT NOT NULL, FIRSTNAME VARCHAR(255) , LASTNAME VARCHAR(255), HIREDATE DATE, SALARY REAL NOT NULL,  ADDRESS_ID VARCHAR(255), STATUS VARCHAR(255), FK_DEPT2 NUMERIC , FK_PROJECT INT, CONSTRAINT PK_PARTTIMEEMPLOYEE PRIMARY KEY (ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !
ALTER TABLE PARTTIMEEMPLOYEE ADD ( CONSTRAINT FK_ADDR FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID) )!

ALTER TABLE PARTTIMEEMPLOYEE ADD CONSTRAINT FK_DEPT2 FOREIGN KEY (FK_DEPT2) REFERENCES DEPARTMENT (ID) !

ALTER TABLE DATES_TABLE DROP foreign key FK_FOR_DATES_TABLE !

DROP TABLE A_BASIC !
CREATE TABLE A_BASIC ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE INT, BASICINTEGER INT, BASICSHORT SMALLINT, BASICBIGSHORT SMALLINT, BASICFLOAT FLOAT, BASICBIGFLOAT FLOAT, BASICLONG BIGINT, BASICBIGLONG BIGINT, BASICDOUBLE DOUBLE, BASICBIGDOUBLE DOUBLE, BASICCHAR CHAR, BASICCHARARRAY VARCHAR(448), BASICBIGCHARARRAY VARCHAR(448), BASICBYTEARRAY   VARBINARY(255), BASICBIGBYTEARRAY  VARBINARY(255), BASICBIGINTEGER DECIMAL(18,0), BASICBIGDECIMAL DECIMAL(18,0), BASICDATE DATE, BASICTIME TIME, BASICCALENDAR DATE, BASICTIMESTAMP TIMESTAMP ) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE DATES_TABLE !
CREATE TABLE DATES_TABLE (ID VARCHAR(255), DATES DATE, FK_FOR_DATES_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE DATES_TABLE ADD (CONSTRAINT FK_FOR_DATES_TABLE  FOREIGN KEY (FK_FOR_DATES_TABLE) REFERENCES A_BASIC(ID)  ON DELETE CASCADE) !

DROP TABLE DATE_TABLE !
CREATE TABLE DATE_TABLE (ID DATE, STRINGVERSION VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!


DROP TABLE A_BIGINTEGER !
CREATE TABLE A_BIGINTEGER ( ID VARCHAR(255), NAME VARCHAR(255) , VALUE INT, BASICINTEGER INT, BASICSHORT SMALLINT, BASICBIGSHORT SMALLINT, BASICFLOAT FLOAT, BASICBIGFLOAT FLOAT, BASICLONG BIGINT, BASICBIGLONG BIGINT, BASICDOUBLE DOUBLE, BASICBIGDOUBLE DOUBLE, BASICCHAR CHAR, BASICCHARARRAY VARCHAR(448), BASICBIGCHARARRAY VARCHAR(448), BASICBYTEARRAY   VARBINARY(255), BASICBIGBYTEARRAY  VARBINARY(255), BASICBIGINTEGER DECIMAL(18,0) PRIMARY KEY NOT NULL, BASICBIGDECIMAL DECIMAL(18,0), BASICDATE DATE, BASICTIME TIME, BASICCALENDAR DATE, BASICTIMESTAMP TIMESTAMP ) !

DROP TABLE A_BIGDECIMAL !
CREATE TABLE A_BIGDECIMAL ( ID VARCHAR(255), NAME VARCHAR(255) , VALUE INT, BASICINTEGER INT, BASICSHORT SMALLINT, BASICBIGSHORT SMALLINT, BASICFLOAT FLOAT, BASICBIGFLOAT FLOAT, BASICLONG BIGINT, BASICBIGLONG BIGINT, BASICDOUBLE DOUBLE, BASICBIGDOUBLE DOUBLE, BASICCHAR CHAR, BASICCHARARRAY VARCHAR(448), BASICBIGCHARARRAY VARCHAR(448), BASICBYTEARRAY   VARBINARY(255), BASICBIGBYTEARRAY  VARBINARY(255), BASICBIGINTEGER DECIMAL(18,0), BASICBIGDECIMAL DECIMAL(18,0) PRIMARY KEY NOT NULL, BASICDATE DATE, BASICTIME TIME, BASICCALENDAR DATE, BASICTIMESTAMP TIMESTAMP )!

DROP TABLE BNE_1XM_BI_BTOB !
CREATE TABLE BNE_1XM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, STREET VARCHAR(255), CITY VARCHAR(255), STATE VARCHAR(255), ZIP VARCHAR(255), PLUSFOUR VARCHAR(255), FK_FOR_ANE_1XM_BI_BTOB VARCHAR(255) ) !

DROP TABLE B_EMBEDDABLE !
CREATE TABLE B_EMBEDDABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, STREET VARCHAR(255), CITY VARCHAR(255), STATE VARCHAR(255), ZIP VARCHAR(255), PLUSFOUR VARCHAR(255)) !

DROP TABLE MEMBER!
CREATE TABLE MEMBER (MEMBER_ID INT NOT NULL, MEMBER_NAME VARCHAR(255), DUES SMALLINT, VERSION INT, DONATION DECIMAL(18,0), CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID))!

DROP TABLE ACCOUNT!
CREATE TABLE ACCOUNT (ID INT NOT NULL, BALANCE DOUBLE, DEPOSIT DOUBLE, WITHDRAW DOUBLE, CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID))!

DROP TABLE SEMESTER!
CREATE TABLE SEMESTER (ID INTEGER NOT NULL, PRIMARY KEY (ID))!

DROP TABLE STUDENT_COURSE!
CREATE TABLE STUDENT_COURSE (Student_ID INTEGER NOT NULL, courses_ID INTEGER NOT NULL, PRIMARY KEY (Student_ID, courses_ID))!

DROP TABLE STUDENT!
CREATE TABLE STUDENT (ID INTEGER NOT NULL, STUDENTNAME VARCHAR(255), PRIMARY KEY (ID))!

DROP TABLE COURSE!
CREATE TABLE COURSE (ID INTEGER NOT NULL, COURSENAME VARCHAR(255), PRIMARY KEY (ID))!

DROP TABLE ENROLLMENTS!
CREATE TABLE ENROLLMENTS (STUDENT INTEGER NOT NULL, ENROLLMENT_KEY INTEGER NOT NULL, SEMESTER INTEGER NOT NULL, PRIMARY KEY (STUDENT, ENROLLMENT_KEY, SEMESTER))!

DROP TABLE COURSE_STUDENT!
CREATE TABLE COURSE_STUDENT (COURSE_ID INTEGER NOT NULL, STUDENT_ID INTEGER NOT NULL, STUDENTS_ORDER INTEGER, PRIMARY KEY (COURSE_ID , STUDENT_ID))!

ALTER TABLE STUDENT_COURSE ADD CONSTRAINT STDNTCOURSEStdntID FOREIGN KEY (Student_ID) REFERENCES STUDENT (ID)!
ALTER TABLE STUDENT_COURSE ADD CONSTRAINT STDNTCOURSEcrsesID FOREIGN KEY (courses_ID) REFERENCES COURSE (ID)!
ALTER TABLE ENROLLMENTS ADD CONSTRAINT ENROLLMENTSSTUDENT FOREIGN KEY (STUDENT) REFERENCES STUDENT (ID)!
ALTER TABLE ENROLLMENTS ADD CONSTRAINT NROLLMENTSSEMESTER FOREIGN KEY (SEMESTER) REFERENCES SEMESTER (ID)!
ALTER TABLE COURSE_STUDENT ADD CONSTRAINT CRSESTUDENTCurseID FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID)!
ALTER TABLE COURSE_STUDENT ADD CONSTRAINT CRSSTUDENTstdntsID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID)!

DROP TABLE NOENTITYLISTENER_TABLE !
CREATE TABLE NOENTITYLISTENER_TABLE(ID BIGINT  PRIMARY KEY NOT NULL) !

DROP TABLE COURSE_2 !
CREATE TABLE COURSE_2(ID BIGINT NOT NULL,NAME VARCHAR(255)) !

DROP TABLE STUDENT_2 !
CREATE TABLE STUDENT_2(ID BIGINT NOT NULL,NAME VARCHAR(255)) !

DROP TABLE STUDENT_2_COURSE_2 !
CREATE TABLE STUDENT_2_COURSE_2(COURSES_ID BIGINT,STUDENTS_ID BIGINT) !

DROP TABLE NAMEONLYINXML !
CREATE TABLE NAMEONLYINXML(ID BIGINT) !

DROP TABLE NAMEONLYINANNOTATION !
CREATE TABLE NAMEONLYINANNOTATION(ID BIGINT) !

DROP TABLE NAMEOVERRIDE !
CREATE TABLE NAMEOVERRIDE (ID BIGINT) !

DROP TABLE NOENTITYANNOTATION !
CREATE TABLE  NOENTITYANNOTATION(ID BIGINT) !

DROP TABLE BOOKSTORE !
CREATE TABLE BOOKSTORE(ID BIGINT NOT NULL,NAME VARCHAR(255),LOCATION VARCHAR(255)) !

DROP TABLE COMPLAINT !
CREATE TABLE COMPLAINT(ID BIGINT NOT NULL, COMPLAINTNUMBER INT, NAME VARCHAR(255), ADDRESS VARCHAR(255)) !

DROP TABLE MOVIETICKET !
CREATE TABLE MOVIETICKET(ID BIGINT NOT NULL, FILMNAME VARCHAR(255), FILMCODE VARCHAR(255)) !

DROP TABLE BOOK !
CREATE TABLE BOOK(ID BIGINT NOT NULL, NAME VARCHAR(255), STATEOFUSA VARCHAR(255)) !

DROP TABLE LAWBOOK !
CREATE TABLE LAWBOOK(ID BIGINT NOT NULL, BOOK_NAME VARCHAR(255), CATEGORY VARCHAR(255),PUBLISHER VARCHAR(255),COST INT) !

DROP TABLE EMPLOYEE_2 !
CREATE TABLE EMPLOYEE_2(ID BIGINT NOT NULL, CODE  VARCHAR(255), DEPARTMENT_ID BIGINT) !

DROP TABLE DEPARTMENT_2 !
CREATE TABLE DEPARTMENT_2(ID BIGINT NOT NULL,NAME  VARCHAR(255)) !

DROP TABLE THEATRELOCATION !
CREATE TABLE THEATRELOCATION(ID BIGINT NOT NULL, CODE  VARCHAR(255)) !

DROP TABLE THEATRECOMPANY !
CREATE TABLE THEATRECOMPANY(ID BIGINT NOT NULL,NAME  VARCHAR(255)) !

DROP TABLE THEATRELOCATION_THEATRECOMPANY !
CREATE TABLE THEATRELOCATION_THEATRECOMPANY(COMPANIES_ID BIGINT, LOCATIONS_ID BIGINT) !

DROP TABLE STORE !
CREATE TABLE STORE(ID BIGINT NOT NULL, NAME VARCHAR(255)) !

DROP TABLE CUSTOMERS !
CREATE TABLE CUSTOMERS(ID BIGINT NOT NULL, CUSTNAME VARCHAR(255), STORE_ID BIGINT) !

DROP TABLE CONSUMER !
CREATE TABLE CONSUMER(ID BIGINT NOT NULL) !

DROP TABLE RETAILORDER !
CREATE TABLE RETAILORDER(ID BIGINT NOT NULL, COST DOUBLE) !

DROP TABLE RETAILORDER_CONSUMER !
CREATE TABLE RETAILORDER_CONSUMER(CONSUMERS_ID  BIGINT NOT NULL,ORDERS_ID  BIGINT NOT NULL) !

DROP TABLE THEATRELOCATION1 !
CREATE TABLE THEATRELOCATION1(ID BIGINT NOT NULL, CODE  VARCHAR(255),TCOMP_ID BIGINT) !

DROP TABLE THEATRECOMPANY1 !
CREATE TABLE THEATRECOMPANY1(ID BIGINT NOT NULL,NAME  VARCHAR(255)) !

DROP TABLE CUBICLE !
CREATE TABLE CUBICLE(ID BIGINT NOT NULL , LOCATION VARCHAR(255), PRIMARY KEY(ID,LOCATION)) !

DROP TABLE HARDWARE !
CREATE TABLE HARDWARE(ID BIGINT NOT NULL, CODE VARCHAR(255),CUBE_ID BIGINT NOT NULL, CUBE_LOCATION VARCHAR(255)) !

DROP TABLE CUSTOMER1 !
CREATE TABLE CUSTOMER1(ID BIGINT NOT NULL, NAME VARCHAR(255), CONSTRAINT PK_CUSTOMER1 PRIMARY KEY (ID)) !

DROP TABLE RETAILORDER1 !
CREATE  TABLE RETAILORDER1(ID BIGINT NOT NULL, COST DOUBLE) !

DROP TABLE CUST_ORDER !
CREATE TABLE  CUST_ORDER(CUSTID BIGINT NOT NULL,ORDERID BIGINT NOT NULL) !


DROP TABLE RETAILORDER2 !
CREATE  TABLE RETAILORDER2(ID BIGINT NOT NULL, COST DOUBLE, FK_FOR_CUSTOMER1 BIGINT ) !

ALTER TABLE RETAILORDER2 ADD CONSTRAINT FK_FOR_CUST FOREIGN KEY(FK_FOR_CUSTOMER1) REFERENCES CUSTOMER1(ID) !

ALTER TABLE UNI1X1PERSON drop foreign key  N1X1PRSNPRJCTPRJID !
DROP TABLE UNI1X1PROJECT !
DROP TABLE UNI1X1PERSON !


CREATE TABLE UNI1X1PROJECT (PROJID BIGINT NOT NULL, BUDGET FLOAT, NAME VARCHAR(255), PRIMARY KEY (PROJID)) !
CREATE TABLE UNI1X1PERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PROJECT_PROJID BIGINT, PRIMARY KEY (ID)) !
ALTER TABLE UNI1X1PERSON ADD CONSTRAINT N1X1PRSNPRJCTPRJID FOREIGN KEY (PROJECT_PROJID) REFERENCES UNI1X1PROJECT (PROJID) !


ALTER TABLE UNI1XMPERSON_UNI1XMPROJECT DROP foreign key N1XMPRSNNn1XMPrsnD !
ALTER TABLE UNI1XMPERSON_UNI1XMPROJECT drop foreign key  N1XMPRSNN1XprjctsD !
DROP TABLE UNI1XMPERSON_UNI1XMPROJECT !
DROP TABLE UNI1XMPROJECT !
DROP TABLE UNI1XMPERSON !

CREATE TABLE UNI1XMPERSON_UNI1XMPROJECT (Uni1XMPerson_ID BIGINT NOT NULL, projects_ID BIGINT NOT NULL, PRIMARY KEY (Uni1XMPerson_ID, projects_ID)) !
CREATE TABLE UNI1XMPROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID)) !
CREATE TABLE UNI1XMPERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID)) !
ALTER TABLE UNI1XMPERSON_UNI1XMPROJECT ADD CONSTRAINT N1XMPRSNNn1XMPrsnD FOREIGN KEY (Uni1XMPerson_ID) REFERENCES UNI1XMPERSON (ID) !
ALTER TABLE UNI1XMPERSON_UNI1XMPROJECT ADD CONSTRAINT N1XMPRSNN1XprjctsD FOREIGN KEY (projects_ID) REFERENCES UNI1XMPROJECT (ID) !


ALTER TABLE UNIMX1PERSON drop foreign key  NMX1PRSNNMX1PRJCTD !
DROP TABLE UNIMX1PROJECT !
DROP TABLE UNIMX1PERSON !

CREATE TABLE UNIMX1PROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID)) !
CREATE TABLE UNIMX1PERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), UNIMX1PROJECT_ID BIGINT, PRIMARY KEY (ID)) !
ALTER TABLE UNIMX1PERSON ADD CONSTRAINT NMX1PRSNNMX1PRJCTD FOREIGN KEY (UNIMX1PROJECT_ID) REFERENCES UNIMX1PROJECT (ID) !


ALTER TABLE UNIMXMPERSON_UNIMXMPROJECT drop foreign key  NMXMPRSNNnMXMPrsnD !
ALTER TABLE UNIMXMPERSON_UNIMXMPROJECT drop foreign key  NMXMPRSNnMXMPrjctD !
DROP TABLE UNIMXMPERSON !
DROP TABLE UNIMXMPROJECT !
DROP TABLE UNIMXMPERSON_UNIMXMPROJECT !

CREATE TABLE UNIMXMPERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID)) !
CREATE TABLE UNIMXMPROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID)) !
CREATE TABLE UNIMXMPERSON_UNIMXMPROJECT (UniMXMPerson_ID BIGINT NOT NULL, UniMXMProject_ID BIGINT NOT NULL, PRIMARY KEY (UniMXMPerson_ID, UniMXMProject_ID)) !
ALTER TABLE UNIMXMPERSON_UNIMXMPROJECT ADD CONSTRAINT NMXMPRSNNnMXMPrsnD FOREIGN KEY (UniMXMPerson_ID) REFERENCES UNIMXMPERSON (ID) !
ALTER TABLE UNIMXMPERSON_UNIMXMPROJECT ADD CONSTRAINT NMXMPRSNnMXMPrjctD FOREIGN KEY (UniMXMProject_ID) REFERENCES UNIMXMPROJECT (ID) !


ALTER TABLE BIDIR1X1PERSON drop foreign key  BDR1X1PRSPRJCTPRJD !
DROP TABLE BIDIR1X1PERSON !
DROP TABLE BIDIR1X1PROJECT !

CREATE TABLE BIDIR1X1PERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PROJECT_PROJID BIGINT, PRIMARY KEY (ID)) !
CREATE TABLE BIDIR1X1PROJECT (PROJID BIGINT NOT NULL, BUDGET FLOAT, NAME VARCHAR(255), PRIMARY KEY (PROJID)) !
ALTER TABLE BIDIR1X1PERSON ADD CONSTRAINT BDR1X1PRSPRJCTPRJD FOREIGN KEY (PROJECT_PROJID) REFERENCES BIDIR1X1PROJECT (PROJID) !


ALTER TABLE BIDIR1XMPROJECT drop foreign key  BDR1XMPBDR1XMPRSND !
DROP TABLE BIDIR1XMPERSON !
DROP TABLE BIDIR1XMPROJECT !

CREATE TABLE BIDIR1XMPERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID)) !
CREATE TABLE BIDIR1XMPROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, BIDIR1XMPERSON_ID BIGINT, PRIMARY KEY (ID)) !
ALTER TABLE BIDIR1XMPROJECT ADD CONSTRAINT BDR1XMPBDR1XMPRSND FOREIGN KEY (BIDIR1XMPERSON_ID) REFERENCES BIDIR1XMPERSON (ID) !


ALTER TABLE BIDIRMX1PERSON drop foreign key  BDRMX1PRNMX1PRJCTD !
DROP TABLE BIDIRMX1PROJECT !
DROP TABLE BIDIRMX1PERSON !

CREATE TABLE BIDIRMX1PROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID)) !
CREATE TABLE BIDIRMX1PERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), UNIMX1PROJECT_ID BIGINT, PRIMARY KEY (ID)) !
ALTER TABLE BIDIRMX1PERSON ADD CONSTRAINT BDRMX1PRNMX1PRJCTD FOREIGN KEY (UNIMX1PROJECT_ID) REFERENCES BIDIRMX1PROJECT (ID) !


ALTER TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT drop foreign key  BDRMXMPBDRMXMPrsnD !
ALTER TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT drop foreign key  BDRMXMBDRMXMPrjctD !
DROP TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT !
DROP TABLE BIDIRMXMPERSON !
DROP TABLE BIDIRMXMPROJECT !

CREATE TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT (BIDIRMXMPerson_ID BIGINT NOT NULL, BIDIRMXMProject_ID BIGINT NOT NULL, PRIMARY KEY (BIDIRMXMPerson_ID, BIDIRMXMProject_ID)) !
CREATE TABLE BIDIRMXMPERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID)) !
CREATE TABLE BIDIRMXMPROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID)) !
ALTER TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT ADD CONSTRAINT BDRMXMPBDRMXMPrsnD FOREIGN KEY (BIDIRMXMPerson_ID) REFERENCES BIDIRMXMPERSON (ID) !
ALTER TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT ADD CONSTRAINT BDRMXMBDRMXMPrjctD FOREIGN KEY (BIDIRMXMProject_ID) REFERENCES BIDIRMXMPROJECT (ID) !


ALTER TABLE DID1DEPENDENT drop foreign key  DID1DEPENDENTEMPID !
DROP TABLE DID1DEPENDENT !
DROP TABLE DID1EMPLOYEE !

CREATE TABLE DID1DEPENDENT (NAME VARCHAR(255) NOT NULL, EMP_ID BIGINT NOT NULL, PRIMARY KEY (NAME, EMP_ID)) !
CREATE TABLE DID1EMPLOYEE (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID)) !
ALTER TABLE DID1DEPENDENT ADD CONSTRAINT DID1DEPENDENTEMPID FOREIGN KEY (EMP_ID) REFERENCES DID1EMPLOYEE (ID) !


ALTER TABLE DID1BDEPENDENT drop foreign key  DID1BDEPENDENTMPID !
DROP TABLE DID1BDEPENDENT !
DROP TABLE DID1BEMPLOYEE !

CREATE TABLE DID1BDEPENDENT (NAME VARCHAR(255) NOT NULL, EMP_ID BIGINT NOT NULL, PRIMARY KEY (NAME, EMP_ID)) !
CREATE TABLE DID1BEMPLOYEE (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID)) !
ALTER TABLE DID1BDEPENDENT ADD CONSTRAINT DID1BDEPENDENTMPID FOREIGN KEY (EMP_ID) REFERENCES DID1BEMPLOYEE (ID) !


ALTER TABLE DID2DEPENDENT drop foreign key  DD2DPENDENTFRSTNME !
DROP TABLE DID2EMPLOYEE !
DROP TABLE DID2DEPENDENT !

CREATE TABLE DID2EMPLOYEE (FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, EMPNO INTEGER, PRIMARY KEY (FIRSTNAME, LASTNAME)) !
CREATE TABLE DID2DEPENDENT (NAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME, FIRSTNAME, LASTNAME)) !
ALTER TABLE DID2DEPENDENT ADD CONSTRAINT DD2DPENDENTFRSTNME FOREIGN KEY (FIRSTNAME, LASTNAME) REFERENCES DID2EMPLOYEE (FIRSTNAME, LASTNAME) !


ALTER TABLE DID2BDEPENDENT drop foreign key  DD2BDPENDENTLSTNME !
DROP TABLE DID2BEMPLOYEE !
DROP TABLE DID2BDEPENDENT !

CREATE TABLE DID2BEMPLOYEE (LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, EMPNO INTEGER, PRIMARY KEY (LASTNAME, FIRSTNAME)) !
CREATE TABLE DID2BDEPENDENT (NAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME, LASTNAME, FIRSTNAME)) !
ALTER TABLE DID2BDEPENDENT ADD CONSTRAINT DD2BDPENDENTLSTNME FOREIGN KEY (LASTNAME, FIRSTNAME) REFERENCES DID2BEMPLOYEE (LASTNAME, FIRSTNAME) !


ALTER TABLE DID3DEPENDENT drop foreign key  DD3DPENDENTFRSTNME !
DROP TABLE DID3EMPLOYEE !
DROP TABLE DID3DEPENDENT !

CREATE TABLE DID3EMPLOYEE (FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (FIRSTNAME, LASTNAME)) !
CREATE TABLE DID3DEPENDENT (NAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME, FIRSTNAME, LASTNAME)) !
ALTER TABLE DID3DEPENDENT ADD CONSTRAINT DD3DPENDENTFRSTNME FOREIGN KEY (FIRSTNAME, LASTNAME) REFERENCES DID3EMPLOYEE (FIRSTNAME, LASTNAME) !


ALTER TABLE DID3BDEPENDENT drop foreign key  DD3BDPENDENTLSTNME !
DROP TABLE DID3BEMPLOYEE !
DROP TABLE DID3BDEPENDENT !

CREATE TABLE DID3BEMPLOYEE (LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (LASTNAME, FIRSTNAME)) !
CREATE TABLE DID3BDEPENDENT (NAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME, LASTNAME, FIRSTNAME)) !
ALTER TABLE DID3BDEPENDENT ADD CONSTRAINT DD3BDPENDENTLSTNME FOREIGN KEY (LASTNAME, FIRSTNAME) REFERENCES DID3BEMPLOYEE (LASTNAME, FIRSTNAME) !


ALTER TABLE DID4MEDICALHISTORY drop foreign key  DD4MDCLHSTRPTNTSSN !
DROP TABLE DID4MEDICALHISTORY !
DROP TABLE DID4PERSON !

CREATE TABLE DID4MEDICALHISTORY (DOCTORNAME VARCHAR(255), PATIENT_SSN VARCHAR(255) NOT NULL, PRIMARY KEY (PATIENT_SSN)) !
CREATE TABLE DID4PERSON (SSN VARCHAR(255) NOT NULL, NAME VARCHAR(255), PRIMARY KEY (SSN)) !
ALTER TABLE DID4MEDICALHISTORY ADD CONSTRAINT DD4MDCLHSTRPTNTSSN FOREIGN KEY (PATIENT_SSN) REFERENCES DID4PERSON (SSN) !


ALTER TABLE DID4BMEDICALHISTORY drop foreign key  DD4BMDCLHSTPTNTSSN !
DROP TABLE DID4BMEDICALHISTORY !
DROP TABLE DID4BPERSON !

CREATE TABLE DID4BMEDICALHISTORY (ID VARCHAR(255) NOT NULL, DOCTORNAME VARCHAR(255), PRIMARY KEY (ID)) !
CREATE TABLE DID4BPERSON (SSN VARCHAR(255) NOT NULL, NAME VARCHAR(255), PRIMARY KEY (SSN)) !
ALTER TABLE DID4BMEDICALHISTORY ADD CONSTRAINT DD4BMDCLHSTPTNTSSN FOREIGN KEY (ID) REFERENCES DID4BPERSON (SSN) !

ALTER TABLE DID5MEDICALHISTORY drop foreign key  DD5MDCLHSTRYFRSTNM !
DROP TABLE DID5PERSON !
DROP TABLE DID5MEDICALHISTORY !

CREATE TABLE DID5PERSON (FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, SSN VARCHAR(255), PRIMARY KEY (FIRSTNAME, LASTNAME)) !
CREATE TABLE DID5MEDICALHISTORY (DOCTORNAME VARCHAR(255), FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (FIRSTNAME, LASTNAME)) !
ALTER TABLE DID5MEDICALHISTORY ADD CONSTRAINT DD5MDCLHSTRYFRSTNM FOREIGN KEY (FIRSTNAME, LASTNAME) REFERENCES DID5PERSON (FIRSTNAME, LASTNAME) !


ALTER TABLE DID5BMEDICALHISTORY drop foreign key  DD5BMDCLHSTRYLSTNM !
DROP TABLE DID5BMEDICALHISTORY !
DROP TABLE DID5BPERSON !

CREATE TABLE DID5BMEDICALHISTORY (DOCTORNAME VARCHAR(255), LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (LASTNAME, FIRSTNAME)) !
CREATE TABLE DID5BPERSON (LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, SSN VARCHAR(255), PRIMARY KEY (LASTNAME, FIRSTNAME)) !
ALTER TABLE DID5BMEDICALHISTORY ADD CONSTRAINT DD5BMDCLHSTRYLSTNM FOREIGN KEY (LASTNAME, FIRSTNAME) REFERENCES DID5BPERSON (LASTNAME, FIRSTNAME) !


ALTER TABLE DID6MEDICALHISTORY drop foreign key  DD6MDCLHSTRYFRSTNM !
DROP TABLE DID6MEDICALHISTORY !
DROP TABLE DID6PERSON !

CREATE TABLE DID6MEDICALHISTORY (DOCTORNAME VARCHAR(255), FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (FIRSTNAME, LASTNAME)) !
CREATE TABLE DID6PERSON (SSN VARCHAR(255), FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (FIRSTNAME, LASTNAME)) !
ALTER TABLE DID6MEDICALHISTORY ADD CONSTRAINT DD6MDCLHSTRYFRSTNM FOREIGN KEY (FIRSTNAME, LASTNAME) REFERENCES DID6PERSON (FIRSTNAME, LASTNAME) !

ALTER TABLE DID6BMEDICALHISTORY drop foreign key  DD6BMDCLHSTRYLSTNM !
DROP TABLE DID6BPERSON !
DROP TABLE DID6BMEDICALHISTORY !

CREATE TABLE DID6BPERSON (SSN VARCHAR(255), LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (LASTNAME, FIRSTNAME)) !
CREATE TABLE DID6BMEDICALHISTORY (DOCTORNAME VARCHAR(255), LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (LASTNAME, FIRSTNAME)) !
ALTER TABLE DID6BMEDICALHISTORY ADD CONSTRAINT DD6BMDCLHSTRYLSTNM FOREIGN KEY (LASTNAME, FIRSTNAME) REFERENCES DID6BPERSON (LASTNAME, FIRSTNAME) !

DROP TABLE A_ADDRESS !
CREATE TABLE A_ADDRESS ( A_ID VARCHAR(255) NOT NULL,  STREET VARCHAR(30), CITY VARCHAR(30), STATE VARCHAR(2), ZIP VARCHAR(10)) !

DROP TABLE COLTAB_ADDRESS !
CREATE TABLE COLTAB_ADDRESS ( A_ID VARCHAR(255) NOT NULL,  STREET VARCHAR(30), CITY VARCHAR(30), STATE VARCHAR(2), ZIP VARCHAR(10) ) !

DROP TABLE AEC !
CREATE TABLE AEC ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) ) !

DROP TABLE COLTAB !
CREATE TABLE COLTAB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) ) !

DROP TABLE ANE_1XM_BI_BTOB !
CREATE TABLE ANE_1XM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL ) !
ALTER TABLE BNE_1XM_BI_BTOB ADD CONSTRAINT FK_FOR_ANE_1XM_BI FOREIGN KEY (FK_FOR_ANE_1XM_BI_BTOB) REFERENCES ANE_1XM_BI_BTOB (ID) !

DROP TABLE EMP_MAPKEYCOL !
CREATE TABLE EMP_MAPKEYCOL(ID NUMERIC NOT NULL, FIRSTNAME VARCHAR(255) , LASTNAME VARCHAR(255), HIREDATE DATE NULL, SALARY REAL NOT NULL, STATUS VARCHAR(255),  FK_MGR NUMERIC, FK_DEPT NUMERIC, FK_DEPT3 NUMERIC, FK_DEPT4 NUMERIC, FK_PROJECT INTEGER , FK_INS INTEGER, OFFICE_ID VARCHAR(255), LASTNAMEEMPLOYEES_KEY VARCHAR(255), CONSTRAINT PK_EMPLOYEE PRIMARY KEY(ID) ) ENGINE=innoDB DEFAULT CHARSET=latin1!
ALTER TABLE EMP_MAPKEYCOL ADD ( CONSTRAINT FK_DEPT1 FOREIGN KEY (FK_DEPT) REFERENCES DEPARTMENT (ID))!
ALTER TABLE EMP_MAPKEYCOL ADD ( CONSTRAINT FK_DEPT3 FOREIGN KEY (FK_DEPT3) REFERENCES DEPARTMENT (ID)) !
ALTER TABLE EMP_MAPKEYCOL ADD ( CONSTRAINT FK_DEPT4 FOREIGN KEY (FK_DEPT4) REFERENCES DEPARTMENT (ID)) !

DROP TABLE EMP_MAPKEYCOL2 !
CREATE TABLE EMP_MAPKEYCOL2(ID NUMERIC NOT NULL, LASTNAME VARCHAR(255), THEDATE DATE ,FK_DEPT5 INT,  CONSTRAINT PK_EMP2 PRIMARY KEY(ID) ) ENGINE=innoDB DEFAULT CHARSET=latin1!
ALTER TABLE EMP_MAPKEYCOL2 ADD ( CONSTRAINT FK_DEPT5 FOREIGN KEY (FK_DEPT5) REFERENCES DEPARTMENT2 (ID)) !

ALTER TABLE COLTAB_EMP_EMBEDED_ADDRESS drop foreign key  FK_EMPEMBADDRID !
DROP TABLE COLTAB_EMP_EMBEDED_ADDRESS !
DROP TABLE EMPLOYEE_EMBEDED_ADDRESS !
CREATE TABLE EMPLOYEE_EMBEDED_ADDRESS (ID INTEGER NOT NULL, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), PRIMARY KEY (ID)) !
CREATE TABLE COLTAB_EMP_EMBEDED_ADDRESS (ADDRESS_LOCATION VARCHAR(255), STREET VARCHAR(255), STATE VARCHAR(255), ZIP VARCHAR(255), CITY VARCHAR(255), ID VARCHAR(255), EMPEMBADDRID INTEGER) !
ALTER TABLE COLTAB_EMP_EMBEDED_ADDRESS ADD ( CONSTRAINT FK_EMPEMBADDRID FOREIGN KEY (EMPEMBADDRID) REFERENCES EMPLOYEE_EMBEDED_ADDRESS (ID) ) !

DROP TABLE IF EXISTS UUIDTYPE !
CREATE TABLE UUIDTYPE (ID VARCHAR(96) NOT NULL PRIMARY KEY, NAME VARCHAR(255)) !

DROP TABLE IF EXISTS CRITERIA_TEST_COLTABLE !
DROP TABLE IF EXISTS CRITERIA_TEST_TABLE !
CREATE TABLE CRITERIA_TEST_TABLE (ID INTEGER PRIMARY KEY NOT NULL, DATE_VAL DATE, INT_VAL INTEGER, STR_VAL_1 VARCHAR(255), STR_VAL_2 VARCHAR(255), TIME_VAL TIME(6)) !
CREATE TABLE CRITERIA_TEST_COLTABLE(ENT_ID INTEGER NOT NULL, COLVAL VARCHAR(255), CONSTRAINT FK_CRITERIA_TEST_COLTABLE_ENT_ID FOREIGN KEY (ENT_ID) REFERENCES CRITERIA_TEST_TABLE (ID))!
