/*
 * Copyright (c) 2008, 2023 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0,
 * or the Eclipse Distribution License v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

// Contributors:
//     Linda DeMichiel - 2.1
//     Linda DeMichiel - 2.0


package jakarta.persistence.metamodel;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The {@code StaticMetamodel} annotation specifies that the class is
 * a metamodel class that represents the Java type designated by the
 * {@link #value} element. The Java type might be:
 * <ul>
 * <li>an entity class, mapped superclass, or embeddable class,
 * <li>a class with one or more {@link jakarta.persistence.NamedQuery}
 *    or {@link jakarta.persistence.NamedNativeQuery} annotations, or
 * <li>a class with one or more methods annotated
 *     {@link jakarta.persistence.query.StaticQuery} or
 *     {@link jakarta.persistence.query.StaticNativeQuery}.
 * </ul>
 *
 * <p>Typically, a static metamodel class is generated by an annotation
 * processor according to the specification of the Jakarta Persistence
 * <em>canonical metamodel</em>. Metamodel classes which do not
 * conform to this specification are not portable between persistence
 * providers.
 *
 * <p>The canonical metamodel for a class {@code X} belongs to the same
 * package as {@code X}, and is named {@code X_}.
 *
 * <p>Suppose the persistence unit contains the following entity class:
 * {@snippet :
 * package org.example;
 * import jakarta.persistence.*;
 *
 * @Entity class Book {
 *     @Id String isbn;
 *     ...
 * }
 * }
 * <p>Then the canonical metamodel class is {@code org.example.Book_}.
 * {@snippet :
 * import org.example.*;
 * import jakarta.persistence.*;
 * ...
 *     EntityType<Book> bookType = Book_.class_;
 *     SingularAttribute<Book,String> isbn = Book_.isbn;
 * }
 *
 * <p>Similarly, suppose the persistence unit contains the following
 * interface annotated {@code @NamedQuery}:
 * {@snippet :
 * package com.acme.orders;
 * import jakarta.persistence.*;
 *
 * @NamedQuery(name = "allOrdersBySku",
 *             query = "select o from Order o join i.items i where i.sku = ?1")
 * ...
 * interface OrderQueries { ... }
 * }
 * <p>Then the canonical metamodel class is {@code com.acme.orders.OrderQueries_}.
 * {@snippet :
 * import com.acme.orders.*;
 * import jakarta.persistence.*;
 * ...
 *     var ordersForSku =
 *             entityManager.createQuery(OrderQueries_._allOrdersBySku_)
 *                     .setParameter(1, sku)
 *                     .getResults();
 * }
 * <p>Note that the canonical metamodel field for the named query
 * {@code allOrdersBySku} is named {@code _allOrdersBySku_} to avoid
 * naming collisions.
 *
 * @since 2.0
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface StaticMetamodel {

    /** 
     * Class being modelled by the annotated class.
     */
    Class<?> value();
}
